### ISSUE TITLE
Locale ($LC_TIME) should automatically determine datetime parsing

### ISSUE THREAD

**Issue by lmmx** [insanum/gcalcli#143]
I changed my config file locale to 'en_GB.utf-8' but it wasn't change date format parsing but am still getting MM/DD format when parsing via `add` :confused:

Just checked my Python and all the modules are installed, so doesn't seem to be an error there.

Is anyone else successfully using DD/MM/YY[YY] format ?

**Comment by Purgator** [comment]
As I understand, we have to wait for someone to make a pull request for that feature ?
Assuming we are at least some people to use this tool, how do you guys process to add an event ? I can't rely on a broken format as MM/DD/YYYY that so far from any logic.

Any workaround to use a DD/MM/YYYY or YYYY/MM/DD ?

Thx !

**Comment by Purgator** [comment]
I found it !
You can set the locale by using the following parameter :
--locale 'en_US.utf8' for example. It need to be loaded on your system.
Take a look at locale -a.

**Comment by githubgnulinux** [comment]
gcalcli --locale='en_GB.utf8'
Error: no command
gcalcli --locale 'en_GB.utf8'
Error: no command
gcalcli --locale en_GB.utf8
Error: no command
gcalcli --locale="en_GB.utf8"
Error: no command

How to change the terminal output:

Sun Jan 01

to:

Sun 01 Jan

**Comment by tresni** [comment]
`--locale` only changes what character set is supported, not the output of any date/time strings.

**Comment by dbarnett** [comment]
Hello from 2024!

Please see #542 for adding format hints and manual config for these date formats.

---

Beyond that, I agree it's surprising it picks arbitrary date formats irrespective of locale settings. Seems complicated to fix but I'd still like to fix it eventually. See my comments about it [in #655](https://github.com/insanum/gcalcli/issues/655#issuecomment-2311669439):

> The dates it parses from input ideally would depend on your system locale (especially LC_TIME on Mac and Linux), but I'm not finding any date parsing libraries that know how to respect system locale like that. dateutil that we use [apparently doesn't](https://stackoverflow.com/a/29548727) and others I found like [dateparser](https://dateparser.readthedocs.io/) support some locale-awareness but not well enough to handle this properly.
