### ISSUE TITLE
Don't import duplicate events

### ISSUE THREAD

**Issue by ppawel** [insanum/gcalcli#150]
When you run the `import` command twice it will import the same events all over again. This is not ideal if you want to set up scheduled sync with an external ical/ics feed - at every sync you will get the same events in your calendar if they are still in the feed.

**Comment by insanum** [comment]
Push up some changes that handle tracking event uids. It needs testing. 928a9dfdcfdc7eb73c379ba15f9185ff03ef7888

See #184 for further discussion.

**Comment by insanum** [comment]
Actually see #47 for further progress on this enhancement.
