### ISSUE TITLE
Cannot login.

### ISSUE THREAD

**Issue by molikto** [insanum/gcalcli#151]
I used `gcalcli list --noauth_local_webserver` to try to auth my account, but even so I cannot login, after I past the code, nothing happens. is there any way i can get more debug information? using OS X 10.10

**Comment by tresni** [comment]
I've tested again on 10.10.2 and I'm still not able to reproduce this.  I am given the URL, I visit the URL, authetnicate, copy the code, paste the code in the terminal, hit return and am given "Authentication successful."
