### ISSUE TITLE
keep getting error whatever command.

### ISSUE THREAD

**Issue by ghost** [insanum/gcalcli#152]
getting the following to whatever command I try. using python 2.7.6, installed python-googleapi, python-gflags, easy_install --upgrade google-api-python-client, python-dateutil (already installed..). Please help, was great when it worked before..

Traceback (most recent call last):
  File "./gcalcli", line 369, in <module>
    class gcalcli:
  File "./gcalcli", line 388, in gcalcli
    dateParser    = DateTimeParser()
  File "./gcalcli", line 321, in **init**
    self.pdtCalendar = parsedatetime.Calendar()
  File "/usr/lib/python2.7/dist-packages/parsedatetime/**init**.py", line 216, in **init**
    self.ptc = Constants()
  File "/usr/lib/python2.7/dist-packages/parsedatetime/**init**.py", line 1733, in **init**
    self.locale = pdtLocales['icu'](self.localeID)
  File "/usr/lib/python2.7/dist-packages/parsedatetime/pdt_locales.py", line 151, in **init**
    self.icu = pyicu.Locale(localeID)
icu.InvalidArgsError: (<type 'icu.Locale'>, '**init**', (None,))

**Comment by HollowProductions** [comment]
Can you please help me.  I'm getting the same issue as you (i've followed those exact steps) but i still get the exact same error code you got before.

**Comment by absando** [comment]
What versions of python packages are you running?

Machine-name~$  pip list

Here are mine.. 

apt-xapian-index (0.45)
argparse (1.2.1)
chardet (2.0.1)
colorama (0.2.5)
command-not-found (0.3)
dateutils (0.6.6)
debtagshw (0.1)
defer (1.0.6)
dirspec (13.10)
dnspython (1.11.1)
gcalcli (3.1)
google-api-python-client (1.3.1)
html5lib (0.999)
httplib2 (0.8)
lxml (3.3.3)
oauth2client (1.4.1)
oauthlib (0.6.1)
oneconf (0.3.7)
PAM (0.4.2)
parsedatetime (1.2)
pexpect (3.1)
Pillow (2.3.0)
pip (1.5.4)
piston-mini-client (0.7.5)
psutil (1.2.1)
pyasn1 (0.1.7)
pyasn1-modules (0.0.5)
PyBluez (0.18)
pycrypto (2.6.1)
pycups (1.9.66)
pycurl (7.19.3)
pygobject (3.12.0)
PyICU (1.8)
pyOpenSSL (0.13)
pyserial (2.6)
pysmbc (1.0.14.1)
python-apt (0.9.3.5)
python-dateutil (1.5)
python-debian (0.1.21-nmu2ubuntu2)
python-gflags (2.0)
pytz (2014.9)
pyxdg (0.25)
reportlab (3.0)
requests (2.2.1)
rsa (3.1.4)
sessioninstaller (0.0.0)
setuptools (3.3)
simplejson (3.3.1)
six (1.5.2)
software-center-aptd-plugins (0.0.0)
ssh-import-id (3.21)
Twisted-Core (13.2.0)
Twisted-Web (13.2.0)
uritemplate (0.6)
urllib3 (1.7.1)
wsgiref (0.1.2)
zope.interface (4.0.5)
