### ISSUE TITLE
Remove gflags dependancy

### ISSUE THREAD

**Issue by tresni** [insanum/gcalcli#165]
gflags has not been maintained for 2 years.  It works, but Google has actually moved all their python projects back to argparse.  We should look at doing the same.

**Comment by tresni** [comment]
Note to self: Always push local branches **before** you do a clean install of OS...  So much work, gone.. :cry:

**Comment by insanum** [comment]
I feel your pain and I've been there before. This led me to start using unison. It's awesome as it runs over ssh via a cron job. I sync multiple systems this way and never had a problem since. Love it.

**Comment by tresni** [comment]
For anyone who wants to see where this is going: https://github.com/insanum/gcalcli/compare/argparse_over_gflags

Notable Changes:

* removed `--flagfile=<file>` in favor of argparse `@<file>` syntax
* removed the `--detail_*` flags in favor of `--detail [all|calendar|location|url|...]`

Lots of TODO's still...

**Comment by polyzen** [comment]
Is this ready for consumption? :)

**Comment by tresni** [comment]
Yes-ish. It means that there are a lot of behavior changes in how we parse command line options that I haven't documented yet, but `gcalcli --help` will likely get you the info you need. I have been using it and tried to test all the angles, but I may have missed things. So think of it as alpha ready.

**Comment by tresni** [comment]
This has been done.  See instructions in https://github.com/insanum/gcalcli/issues/237#issuecomment-242869754
