### ISSUE TITLE
Support multiple accounts

### ISSUE THREAD

**Issue by justmytwospence** [insanum/gcalcli#167]
Is there any way to make this work with both a personal and a work google calendar account?

**Comment by boyanpenkov** [comment]
Have folks gotten this to work?  I can't; one account is plain-vanilla google, and the other is google apps for enterprise.  Does that make a difference?

I can see output when I do 'gcacli --configFolder mydir list', but not when I ask for 'agenda'

**Comment by tresni** [comment]
I use this personally for my work vs personal accounts.  Do the other commands produce output (calm/calw)?

**Comment by boyanpenkov** [comment]
Yes, they do -- both calm and calw return the grid, with no scheduled 
items.  calw does get the date correct.

How do I check to make sure my institution's Google apps install allows 
the retrieval method?

On 02/02/2016 10:19 PM, Brian Hartvigsen wrote:
>
> I use this personally for my work vs personal accounts. Do the other 
> commands produce output (calm/calw)?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/insanum/gcalcli/issues/167#issuecomment-178979360>.
>

-- 
Boyan Penkov
boyanpenkov.com <www.boyanpenkov.com>

**Comment by rafi** [comment]
Have you considered supporting multiple accounts at the same time? This is really valuable because most programmers have more than one Google account.
