### ISSUE TITLE
Stripping of unicode/Emoji possible?

### ISSUE THREAD

**Issue by Cantello** [insanum/gcalcli#17]
Some calendars that I share with friends/family tend to use Emoji characters (see http://www.unicode.org/charts/PDF/U1F300.pdf). These are correctly displayed (albeit with a light background on an otherwise dark terminal for non-standard emojis) but overlapping with the next character, rendering the beginning of calendar entries illegible (see http://cl.ly/1T0j2Z2v2i0t3J203E3Y)

Is it somehow possible to strip these characters from the text that gcalcli displays?

**Comment by jcrowgey** [comment]
We now use the native encoding of the environment to output.  If the issue was actually due to glyph rendering with particular fonts, that's out of scope for us, I think---the user should change fonts to one that supports the characters that they use.
