### ISSUE TITLE
Move all strings to unicode internally

### ISSUE THREAD

**Issue by tresni** [insanum/gcalcli#170]
Trying to bring over the [unicodelineart](https://github.com/insanum/gcalcli/tree/unicodelineart) branch shows that we still have lots of issues with unicode vs ascii string handling.  What may be the best idea is to use unicode everywhere internally and then decode on output.  Also means that all input strings (anything from Google and/or user) should be checked for type unicode and encoded if it is not.

**Comment by jcrowgey** [comment]
I believe we're doing this now by using six and our _u function on text.  Closing as fixed.  If this is not the case, let's reopen.
