### ISSUE TITLE
Export to HTML

### ISSUE THREAD

**Issue by phavx** [insanum/gcalcli#174]
I'd like to be able to make some exports I can just "dump" into a HTML page, probably into the \<pre\>-tag(to include in my personal startpage and as backup in case no network is available).

Needed for that would be automatic conversion of some characters, f.e. umlauts to their &Xuml; variant and also line drawing characters to their respective representation.

**Comment by insanum** [comment]
I think this is something that would be much better handled outside of gcalcli. Initial thought is to run gcalcli with the --tsv flag and pipe that output to a script. This script could to anything you want regarding final formatting/rendering.

If you were to pursue this then please share your script and I think it's something we would pull in and distribute.
