### ISSUE TITLE
Feature request: hide events that I've removed from gcal

### ISSUE THREAD

**Issue by sagotsky** [insanum/gcalcli#175]
Preface: I have no idea if gcal's api makes this data available.  I won't take it personally if what I'm requesting is impossible due to limitations of the api.

In gcal, when I click on an event to which I've been invited I can RSVP.  I next to the RSVP options I can also remove the item from my calendar, which hides it from gcal.

When I view that calendar in gcalcli, the event is still visible.  When I view it with `--details all` there's no indication that I've tried to remove it.  

I'd love it if gcalcli would honor that setting to hide an event.  If it just showed up as another detail, that'd be cool too.

**Comment by tresni** [comment]
I can't seem to replicate this.  If I "Remove" the event it doesn't show up for me in agenda or cal views.  Are you responding to the invite with Yes/No/Maybe first or just hitting remove?

**Comment by sagotsky** [comment]
Just remove.  I'll try declining as well.

**Comment by sagotsky** [comment]
I got more invitations.  Decline, then remove has no effect - I still see the item in gcalcli.  I'm on 3.2-dev.

**Comment by tresni** [comment]
Okay, I'll take another look, but so far I've been unable to duplicate this behavior..  You are receiving these invites from other calendars (ie not something associated with your Google account that is being used by gcalcli?)

**Comment by sagotsky** [comment]
As of today those items are gone.  Weird.  I apologize for the wild goose chase.
