### ISSUE TITLE
[request] Assign calendar color by choice instead of by ownership, read, write

### ISSUE THREAD

**Issue by itstallchris** [insanum/gcalcli#176]
New to github not sure if this is how this works.

I feel that ownership read write isn't worth displaying through color, since it's a detail you probably already know or could learn once through using 'gcalcli list'.

In its place custom calendar color assignment to a calendar would rock, especially while using conky. They could all default to a color unless you flag the calendar for a certain color.

Even better would be to somehow match Google calendar's color assignment to each calendar.

**Comment by tresni** [comment]
You can do this today.  It doesn't show up in the lastest help output, but the functionality hasn't been removed:

`gcalcli calw --calendar mine#red --calendar yours#blue`

Colors are defined at https://github.com/insanum/gcalcli/blob/master/gcalcli#L2030.  Those color names are mapped to the appropriate output colors so both conky and the terminal should get appropriate output.
