### ISSUE TITLE
Feature request: limit delete to timeframe

### ISSUE THREAD

**Issue by 0-wiz-0** [insanum/gcalcli#179]
When syncing an external calendar to a google calendar by using the import functionality, I have to replace the existing events. Since matching them up isn't easy (see https://github.com/insanum/gcalcli/issues/47), I'd like to remove all events e.g. for February before I import the new ones. Can you please add "--from" and "--to" or similarly to the delete command?

**Comment by tresni** [comment]
Yeah, I actually did this on a local branch for many of the reasons you indicated.  Deleting events that matched stuff 3 years ago...  Anyway, I now get to re-do it per #165 but that's the one it goes some times...

**Comment by tresni** [comment]
#189 Is a patch to deal with this, but changes delete behavior overall to default to only deleting things in a 30 day window.
