### ISSUE TITLE
Agenda for the next N days in general?

### ISSUE THREAD

**Issue by mathomp4** [insanum/gcalcli#180]
All,

Maybe this isn't doable, but I was wondering if it is possible to get "calw <weeks>" functionality with "agenda"? I ask because I'm currently using "agenda --detail_description" with a conky on my desktop. However, often times a full description means that I can get maybe 2 days on my screen (long descriptions!). So, I'd love to say "agenda next2days" or the like to just display the next 2 days.

At present, I'm using: 
```
gcalcli agenda 7am `date --date="tomorrow 7pm" +%Y-%m-%dT%R`
```
which works, but it seems like there should be a nicer way to do that and maybe I'm just not smart enough to figure it out.

Thanks,
Matt

**Comment by tresni** [comment]
You could do that by install parsedatetime:
``` sh
$ pip install parsedatetime
$ gcalcli agenda 7am "tomorrow 7pm"
```

Not sure if that's what you mean by "a nicer way" but...

**Comment by mathomp4** [comment]
Huh. Never heard of that package. I'll try it out tomorrow!

**Comment by tresni** [comment]
Did this resolve the issue for you or were you looking for something else?

**Comment by mathomp4** [comment]
It did. Thank you! Closing.
