### ISSUE TITLE
[discussion] Could gcalcli be used to synchronise local and google calendars?

### ISSUE THREAD

**Issue by guiniol** [insanum/gcalcli#184]
Hello,

While looking for a solution to sync gcal with a local calendar, I came accross gcalcli. This seems to be the only cli application able to push/pull to/from gcal, but sadly it doesn't have a synchronise mode (I'll be more than happy to be proved wrong).
My question is this: what amount of work would be necessary to create a sync mode? This is not a request for people to do it, this is me wondering if I would have time to do it.
The problem I foresee with the two-way sync is knowing which events are already on the side we're pushing to and if they have been modified on the side we are pulling from: we don't want to duplicate events. Also, it needs to properly handle events modified on both sides.

Cheers,

-- 
Guillaume

**Comment by tresni** [comment]
My initial impression is that it would be non-trivial.  gcalcli doesn't speak calendar really, mostly it just speaks Google API.  So you'd have to build something that reads your local calendar and then synchronizes it with your Google Calendar.  I feel like most calendar apps have that built in today.

On top of that you do have the issue you mentioned of knowing which events have been modified and too what, as well as determining which calendar is "right" (unless you only go 1 way.)  @insanum has/had been doing some work around being able to push event ids to google so we could do basic updates from an ical event, but that is not in place at this time.

Not saying it's impossible, but I definitely thing it would be a big project.

**Comment by guiniol** [comment]
Alright. Thanks for the assessment. I guess I'll wait and see if @insanum does something with the events ID, and then we'll see if I'll do something ^^

**Comment by insanum** [comment]
I wouldn't call it a full on sync mode but I did add support for event IDs when importing events ics/vcal files. @tresni is right about gcalcli not really speaking "calendar". It's just a wrapper around the google calendar APIs. Call it a window to your calendar.

FWIW I'm now using gcalcli solely for syncing incoming Microsoft Exchange events at work. It's a manual process though. I use mutt and wrote a script that can take a calendar attachment, pipe it to gcalcli, which then updates my google calendar. That's easy. The harder part is the event ID tracking. With the event ID support I cooked up I'm now able to handle Microsoft Exchange messages that create/modify/cancel events. Works perfectly for single non-recurring events. Current problem I have is when someone cancels or modifies a single event from a recurrence. At first glance I didn't see a way to modify a single event with the APIs but I didn't dig deep enough. It has to be there...

My event ID stuff hasn't been pushed yet for testing. Thanks for the reminder. I gotta do that now... :-)

**Comment by guiniol** [comment]
@insanum I'm really interested in your script to handle calendar attachments in mutt. I use supmua myself, but this is exactly what brought me down the rabbit hole. Also, calcurse seems to be able to use .ics files directly, so maybe I can cook up something. If the server handles events with the same ID properly (as in update the event) then it shouldn't be too hard: once you finish editing an event locally, gcalcli uploads it and lets gcal do all the hard work. You just need to be careful when you pull from gcal that you have pushed all the local changes first. Maybe.

**Comment by insanum** [comment]
Nothing that special about it. Under mutt I view the multipart attachments for a message, select the text/calendar attachment, then hit the macro ',c' which i've defined as:
```
macro attach ,c "<pipe-entry>gcalcli --reminder=10 --detail_url=short --calendar='Work' import\n"
```
Boom, invite is created/modified/cancelled on my google calendar.

I use the following mailcap entry for viewing invites:
```
text/calendar; gcalcli import -d; copiousoutput
```

**Comment by guiniol** [comment]
@insanum thanks. I'll see what I can do.

**Comment by guiniol** [comment]
@insanum this works for me

I just realised gcalcli can't just download a whole calendar as an ics file... (or maybe I'm blind, it happens)

**Comment by insanum** [comment]
Pushed a branch the contains my preliminary event uid tracking: 928a9dfdcfdc7eb73c379ba15f9185ff03ef7888

Needs lots of testing! As I mentioned above it mostly works great. Problems occur when you try to modify a single event that is part of a recurrence.

**Comment by insanum** [comment]
Moving discussion to #47 as that enhancement is more inline with what I've implemented. I doubt gcalcli would ever become a full blown sync tool. It's more of a swiss army knife. :-)
