### ISSUE TITLE
Python 3

### ISSUE THREAD

**Issue by nicklasb** [insanum/gcalcli#186]
Hi,

I am wondering if there are any plans to support Python 3 sometime in the near future?
Posting this question also a little bit since no one seem to have asked before, which seems uncommon.

**Comment by nicklasb** [comment]
Oh, sorry. I just saw that google-api-python-client has been *insanely* late in supporting Python 3. 

Weird as *hell* by a company like google. Rather,they should be on the forefront of a language on which they build so many of their stuff instead of holding it back like this : https://github.com/google/google-api-python-client/issues/3

Anyway, they seem to be supporting Py3 as of a week ago, or something.

**Comment by tresni** [comment]
Haven't looked into this much (partly for the reason you noticed, partly cause I don't do any python3 specific stuff at the moment.)  Likely possible now, but need to explorer further.

**Comment by nicklasb** [comment]
Ok. I saw that python3-gflags is available and the other dependencies also are satisified.
But as it is a command line utility, perhaps the interactions with aren't through imports, so perhaps it doesn't matter that much.

**Comment by tresni** [comment]
gflags actually looks like it may need to be complete removed (ala #165) to be able to support Python3, not that that's a bad thing, but just more work to be done ;-)

**Comment by tresni** [comment]
Good news, gflags is being removed in favor of argparse, that *should* make Python3 support simpler.  Still a lot more testing to do, but just figured I'd note that here.

**Comment by nicklasb** [comment]
Good stuff.

**Comment by DancingQuanta** [comment]
How is python 3 support coming along? Is there a branch to test?

**Comment by tresni** [comment]
No major focus on python3.  The argparse_over_gflags branch work would be required to even start that as current dependancies do not support Python3.  Limited time on my end and a shift of calendaring to Exchange at work means I don't use this as much as I used to.  @insanum is in a similar situation last I heard.

**Comment by tresni** [comment]
58f9cc41758ab3da68736c955f81ffd25b98af71...c31f2c251565f5603068ee120abda47d1a9777dc are all fairly minor changes to get us towards python3 support.  c31f2c...5ceef77 are the rest of them.

Google's Python Client library already relied on six so just used that.
