### ISSUE TITLE
Add repeated event

### ISSUE THREAD

**Issue by jackjackk** [insanum/gcalcli#187]
Is there a more proper way to add a repeated event rather than bash looping?
Thanks

**Comment by insanum** [comment]
Use the quick add feature of Google Calendar. gcalcli passes the string "as is" to Google's server for processing.
https://support.google.com/calendar/answer/36604

**Comment by jackjackk** [comment]
This is awesome! Thanks again.
Is there also a convenient way to delete recurring events?

**Comment by tresni** [comment]
Not at this time, see #157 .

**Comment by burningTyger** [comment]
The link doesn't tell anymore. So what's the magic spell that's passed to Google?

**Comment by KhalfaniWadlington** [comment]
Luckily someone archived that website in 2013 on archive.org

http://web.archive.org/web/20130405061614/https://support.google.com/calendar/answer/36604#


Here is what it said about recurring events.



When creating recurring events, the time expression has three parts: the start, the repetition, and the end.

- Example: [Gardening Monday at 10 am repeats weekly for 8 weeks].

The start is 'Monday at 10 am,' the repetition rule is 'repeats weekly,' and the end is given by '8 weeks.' Quick Add understands many kinds of repetition rules covering daily, weekly, monthly, and yearly repetitions. Examples are given below. We also encourage you to try various texts to explore this feature further.

To create a weekly recurring event:

-    Enter [Meeting at work every Monday at 2pm]
-    Enter [Tennis practice Tuesday 7pm to 9pm weekly]

 

To create a monthly recurring event:

-    Enter [Dinner at Mom's on the first Tuesday of every month]
-    Enter [Manicure on 9/1 every month]

To create a yearly recurring event:

-    Enter [Mom's birthday June 19 yearly]
-    Enter [Wedding anniversary July 3 yearly]

 

To create an event that repeats a certain number of times:

  -  Enter [Baseball Game every Thursday for 10 weeks]
  -  Enter [Language Class every Wednesday 7-8pm for 5 months]

 
When entering recurring events, don't enter a location in the middle of a time expression. For example, don't enter [dance practice every Tuesday in the gym at 8pm]. This event should be entered [dance practice at the gym every Tuesday 8pm].

*Also, if you do not specify an end date, duration, or number of times the recurring event occurs, it will repeat for 365 times, which is the maximum number of instances currently allowed for a recurring event.
