### ISSUE TITLE
Delete with start/end support

### ISSUE THREAD

**Issue by cyphunk** [insanum/gcalcli#189]
This patch allows for support of start and end times for delete searchs:

https://gist.github.com/cyphunk/7e9257e6d81ce3fc230d

Examples:

* ``gcalcli delete "search string" --calendar "my calendar" 2014-05-18 "30 days" --iamaexpert``

I chose not to create a fork to submit this because I do not work actively with this tool. And I understand this may mean no one cares to integrate this feature. But here it is if someone searches for it.

**Comment by tresni** [comment]
My only concern with this is the change of the default behavior.  Can you make the default `None` for start/end to maintain how it's been working?  Also, can you open this as a pull request vs a patch?  Thanks!
