### ISSUE TITLE
Adding to a calendar when having multiple --calendar specified in .gcalclirc

### ISSUE THREAD

**Issue by steinerhippo** [insanum/gcalcli#190]
Hey,

I have multiple calendars specified with --calendar in my .gcalclirc file (because I don't want all of my calendars to show up).

The problem with this is that it doesn't let me add something to a calendar because it apparently always attaches the multiple --calendar options to every command. I then complains 'Must specify a single calendar'.

Is there any other option to only show specified calendars while being able to add something to a calendar by specifying --calendar 'xyz' in the add command?

Best regards

**Comment by tresni** [comment]
If you are using 3.2 or later use `--defaultCalendar` in your .gcalclirc and `--calendar` on the command line.  `--defaultCalendar` is only used if you don't specify `--calendar`.  You can specify `--defaultCalendar` multiple times.

cf9cdf5fce2ea6703e83d3282200d9e2f6be15eb was the change.

**Comment by z0xyz** [comment]
I faced this issue when attempting to use it with the `quick` subcommand . I listed the available calendars at my connected google account , then assigned of one of them -which is typically the google account email itself- as the default calendar at the `~/.gcalclirc` configuration file , but with the new syntax i.e. `--default-calendar`
