### ISSUE TITLE
Offline - Should use cache

### ISSUE THREAD

**Issue by stevesbrain** [insanum/gcalcli#193]
Hi there. When offline, I put forth that gcalcli should use the cache, rather than erroring out. Alternatively, at the very least, I would recommend catching the error and spitting back an error message, rather than a dump :)

**Comment by tresni** [comment]
#48 has been open a while to address this.  There is no cache today, everything is queried live.  Better error handling would probably be a good thing.

**Comment by tresni** [comment]
Better error messaging is actually already one the list (#88).
