### ISSUE TITLE
Crash on start (ValueError: unknown locale: UTF-8)

### ISSUE THREAD

**Issue by SebastianKeller** [insanum/gcalcli#195]
Hey, really cool tool!

Sadly, it crashes right at the beginning for me.

Mac OS X: Yosemite 10.10.2
Python: 2.7.10

Traceback:

```
Traceback (most recent call last):
  File "/usr/local/bin/gcalcli", line 2555, in <module>
    BowChickaWowWow()
  File "/usr/local/bin/gcalcli", line 2406, in BowChickaWowWow
    gcal.AgendaQuery()
  File "/usr/local/bin/gcalcli", line 1670, in AgendaQuery
    self._IterateEvents(start, eventList, yearDate=False)
  File "/usr/local/bin/gcalcli", line 1518, in _IterateEvents
    self._PrintEvent(event, prefix)
  File "/usr/local/bin/gcalcli", line 1228, in _PrintEvent
    (tmpTimeStr, self._ValidTitle(event).strip()))
  File "/usr/local/bin/gcalcli", line 415, in PrintMsg
    msg = stringFromUnicode(msg)
  File "/usr/local/bin/gcalcli", line 228, in stringFromUnicode
    return string.encode(locale.getlocale()[1] or
  File "/usr/local/Cellar/python/2.7.10/Frameworks/Python.framework/Versions/2.7/lib/python2.7/locale.py", line 562, in getlocale
    return _parse_localename(localename)
  File "/usr/local/Cellar/python/2.7.10/Frameworks/Python.framework/Versions/2.7/lib/python2.7/locale.py", line 475, in _parse_localename
    raise ValueError, 'unknown locale: %s' % localename
ValueError: unknown locale: UTF-8
```

+1 for `BowChickaWowWow()` :)

Regards,
Sebastian

**Comment by SebastianKeller** [comment]
I just discovered that calling ```gcalcli agenda --locale de_DE``` works just fine.

**Comment by tresni** [comment]
interesting... Never seen UTF-8 fail before, first for everything ;-)  I'll try to see if I can replicate this.  Where did you install python from (or is it system default?)

**Comment by SebastianKeller** [comment]
Glad I brought you something new :)

That python version was installed via [homebrew](http://brew.sh)

**Comment by tresni** [comment]
Out of curiosity, when you installed OSX did you do it with German language settings?  Trying to find a way to replicate this so I can figure out why it's not picking up your locale and defaulting to UTF-8.

**Comment by louwers** [comment]
I have exactly the same error. Setting German locale also works for me, so does Dutch locale.

**Comment by uzzer** [comment]
Same issue on OSX.

I have tried to set default locale in `.gcalclirc` and it does not help. What could be wrong?

**Comment by eyaleizenberg** [comment]
@tresni Just installed v4a2 and getting this:

```bash
gcalcli agenda

Tue Feb 13Traceback (most recent call last):
  File "/usr/local/bin/gcalcli", line 2493, in <module>
    BowChickaWowWow()
  File "/usr/local/bin/gcalcli", line 2391, in BowChickaWowWow
    gcal.AgendaQuery(startText=FLAGS.start, endText=FLAGS.end)
  File "/usr/local/bin/gcalcli", line 1691, in AgendaQuery
    self._DisplayQueriedEvents(start, end)
  File "/usr/local/bin/gcalcli", line 1656, in _DisplayQueriedEvents
    self._IterateEvents(start, eventList, yearDate=yearDate)
  File "/usr/local/bin/gcalcli", line 1522, in _IterateEvents
    self._PrintEvent(event, prefix)
  File "/usr/local/bin/gcalcli", line 1211, in _PrintEvent
    PrintMsg(eventColor, fmt % (_u(tmpTimeStr), _u(self._ValidTitle(event).strip())))
  File "/usr/local/bin/gcalcli", line 219, in _u
    encoding = locale.getlocale()[1] or locale.getpreferredencoding(False) or "UTF-8"
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/locale.py", line 562, in getlocale
    return _parse_localename(localename)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/locale.py", line 475, in _parse_localename
    raise ValueError, 'unknown locale: %s' % localename
ValueError: unknown locale: UTF-8
```

Trying to run this as recommended got me the following:
```bash
gcalcli agenda --locale en_US
The following options are either no longer valid globally or just plain invalid:
  --locale
```

**Comment by krupenja** [comment]
Had the same issue on macOS. Workaround is to use `gcalcli --locale=en_US agenda`, note that `--locale` should come before `agenda`.

**Comment by jcrowgey** [comment]
@eyaleizenberg @krupenja 

Can either (both?) of you verify that this is still and issue when running from the current master branch in this repo?  If so, I'd like to fix it before I release.

UTF-8 isn't a locale, it's an encoding.   Can you also post output of the `locale` command?

**Comment by krupenja** [comment]
@jcrowgey

1. The output of `locale` was:

```
ANG=
LC_COLLATE="C"
LC_CTYPE="UTF-8"
LC_MESSAGES="C"
LC_MONETARY="C"
LC_NUMERIC="C"
LC_TIME="C"
LC_ALL=
```

Hmmm, so it seems that I did not have a locale set. Not sure how that happened.

2. After running `export LANG=en_US.UTF-8`, the output of `locale` was:

```
LANG="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_CTYPE="UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_ALL=
```

And gcalcli was still crashing if ran without `--locale` argument.

3. So then I exported `export LC_CTYPE=en_US.UTF-8` directly and gcalcli started working fine even if run without `--locale`.

Does this help or you still want me to try building and running from master branch?

**Comment by krupenja** [comment]
Initially missing locale on my system is perhaps related to a bug in oh-my-zsh: https://github.com/robbyrussell/oh-my-zsh/issues/7558

**Comment by jcrowgey** [comment]
@krupenja That does help! 

Can you confirm for me that it was "ANG" and not "LANG" (not sure if it was an issue in your shell or just a typo in the report :)). 

I need to do a little research to understand proper POSIX behavior in this context.

**Comment by krupenja** [comment]
@jcrowgey No, that was a typo and it was indeed `LANG` so the correct output of `locale` at step 1 is:

```
LANG=
LC_COLLATE="C"
LC_CTYPE="UTF-8"
LC_MESSAGES="C"
LC_MONETARY="C"
LC_NUMERIC="C"
LC_TIME="C"
LC_ALL=
```

**Comment by jcrowgey** [comment]
@krupenja thank you.  I may not be able to address this right away, but these notes will come in handy when I have a change to investigate the right behavior here.  If possible, I'd still love to confirm concretely that this is broken for you on git master (I believe it will be).

**Comment by krupenja** [comment]
@jcrowgey Sure, I will try to have a look at whether it reproduces on git master in the next couple of days.

**Comment by jcrowgey** [comment]
So, I think this is the question I want to get to the bottom of:

I'm used to seeing locale values of the form:

COUNTRY_LANG.ENCODING

While I've seen locales without the ".ENCODING" part, this is the first time I've seen one with only the ENCODING part.  On the other hand, I'm aware of the "C" locale so I know ther are special cases.  I don't really know if this is a special case that I need to handle or if I can simply say that your shell has done something wrong here.  Note that even in the latter case, we can make gcalcli fail more gracefully.

Potentially useful:

http://pubs.opengroup.org/onlinepubs/007908799/xbd/envvar.html

**Comment by krupenja** [comment]
@jcrowgey Just want to confirm that this is still a problem with girt master if `export LC_CTYPE=en_US.UTF-8` is not set, just like you expected.
