### ISSUE TITLE
API limits exceeded

### ISSUE THREAD

**Issue by LinuxMercedes** [insanum/gcalcli#197]
Looks like you guys made it onto Hacker News and ran out of API requests. 

Providing my own client id/secret works.

**Comment by tresni** [comment]
I've put in a request for additional API capacity.  Normally this turns around in less then a day.  For now, using your own client id/secret will solve it.  Luckily this is supported through command line interface and config file.

**Comment by tresni** [comment]
Request has been granted, but we are already pushing the new limit.  Going to watch it for a couple days and see what happens.

**Comment by cybermails** [comment]
I'm trying to follow directions to use my own client id and secret from this website, http://choorucode.com/2013/11/19/how-to-use-gcalcli-with-your-own-client-id-and-secret/

However, I am unable to modify Authorized Redirect URI as mentioned in the 4th point there:
"4. gcalcli uses a localhost URI for its authentication. We need to add this to our API settings. To do this, click Edit Settings and in the Authorized Redirect URIs textbox add http://localhost:8080/ and click Update."

How can I create and use my own client id and secret?

**Comment by LinuxMercedes** [comment]
Those directions are really old. Here's what I did:

- Go to the [Google developer console](https://console.developers.google.com/)
- Make a new project for gcalcli
- On the sidebar under `APIs & Auth`, click `APIs`
- Enable the `Calendar API` (you'll probably have to search for it)
- Now, on the sidebar, click `Credentials`
- Create a new Client ID. Set the type to `Installed Application` and the subtype to `Other`
- It'll probably want you to set up a consent screen thing. What you put here isn't too important; it's just what will show up when gcalcli opens up the OAuth website. (Note: you may have to do this step in Chrome; Firefox didn't want to load the page for me.)
- Go back to the credentials page and grab your ID and Secret!

**Comment by hshan** [comment]
Thanks for this!

<< FROM
> Those directions are really old. Here's what I did:


>  * Go to the Google developer console[1]
>  * Make a new project for gcalcli
>  * On the sidebar under APIs & Auth, click APIs
>  * Enable the Calendar API (you'll probably have to search for it)
>  * Now, on the sidebar, click Credentials
>  * Create a new Client ID. Set the type to Installed Application and
>    the subtype to Other
>  * It'll probably want you to set up a consent screen thing. What you
>    put here isn't too important; it's just what will show up when
>    gcalcli opens up the OAuth website. (Note: you may have to do this
>    step in Chrome; Firefox didn't want to load the page for me.)
>  * Go back to the credentials page and grab your ID and Secret! —
>    Reply to this email directly or view it on GitHub[2].


>



Links:

  1. https://console.developers.google.com/
  2. https://github.com/insanum/gcalcli/issues/197#issuecomment-118398319

**Comment by tresni** [comment]
I've put in another request as we are hitting the limits (again.)

**Comment by cybermails** [comment]
Thanks LinuxMercedes. I followed your instructions and successfully created my own client ID and secret for using Google Calendar with gcalcli. I then also created ~/.gcalclirc and entered in it in the following format;

--client_id='xxxxxxxxxxlongIDxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.com'
--client_secret='xxxxxxxxsecretxxxxxxxxxxx'
 
However, even after using my own client ID and secret I still get API limits error sometimes. As I am writing this it just started working again.

**Comment by LinuxMercedes** [comment]
I don't use ~/.gcalcli, but you might need to remove the '--' from the front of your variable names. 

We should probably find a better place to answer these questions...

**Comment by tresni** [comment]
No quotes in the gcalclirc file.   Dashes are required.

> I don't use ~/.gcalcli, but you might need to remove the '--' from the
> front of your variable names.
>
> We should probably find a better place to answer these questions...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/insanum/gcalcli/issues/197#issuecomment-119434091>.
>


-- 
-- Brian
Sent from Gmail Mobile

**Comment by cybermails** [comment]
I removed the quotes and kept the dashes and I still get the Daily limit exceeded error. Here's what I get in the terminal.
---------------------------------------
$ gcalcli agenda
Traceback (most recent call last):
  File "/usr/bin/gcalcli", line 2555, in <module>
    BowChickaWowWow()
  File "/usr/bin/gcalcli", line 2406, in BowChickaWowWow
    gcal.AgendaQuery()
  File "/usr/bin/gcalcli", line 1665, in AgendaQuery
    eventList = self._SearchForCalEvents(start, end, None)
  File "/usr/bin/gcalcli", line 1590, in _SearchForCalEvents
    events = self._RetryWithBackoff(work)
  File "/usr/bin/gcalcli", line 644, in _RetryWithBackoff
    return method.execute()
  File "/usr/lib/python2.7/site-packages/oauth2client/util.py", line 137, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/googleapiclient/http.py", line 729, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 403 when requesting https://www.googleapis.com/calendar/v3/calendars/txstategeography%40gmail.com/events?timeMax=2015-07-13T00%3A00%3A00-05%3A00&alt=json&singleEvents=true&timeMin=2015-07-08T00%3A00%3A00-05%3A00 returned "Daily Limit Exceeded">

**Comment by tresni** [comment]
Alright, got the limit bumped again.  We'll see how long it lasts this time ;-)

**Comment by tresni** [comment]
Looks like the new limit will hold us for a little while (first day we only used ~40% of the new limit.)  We'll keep on eye on this to see how it goes moving forward.

**Comment by LinuxMercedes** [comment]
Thanks!

**Comment by mhoran** [comment]
I received a 500 error via cron (`gcalcli remind`) this morning and confirmed via manual request that the API limit had been reached again. I tried to follow the instructions above for generating an API key but it seems they've changed, again.

Here's what I did:

1. Go to the [Google developer console](https://console.developers.google.com/)
1. Make a new project for gcalcli
1. On the sidebar under APIs & Auth, click APIs
1. Click on Calendar API under the Google Apps APIs heading and enable it.
1. Now, on the sidebar, click Credentials
1. Click the Add credentials dropdown and choose OAuth 2.0 client ID
1. Click Configure consent screen
1. Fill in Product name with gcalcli
1. Click save
1. Set the Application type to Other
1. Copy your OAuth client client ID and client secret from the resulting modal.
