### ISSUE TITLE
ERROR: Missing module - cannot import name run

### ISSUE THREAD

**Issue by leftoverBits** [insanum/gcalcli#204]
I'm pretty new to the concept of using someone else's python module, so apologies in advance if this issue is my fault.

When I run gcalcli in terminal (with or without args), I get the message ERROR: Missing module - cannot import name run. I can't trace the source of this error, so I'm not sure what's going on. 

I believe I'm up-to-date with all prereqs:
Python (2.7.6)
gcalcli (3.3)
google-api-python-client (1.4.1)
python-dateutil (2.4.2)
python-gflags (2.0)

Any advice would be appreciated...

**Comment by nmpx** [comment]
I'm experiencing this problem too.

**Comment by tresni** [comment]
Sounds like this is an issue with newer versions of google-api-python-client in which `run` was deprecated.  I am pushing an update now that should resolve this.  I'm testing with google-api-python-client 1.4 now (and 1.5 later).  I'll post an update as soon as I do.

**Comment by tresni** [comment]
Looks like some people are finding #123 which was (slightly different) but a similar error message.  Cross linking to (hopefully) get people to see this.

Quick fix is to downgrade oauth2client to 1.4.9
`pip install oauth2client==1.4.9`

Simply changing over to run_flow with gflags doesn't appear to work.  I'm trying a couple different things, but it may be time to kill gflags.

**Comment by tresni** [comment]
For now, keep oauth2client<=1.4.9.  Looks like it is time to kill gflags and move us (back) to argparse.

**Comment by kadomcevi** [comment]
All modern distros upgraded to oauth2client-1.5.2 and  2.0.1
Can you fix this issue for new oauth2client?


Right now gcalcli-3.3.2 fail with error
ERROR: Missing module - cannot import name run

**Comment by carlospgmat03** [comment]
In my distro, I only have modern oauthclient. Stuck here...

**Comment by tresni** [comment]
Try the alpha tags: https://github.com/insanum/gcalcli/tree/v4.0.0a3
