### ISSUE TITLE
404 on gcalcli agenda

### ISSUE THREAD

**Issue by blawiz** [insanum/gcalcli#205]
'gcalcli agenda' gives this error: 

```
Traceback (most recent call last):
  File "/usr/local/bin/gcalcli", line 2580, in <module>
    BowChickaWowWow()
  File "/usr/local/bin/gcalcli", line 2431, in BowChickaWowWow
    gcal.AgendaQuery()
  File "/usr/local/bin/gcalcli", line 1683, in AgendaQuery
    eventList = self._SearchForCalEvents(start, end, None)
  File "/usr/local/bin/gcalcli", line 1605, in _SearchForCalEvents
    events = self._RetryWithBackoff(work)
  File "/usr/local/bin/gcalcli", line 646, in _RetryWithBackoff
    return method.execute()
  File "/usr/local/lib/python2.7/dist-packages/oauth2client/util.py", line 132, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/googleapiclient/http.py", line 723, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 404 when requesting https://www.googleapis.com/calendar/v3/calendars/dtbhc6ieoghn242trkko9v7oh8%40group.calendar.google.com/events?timeMax=2015-09-13T00%3A00%3A00%2B02%3A00&alt=json&singleEvents=true&timeMin=2015-09-08T00%3A00%3A00%2B02%3A00 returned "Not Found">
```

When i go to the above mentioned url in my browser i get:

```
{
 "error": {
  "errors": [
   {
    "domain": "usageLimits",
    "reason": "dailyLimitExceededUnreg",
    "message": "Daily Limit for Unauthenticated Use Exceeded. Continued use requires signup.",
    "extendedHelp": "https://code.google.com/apis/console"
   }
  ],
  "code": 403,
  "message": "Daily Limit for Unauthenticated Use Exceeded. Continued use requires signup."
 }
}
```

Is this a limitation or a bug with gcalcli? i did do some heavy tasks like 'gcalcli agenda 20000101 20150901'.

I see the url went missing, sorry dont know this markdown stuff.

**Comment by tresni** [comment]
You are getting a 404 through the API which means it's trying to access something that doesn't exist.  But that URL is really not designed to be accessed via browsers which is why you get the 403 when you try to look it up directly (You aren't doing the proper authentication.)  Try doing `gcalcli --refresh --nocache agenda` to see if that resolves the 404 issue.  There are limits on individual users (as imposed by Google), but the backoff code should mean that while it would take forever, it should eventually succeed.  I would also recommend not trying to export you entire calendar like that ;-)  You are probably better off getting it via an export on the website.

(Also, fixed your post so now the URL shows up ;-)  Markdown treats &lt; and &gt; as special characters indicating you want to input HTML directly.)

**Comment by blawiz** [comment]
Thank you for a great answer tresnl, actually I triend the "use your own Calendar API" recipe from https://github.com/insanum/gcalcli and it fixed it, probably the same way your solution would have :)

Why shouldnt one download the whole calendar? I've been using it with scripts to automatically add/remove/list appointments (with the --tsv option and parsing). Sometimes it's nice to get the full calendar to be sure not to miss anything, for stats etc.

I think i found a bug btw. In a failed attempt to import a ics file in 2013, i added an entry almost 650 times! (The "Norwegian til Molde..." entry)

'gcalcli --military agenda 20130809 20130810'
---
		Fri Aug 09         VIZ Resultat 2. kvartal
	           11:00  Norwegian til Molde-Aaroe - 4SSI4G
	           11:00  Norwegian til Molde-Aaroe - 4SSI4G
                    ....
---

when trying to delete them, gcalcliseems to want to try to delete all my appointments, even outside the specified period, which ofc would be not so good if --iamaexpert was used: 

'gcalcli --military delete Norwegian 201308091100 201308091800'
---
2013-02-07         ATEA 4Q resultat
Delete? [N]o [y]es [q]uit: n

2013-02-07         ATEA Resultat 4. kvartal
Delete? [N]o [y]es [q]uit: n
---

I can make this a new issue if requested.

**Comment by tresni** [comment]
The big reason you wouldn't want to export your entire calendar repeatedly through the API is you'll eventually hit the limits.

Please open a separate issue for the delete behavior.

**Comment by kdvolder** [comment]
I was getting the same error and this:

           gcalcli --refresh --nocache agenda

Fixed it. So what is this problem? An expired oauth token gcalcli has stashed somewhere?If that's what it is, then, shouldn't gcalcli be smart enough to refresh the token itself once in a while?

**Comment by tresni** [comment]
gcalcli does refresh the token automatically and `--nocache` has nothing to do with the token itself.  `--nocache` just means we don't rely on the cached calendar data (just a list of what calendars you have access to, their IDs, etc.)  If something has changed (ie you deleted and re-created a calendar with the same name) then that data may be invalid.  The cache keeps us from needing to re-request a list of calendars on every operation, but it should likely be expired out at some point (Right now you have to use `--nocache` to clean it out when you need to.)

**Comment by kdvolder** [comment]
Okay thanks for the clarification. BTW: gcalcli is working pretty well for me. Thanks for building it.
