### ISSUE TITLE
Export to ics

### ISSUE THREAD

**Issue by droidzone** [insanum/gcalcli#209]
Seeing that Outlook 2016 doesnt support Google Calendar syncing, I was hoping that I could use this script in a cron job to export Google Calendar to ics. Can this script support exporting to ics?

**Comment by insanum** [comment]
No gcalcli does not support ics/vcal export. If you're tied to Outlook (note that I am tied to it also at work) then there are much better options. I've used Google Calendar Sync with pretty good success.
http://pppindia.com/calendar-sync/index.html

**Comment by insanum** [comment]
Another option. I came across the exchange-sync project the other day and it works beautifully. It's awesome as you can run it on Linux as a cronjob.
https://github.com/gdenning/exchange-sync

**Comment by insanum** [comment]
I'm closing this issue as it's outside the scope of gcalcli and there are other solutions.

**Comment by rrthomas** [comment]
Looking for a solution to this problem as my web-scraping script from years ago no longer works, I cannot actually currently find another solution. I just want to be able to generate an iCal file. So, if you're aware of any other solutions, I'd love to hear 'em! I have been searching for hours. The only program I found that advertises the right sort of capability is vdirsyncer, but that I couldn't get to work with my main calendar.
