### ISSUE TITLE
quick option strips leading non-alphanumeric characters

### ISSUE THREAD

**Issue by atsepkov** [insanum/gcalcli#210]
Try any of the following:

    gcalcli quick "[TAG] event"
    gcalcli quick "<TAG> event"
    gcalcli quick "<<TAG>> event"

In 3 all cases, everything until the first T will be stripped from the entry, resuling in something like `TAG>> event`. Special characters in the middle of the string are not a problem.

EDIT: regular `gcalcli add` does not seem to be affected by this.

**Comment by tresni** [comment]
Unfortunately this seems to have the same answer as #214 .  We are passing the full string to Google, but they are chopping off the non-alpha characters at the start of the string.  Not seeing any reasoning for this in the [quickAdd](https://developers.google.com/google-apps/calendar/v3/reference/events/quickAdd) documentation.  Tried a couple of things to see if I could circumvent the behavior, no dice so far.
