### ISSUE TITLE
Search doesn't seem to work

### ISSUE THREAD

**Issue by TT44bb** [insanum/gcalcli#212]
So I'm trying to write a search query which matches all events related to a guy called "Kowalski" with:
./gcalcli search "Kowalski"
But this matches all kinds of events, for example one which contains only the title "Physik Zwischenprüfung", no description, nothing.
Even when I enter the exact title of one of the events I'm searching and add extra quotes in the hope they'll somehow trigger exact matching:
./gcalcli search "'Lineare Algebra I (U) E. Kowalski'"
I still get all kinds of stuff including the physics exam which includes no single word from the search query.
So either I completely misunderstand this so called "search" function, or it's broken.

Edit: Oh, and I'm using the latest version from git as of writing.

**Comment by tresni** [comment]
`search` is powered by Google, not gcalcli directly.  We pass the string you supply to Google and parse the results.  Do you see the same behavior if you search for "Kowalski" in Google Calendar web UI?

**Comment by TT44bb** [comment]
I can't seem to properly search using the web UI at all, it always tells me there are 200 results, but displays only a couple within the near future.
But using the function to search only for events on a specific day I got this:
2 results for LE Nr. 401-1261-07L when: 17/12/2015 - 17/12/2015 on All Calendars
(which is correct, two events on that day contain that number)
When I do
./gcalcli search 'LE Nr.  401-1261-07L'
I get the following events in the list of results:
2015-12-17   8:15am  Analysis I (V) H. Knörrer
2015-12-17   8:15am  Analysis I (V) H. Knörrer
2015-12-17   7:00pm  MTY Musizierstunde
That is, it lists a third (unwanted, absurd, it doesn't contain the term or anything similar) result which the web ui doesn't list.

Strange.

**Comment by boomertsfx** [comment]
Same problem happens to me -- works fine on the web side.
