### ISSUE TITLE
quick option ignores time from timestamps like 2007-09-24T15:30

### ISSUE THREAD

**Issue by atsepkov** [insanum/gcalcli#214]
The time part of above timestamp gets added to the message text. The task itself gets assigned to correct date but gets no time associated with it.

**Comment by tresni** [comment]
`quick` gets no processing by gcalcli but directly calls the [quick add](https://developers.google.com/google-apps/calendar/v3/reference/events/quickAdd) API from Google.  We take the string you supply and send it off to Google.  All the processing on the string is done by Google.  It's the same as using the "Quick Add" button in Google Calendar.
