### ISSUE TITLE
Use event id in ical import to avoid duplicates

### ISSUE THREAD

**Issue by victorbrca** [insanum/gcalcli#216]
More of a question (possible enhancement). 

It there a way to use the existing ID in the ical file for the import so that events are not duplicated when being imported for the second time?

I have a job that exports Outlook events daily into an ical file. I would like to use gcalcli to import into Google Calendar, but it ends up duplicating the events if they already exists. 

If I import manually (via the UI) it works (I don't get any duplicates).

Thanks.

**Comment by insanum** [comment]
There is a branch (way outdated btw) that was the first cut at handling this import.
https://github.com/insanum/gcalcli/tree/track_import_event_ids

Also, not to steer you away from gcalcli, if you're just interested in a one-way sync from Outlook to Google Calendar then check out this project. It's great and does exactly that. For what it's worth I've been using it for a couple months.
https://github.com/gdenning/exchange-sync

**Comment by sje30** [comment]
I'd be interested in this.  I would be happy with a one-way sync from a local .ics file to Google Calendar.

**Comment by rmsppu** [comment]
You could do something like this:

```
	# extract the SUMMARY, DTSTART and DTEND fields to check
	# for duplicate entries before importing invite
	SUMMARY=`sed -n -e "s/^SUMMARY.*://p" $invitefile`
	DTSTART=`sed -n -e "s/^DTSTART.*://p" $invitefile | head -1`
	DTEND=`sed -n -e "s/^DTEND.*://p" $invitefile | head -1`

	if [[ -z "$SUMMARY" || -z "$DTSTART" || -z "$DTEND" ]] ; then
		echo "Invitation $invitefile missing required field (SUMMARY, DTSTART, DTEND)"
		exit 1
	fi

	gcalcli --calendar $CAL search "${SUMMARY}" $DTSTART $DTEND | grep -qw "${SUMMARY}"
	if [ $? = 0 ] ; then
		# found a match...the invite has already been imported...
		echo "Existing invitation for event \"${SUMMARY}\" from $folder found in calendar ${CAL}...not importing"
		exit 1
	fi

	gcalcli --calendar $CAL import $invitefile
```

**Comment by nikksno** [comment]
Hi. I've installed the track_import_event_ids branch on ubuntu 16.04 [not mentioned on the docs, for me it needed `pip install oauth2client==1.5.0`] but although it does not duplicate events upon repeated imports, it does not of course delete ones that have been deleted. Do you have any ideas regarding this functionality? Is there any plan to integrate the duplicate ID tracking in the main branch?  Why on earth would you *not* want to? ;] Thanks all!

**Comment by dbarnett** [comment]
I believe this and #583 are dupes? Should be fixed now using the "import" API instead of "insert".

Note there are still some rough edges like #730, but it should more-or-less do what you need it to now (in the repo + in the upcoming 4.5 release). LMK if not.
