### ISSUE TITLE
Gflags Error

### ISSUE THREAD

**Issue by BrokeTheUniverse** [insanum/gcalcli#217]
I get this error message: 

NotImplementedError: the gflags library must be installed to use tools.run().

And for the record, I have installed gflags. I used the Arch Linux user repositories, and when that didn't work I tried pip.

**Comment by polyzen** [comment]
@BrokeTheUniverse, read the comments here https://aur.archlinux.org/packages/gcalcli/

**Comment by polyzen** [comment]
@BrokeTheUniverse, make sure you have  `community/python2-gflags` installed, and try `aur/python2-oauth2client1412-2` which was just pushed

**Comment by tresni** [comment]
The setup.py has this pinned to the right version so I'm guessing you are installing a package vs using pip.  I would open a bug report against the package.  I have been working on a [new version](https://github.com/insanum/gcalcli/tree/argparse_over_gflags) that uses argparses, but I haven't decided to release it yet as it's not reverse compatible with everything today.

**Comment by polyzen** [comment]
Arch Linux doesn't support partial updates, but the issue should be resolved.
