### ISSUE TITLE
Command line arguments do not override the configuration file

### ISSUE THREAD

**Issue by geo909** [insanum/gcalcli#220]
Hi,

First off, thanks for the great piece of software, it is very very helpful. 

I have a little issue here. My configuration file looks as follows:
--mon=true
--military
--calendar=Calendar#cyan
--calendar=Birthdays#magenta
--calendar=Weekly#white
--calendar=Bills#brightblack
--width=15

If I try the following:
gcalcli --cal 'Calendar' quick 'buy milk tomorrow'
I get an 'Error: invalid event text'

However if I remove all the lines with "--calendar" from my configuration file, the above command works without problem. So my guess is that the command line arguments do not override the configuration file. 

I'm pretty sure I read somewhere in the documentation that this should not be the case. Is that the expected behaviour?

**Comment by tresni** [comment]
Use `--defaultCalendar` in your config file. `--calendar` is cumulative, so having them in your config means "use these plus anything I specify on the command line."  If you want "use these if I don't specify anything" then `--defaultCalendar` is the way to go.

**Comment by geo909** [comment]
Indeed, puting '--defaultCalendar' instead of '--calendar' in the config file and doing:
gcalcli --calendar 'Calendar' quick 'buy milk tomorrow'
did the job..

Many thanks
