### ISSUE TITLE
Tasks do not show up in gcalcli

### ISSUE THREAD

**Issue by geo909** [insanum/gcalcli#221]
Hi there,

I've been using gcalcli recently and everything works like a charm, except that the calendar corresponding to tasks does not show up.

In my gcalclirc I have included the following lines:
--defaultCalendar=Calendar#cyan
--defaultCalendar=Birthdays#magenta
--defaultCalendar=Weekly#white
--defaultCalendar=Bills#brightblack
--defaultCalendar=Tasks#white

If I do for example 'gcalcli calw' all the above calendars show up, except for tasks. 

Is that an expected behaviour? Is there any way to make tasks appear in the gcalcli output? That would be great.

Many thanks

**Comment by tresni** [comment]
I believe this is expected as Tasks (to my knowledge) are their own API: https://developers.google.com/apis-explorer/#p/tasks/v1/

**Comment by geo909** [comment]
Good to know, thanks.
