### ISSUE TITLE
gcalcli quick  yields error message 'must specify a single calendar'

### ISSUE THREAD

**Issue by robsc13** [insanum/gcalcli#223]
i see that this is an old message that has been closed. however i have one netbook on which gcalcli works correctly. but on my pc, running 64 bit Ubuntu 15.10, I keep getting the error. I've removed cache, uninstalled, reinstalled, don't know what to try next. i do know that i installed using git the first time, later i installed from software center, any help?

**Comment by tresni** [comment]
Check #220 and see if that reaolution solves it for you.

**Comment by robsc13** [comment]
thanks for your reply. sorry I'm not sure i understand by config file do you mean .config? if so, I don't have gcalcli in my .config    and i can't seem to find anything gcalcli related that looks like --calendar. perhaps you could be more specific for this 5 year newbie.

**Comment by robsc13** [comment]
thx for getting back, Brian... I'd like to try that fix but i'm confused as
to what you mean by my config file. I looked in .config and found nothing
that looks like gcalcli; i looked in gcalcli and saw nothing that looks
like a config file. i'm a sort of newbie after 5 years, could you be more
specific on what and where  is my config file?   thx

On Mon, Dec 28, 2015 at 10:07 AM, Brian Hartvigsen <notifications@github.com

**Comment by tresni** [comment]
So one of 3 things is happening.  Either you are not specifying a `--calendar` on the command line, your `--calendar` is matching either exactly 0 or multiple calendars, or you have one or more `--calendar` in you `~/.gcalclirc`.  What is the exact command you are using?  What are the contents of your `~/.gcalclirc`?

**Comment by robsc13** [comment]
i'm using command gcalcli quick ' 9am test '         . and as i recall the
last time this happeneded , the solution was to delete my gcalclirc file.
problem is, i can't find it. in my files, i have a gcalcli,  i have a
.gcalcli_cache, and a .gcalcli_oauth       there's probably some simple
linux fact that i'm unaware of, but for the life of me i cannot find
 /.gcalclirc      . btw when i do gcalcli list,    i see bob.eback@gmail.com
and then  in purple, reader   Holidays in the United States. and for more
information and perphpas what make s it more confsing, it i've installed
gcalcli hrice, once from the git repository, and once from the ubuntu
software center, once from synaptic. and even if i uninstall, i can still
read gcalcli agenda. thx for your help.

On Tue, Dec 29, 2015 at 11:20 AM, Brian Hartvigsen <notifications@github.com

**Comment by tresni** [comment]
Create a file called `~/.gcalclirc` in it put:
```txt
--defaultCalendar bob.eback@gmail.com
```

gcalcli requires that you specify a calendar, even if you only have one.  It isn't "smart" enough to figure out there is only one of them :)

**Comment by robsc13** [comment]
well i'mg etting closer, but now i get  'Unknown command line flag
'defaultCalendar bob.eback@gmail.com'


On Wed, Dec 30, 2015 at 11:02 PM, Brian Hartvigsen <notifications@github.com

**Comment by tresni** [comment]
```
--defaultCalendar=bob.eback@gmail.com
```

Forgot the `=` was required for flag files long options

**Comment by robsc13** [comment]
sorry, I've tried several variations with the same 'unknown command line
flag' message. and the very odd thing is that I have two other computers,
on which gcalcli work great. the only difference i can think of is this pc
is 64 bit, and i have a newer python 3.51 i think. also, i'm using the
google oauth module, when i adopted that i stopped having a gcalclirc file
at all. as i recall, the last time i had this issue.  at anyh rate, so far,
glas doesnt mind me having an empty rcalclirc file, but as soon as i put
any command in at all, it gets red lettered.
'bob@bob-3:~$ gcalcli agenda
Unknown command line flag ' defaultCalendar '

one last hope.... inside the ~/.gcalclirc, should the first line be inside
square brackets?

righ now its just

.gcalirc
      --defaultCalendar = bob.eback@gmail.com


thanks.

**Comment by tresni** [comment]
What version are you running?

**Comment by robsc13** [comment]
verdionb3.3.2 from pypi.python.org,installed from source via git clone

**Comment by robsc13** [comment]
Brian, thanks for your help. everything works now. i added the line  "
--defaultCalendar=bob.eback@gmail.com"  and made it the lone entry in my
gcalclirc folder. i just had to clean up my syntax a little.

**Comment by troylar** [comment]
For others landing on this thread with the same problem, don't use quotes on the `defaultCalendar` entry in the `~/.gcalcirc'.
