### ISSUE TITLE
URL calendar no name, events won't show up

### ISSUE THREAD

**Issue by tgy** [insanum/gcalcli#232]
I'm trying to set up a URL calendar on Google.

I have another one working fine but this one just doesn't work with `gcalcli`...

Here is how I added it on *calendar.google.com*

![deepinscreenshot20160210101908](https://cloud.githubusercontent.com/assets/694873/12943209/0b19ada0-cfe0-11e5-8283-83fae46a9b2f.png)

I named it 'epita':

![deepinscreenshot20160210102012](https://cloud.githubusercontent.com/assets/694873/12943208/0b16e732-cfe0-11e5-830a-99c32608aebd.png)

Here is what I get from `gcalcli`

```
λ gcalcli --nocache list
 Access  Title
 ------  -----
  owner  life
 reader  https://acu.epita.fr/chronos/calendars/CSI.ics
 reader  LRDE
 reader  Anniversaires
 reader  Jours fériés en France
 reader  Numéros de semaine
```

```
λ gcalcli agenda --calendar epita

No Events Found...

λ gcalcli agenda --calendar https://acu.epita.fr/chronos/calendars/CSI.ics

No Events Found...
```

**Comment by tresni** [comment]
Delete your `$HOME/.gcalcli_cache` file or use the `--nocache` option.  The only thing that is cached today is the list of calendars.
