### ISSUE TITLE
Different colors for different calendars

### ISSUE THREAD

**Issue by alexozer** [insanum/gcalcli#233]
It would be nice if you could specify different colors for different calendars, something like specifying --color sets the color of the most recent --calendar.

**Comment by tresni** [comment]
You already can it is just not very well (read: at all) documented. 

`--calendar brian#black`

Would make that calendar black (not that it would be super useful). Any of the color names defined elsewhere in the documentation would work.

**Comment by alexozer** [comment]
Oh very nice, thank you! Probably should document that.
