### ISSUE TITLE
Not working, asking for modules

### ISSUE THREAD

**Issue by carlospgmat03** [insanum/gcalcli#236]
I am trying to make it work. Could you give a combination of versions of python, oauth2client and gcalcli that make it work correctly? I think I tried several without luck. In my desktop it complains with 

ERROR: Missing module - cannot import name run

thanks!

**Comment by tresni** [comment]
See #211 .  How did you setup gcalcli?

**Comment by carlospgmat03** [comment]
Thanks. I had seen it, and I thought I had tried it. Just to make sure, I tried again with oauth2client=1.4.12 and it worked!
