### ISSUE TITLE
Custom colors

### ISSUE THREAD

**Issue by Erulisse** [insanum/gcalcli#240]
As far as I can tell the user can only use the predefined color set allowed by the application. The availability of custom color sets would be nice.

**Comment by tresni** [comment]
`--calendar=brian#red`

**Comment by Erulisse** [comment]
Exactly, it's predefined in the code.  I'm referring to the ability to use something like 

"<Esc>[48;5;ColorNumberm"

**Comment by tresni** [comment]
Got ya. Yeah that has come up before and I think there is even a branch that started down that line. But nothing in master yet...

**Comment by Walt1256** [comment]
Pulling gcalcli agenda into Conky, I am able to use some of my Conky-defined colors. However, I only seem to be able to use two of those colors.  I have four calendars that I have access to read (three of which I can also write to). I tried the color command that tresni indicated (does it go in the def SetConkyColors(): section?), but it did not seem to work.

I have a few questions: 1) should those color commands go somewhere else in the gcalcli file; 2) if a calendar name has two (or more) words in it, should there be a space or an underscore (or something else) between those words; 3) in defining those colors, is it possible yet to use HTML color codes (e.g., ff0000)? 

I'm afraid I don't know much at all about coding and even less about how gcalcli works, so I apologize if my questions are simplistic. Thanks.

**Comment by tresni** [comment]
See #90 .
