### ISSUE TITLE
shared calendars not accessible

### ISSUE THREAD

**Issue by ccnixon** [insanum/gcalcli#241]
I have my personal calendar shared with my work calendar. The personal calendar does not appear to be accessible though per `gcalcli list`.

Is there a workaround for this?

Thanks!

**Comment by insanum** [comment]
Are both these calendars on the same Google account?

**Comment by rupa** [comment]
I have same issue, with work calendar shared with personal calendar. they are _not_ on the same account.

**Comment by Ticonderoga** [comment]
Same here ... unable to list events in a share calendar (url import) or even to list the calendar !!

**Comment by geolado** [comment]
Same here , any idea ?

**Comment by tresni** [comment]
I have a number of shared calendars (on both personal and work) and they all show up... Have you tried removing the `$HOME/.gcalcli_cache` file or using the `--nocache` option?  Could just be that we have an out-of-date cache and the calendars weren't there when we asked the first time.

**Comment by rafi** [comment]
Removing cache fixed it for me.

**Comment by firecat53** [comment]
I'd recommend making a comment about this in the README. It's a simple fix, but not obvious :)  Thanks!

**Comment by mckao** [comment]
I have the same issues and still can not figure it out. Any idea?

**Comment by jcrowgey** [comment]
mckao: you tried remove the cache file?

**Comment by yermulnik** [comment]
Removing cache file fixed all the same issue for me with a newly added calendar and it took me a while to fond the fix. It's definitely worth mentioning this in README please.
