### ISSUE TITLE
Agenda, Quick, Calw, and Calm all take 2m8s...

### ISSUE THREAD

**Issue by xGDPx** [insanum/gcalcli#243]
So just installed and got gcalcli working and the one thing I've noticed is basically any command I've tested takes 2m8s (+/- .5sec) to execute. Is this normal or a known issue or is there some configuration somewhere I've jacked up? (Sorry to spam like this but I couldn't find anything on Google, in the closed/open issues, or in the documentation.)

time { gcalcli --calendar "Work" agenda; } -- real  2m8.036s
time { gcalcli --calendar "Work" calw; } -- real    2m7.883s
time { gcalcli --calendar "Work" quick 'Test Meeting'; } --real 2m8.155s

**Comment by tresni** [comment]
Hmm, interesting observation.  It may have more to do with the number of events you have in each time period.  For me the timings looks like:

```
Projects/gcalcli ●» time ./gcalcli calw > /dev/null                                                                            « [argparse_over_gflags]
./gcalcli calw > /dev/null  0.30s user 0.05s system 8% cpu 4.267 total
Projects/gcalcli ●» time ./gcalcli calm > /dev/null                                                                            « [argparse_over_gflags]
./gcalcli calm > /dev/null  0.37s user 0.06s system 11% cpu 3.785 total
Projects/gcalcli ●» time ./gcalcli agenda > /dev/null                                                                          « [argparse_over_gflags]
./gcalcli agenda > /dev/null  0.29s user 0.05s system 9% cpu 3.559 total
Projects/gcalcli ●»
```

So your connectivity is definitely going to play a part.  Additionally, keep in mind that we do no caching.  So every request you makes goes up to google, gathers the data, and comes back to be rendered.  If you have a ton of events, this happens about every 100 events or so.
