### ISSUE TITLE
OAuth2 Error: invalid_request

### ISSUE THREAD

**Issue by bdaigle** [insanum/gcalcli#245]
When I run gcalcli after deleting .gcalcli_oauth, my browser opens to a Google error page with the following message:

"400. That's an error.
Error: invalid_request
Invalid response_type: code\\\"

If I manually edit the url in the browser by removing all four instances of "\\\" and refresh, everything works fine. Any ideas why the original url is incorrect? I am working with gcalcli 3.3.2, google-api-python-client 1.4.2, and oauth2client 1.4.12.

**Comment by tresni** [comment]
I don't believe this has ever been seen before.  What operating system, version of python, etc?

Do you see the same issue if you install the latest test release (`pip install gcalcli==4.0.0a1`) and delete the `$HOME/.gcalcli_oauth` file?

**Comment by bdaigle** [comment]
I just upgraded to gcalcli 3.4.0, and the issue no longer occurs after deleting the .gcalcli_oauth file. I would consider the issue closed.
