### ISSUE TITLE
How to add entry without reminder?

### ISSUE THREAD

**Issue by ReekenX** [insanum/gcalcli#248]
Tricky to understand how to add entries without reminders.

Readme says:

    --[no]default_reminders: If no --reminder is given, use the defaults. If this
    is false, do not create any reminders.
    (default: 'true')

1) Is --nodefault_reminders is false? And --default_reminders is true?
2) I am using:

    gcalcli --calendar "$CALENDAR" --title "$TITLE" --when $START --duration $TIME_BONUS --where '' --description "$DESCRIPTION" --nouse_reminders --nodefault_reminders --nocache --military add

It raises me an error:

    Enter a valid reminder or '.' to end:

What does that even mean?

3) So what is proper syntax to add entry without reminder? Tried this:

    gcalcli --calendar "$CALENDAR" --title "$TITLE" --when $START --duration $TIME_BONUS --where '' --description "$DESCRIPTION" --nouse_reminders --nodefault_reminders --reminder 0 --nocache --military add

But even with `nouse_reminders` and `nodefault_reminders` it gives me an entry with "immedialy remind" in GCal.

And finally - I really like what you did. Been using this for half year already.

**Comment by drisher** [comment]
This is quite obscure, but looking at the source code I found a solution. Choose the flag --noprompt. This will allow you to omit flags like --reminder, and the event will be created without reminders. You can also omit other flags like --description, --where, etc.

**Comment by ReekenX** [comment]
I already figured it out by looking into source code.

I am closing this, since workaround and/or explanation is already done by @drisher.
