### ISSUE TITLE
gcalcli seems to set a timezone for events

### ISSUE THREAD

**Issue by Miesco** [insanum/gcalcli#251]
My timezone is set on my computer correctly.  When I add an event with `gcalcli quick`, it sets an "event timezone".  This causes the event to show at the wrong time.

In google calendar, it shows an "Event Timezone".  To get rid of this and to use my local timezone, I have to click the blue "time zone" link and delete that "event timezone".

![timezone](http://i.imgur.com/QMtQHZi.png)

How do I add events without any timezone data to it?

This only seems to happen when I use an 'every thursday' clause in the `gcalcli quick`.

**Comment by tresni** [comment]
When using `gcalcli quick` we do **no** parsing on the text you enter.  It is sent straight to Google and they do their magic with it.  So any timezone is being set by Google based on calendar preferences or Google magic.

**Comment by seven20solutions** [comment]
10 years later... I had this issue too...!

For anyone who runs into it, Google has a timezone setting for each of your individual calendars. So you need to have it set correctly for each calendar. Nothing to do with gcalcli.
