### ISSUE TITLE
Event added to wrong week

### ISSUE THREAD

**Issue by dspoka** [insanum/gcalcli#253]
I have something that does a quick add of "Meeting':'Murat at 5pm on Wednesday"

If I run the string 'Murat at 5pm on Wednesday' just through the parsedatatime library to get the time it shows this weeks wednesday (24 aug) however when I do 

gcalcli --calendar Classes --prompt quick --details url "Murat at 5pm on Wednesday"

It adds it to the previous week Aug 17th. 

Not sure if there are things to pass here to make this work properly.

**Comment by tresni** [comment]
`--quick` does not parse your string through the datetime or parsedatetime libraries. We send it to Google exactly as you gave it to us and they parse it server side. 

-- Brian
