### ISSUE TITLE
[Q] Is it possible to edit ACCESS section to reflect specific calendars?

### ISSUE THREAD

**Issue by Walt1256** [insanum/gcalcli#255]
In gcalcli, the class gcalcli shows the following:
ACCESS_OWNER = 'owner'
    ACCESS_WRITER = 'writer'
    ACCESS_READER = 'reader'
    ACCESS_FREEBUSY = 'freeBusyReader'
(snip)
  # gcalcli defined way to order calendars
        order = {self.ACCESS_OWNER: 1,
                 self.ACCESS_WRITER: 2,
                 self.ACCESS_READER: 3,
                 self.ACCESS_FREEBUSY: 4}

Is is possible to change those to point to or reflect specific calendars instead? I have four calendars I monitor, two that I own, one that I have write access to, and another that I can read. I would like to be able to make it so that the two calendars I own show up in different colors and it seems this would be the section in which to do that. Other suggestions (by both tresni and insanum) for adding specific calendars and specifying colors (both in gcalcli and in .gcalclirc) have not worked for me thus far.

**Comment by tresni** [comment]
This is used for setting color based on your access to the calendar, not the calendar itself.  #254 is the right way to do it.
