### ISSUE TITLE
Can't set default calendars in ~/.gcalclirc

### ISSUE THREAD

**Issue by p-phillips** [insanum/gcalcli#257]
Hi
Great utility by the way!

Trying to set up my ~/.gcalclirc file so that it only shows one or two of my calendars.

On the command line, this works:

`gcalcli --calendar="Pete (Work)"\#red --calendar="Pete (Home)"\#green agenda`

but if I put the following two lines in the rc file as follows:

```
--calendar="Pete (SMTL)"#red                                                                                                                   
--calendar="Pete (Home)"#green  

```
and run    `gcalcli agenda`  I get:  

`No Events Found...`

Any clues on what I'm doing wrong ?  Version is 3.3.2 

Pete

**Comment by tresni** [comment]
It seems like there is something up with calendars with spaces in them in the gcalclirc. On another bother. In your gcalclirc use --defaultCalendar. That way if you pass a --calendar option on the command line it can override what's in your configuration vs add to the list. 

-- Brian

**Comment by p-phillips** [comment]
Hi Brian

Thanks for responding so quickly.

I don't quite understand your advice I'm afraid:

On another bother. In your gcalclirc use --defaultCalendar.
>

Could you explain in a bt more detail ?

Also, is there any way to fix the problem with appropriate quoting in the
config file ?

Pete

**Comment by tresni** [comment]
In your `.gcalclirc` use the following (notice no quotes and one per line.)

```
--defaultCalendar=Pete (SMTL)#red                                                                                                                   
--defaultCalendar=Pete (Home)#green  
```

I've verified that this will work (or does for my calendars at least ;-)

**Comment by p-phillips** [comment]
Perfect. Confirmed for my calendars also.
Thanks.
