### ISSUE TITLE
How to set the default period for the agenda

### ISSUE THREAD

**Issue by p-phillips** [insanum/gcalcli#259]
I hope I'm not being an idiot, but I can't see any way to set the default parameters for the number of days an agenda shows (the default is 5 but  I want it to default to 10).

Looking for something that will give me the same as

`gcalcli agenda today '10 days'`

Cheers
Pete

**Comment by tresni** [comment]
That is not possible today without editing they python directly.  You either specify it in your command or get 5 :)
