### ISSUE TITLE
Bug in _tsv(self, startDateTime, eventList):

### ISSUE THREAD

**Issue by Ticonderoga** [insanum/gcalcli#261]
I found a bug about unicode in the tsv part :
           output = "%s\t%s\t%s\t%s" % (event['s'].strftime('%Y-%m-%d'),
                                         event['s'].strftime('%H:%M'),
                                         event['e'].strftime('%Y-%m-%d'),
                                         event['e'].strftime('%H:%M'))

should be replaced by : 
            output = "%s\t%s\t%s\t%s" % (event['s'].strftime('%a %d %b %Y').decode(locale.getlocale()[1]),
                                         event['s'].strftime('%H:%M'),
                                         event['e'].strftime('%a %d %b %Y').decode(locale.getlocale()[1]),
                                         event['e'].strftime('%H:%M'))

the strftime could remain in english (%Y%m%d) ... I changed it for my personnal use but the decode part should be included in the code. The main problem concerns the month name with accents. Examples in French : 
  Décembre : Decembre 
  Février : February

Hope it helps

**Comment by tresni** [comment]
Good catch. I'll get a change incorporated for the next alpha release. 

-- Brian
