### ISSUE TITLE
New calendar

### ISSUE THREAD

**Issue by GrouchyGaijin** [insanum/gcalcli#262]
I am running Ubuntu 16.04 and gcalcli version 3.3.3
Is there anything I need to do to have gcalcli scan for new calendars?
I have created an additional google calendar and it will show up in Evolution, but gcalcli does not see it when I run the list command.

**Comment by GrouchyGaijin** [comment]
Nevermind...user error.  I reauthenticated and the new calendar was found.

**Comment by kiloamp** [comment]
https://github.com/GrouchyGaijin How did you authenticated?
