### ISSUE TITLE
error when adding in v4.0.0a2

### ISSUE THREAD

**Issue by rhavenn** [insanum/gcalcli#268]
Using FreeBSD with a custom port build of the 4.0.0.a2 alpha so I can use the latest oauth client. Showing existing calendars works, but when I try to add an event like this:

`gcalcli --calendar 'my cal' add --reminder 0 --reminder 15m --reminder 1h --title test --duration 60 --when '10/07/2016 23:00'`

I get the following error:

>   Traceback (most recent call last):
>   File "/usr/local/bin/gcalcli", line 2493, in <module> 
>     BowChickaWowWow()
>   File "/usr/local/bin/gcalcli", line 2449, in BowChickaWowWow
>     FLAGS.reminder)
>   File "/usr/local/bin/gcalcli", line 1817, in AddEvent
>     insert(calendarId=self.cals[0]['id'], body=event))
>   File "/usr/local/lib/python2.7/site-packages/googleapiclient/discovery.py", line 692, in method
>     actual_path_params, actual_query_params, body_value)
>   File "/usr/local/lib/python2.7/site-packages/googleapiclient/model.py", line 149, in request
>     body_value = self.serialize(body_value)
>   File "/usr/local/lib/python2.7/site-packages/googleapiclient/model.py", line 258, in serialize
>     return json.dumps(body_value)
>   File "/usr/local/lib/python2.7/json/**init**.py", line 244, in dumps
>     return _default_encoder.encode(obj)
>   File "/usr/local/lib/python2.7/json/encoder.py", line 207, in encode
>     chunks = self.iterencode(o, _one_shot=True)
>   File "/usr/local/lib/python2.7/json/encoder.py", line 270, in iterencode
>     return _iterencode(o, 0)
>   File "/usr/local/lib/python2.7/json/encoder.py", line 184, in default
>     raise TypeError(repr(o) + " is not JSON serializable")
> TypeError: <itertools.imap object at 0x8053d08d0> is not JSON serializable

**Comment by kn1701** [comment]
I get the same error since updating to 4.0.0a2 - unable to add events using 'add' (still works using 'quick').
