### ISSUE TITLE
agenda is unknown argument

### ISSUE THREAD

**Issue by amitkalani1** [insanum/gcalcli#269]
I'm trying to get gcalcli to auth with the first command after installing, but it just gives me that:

```
gcalcli agenda
usage: gcalcli [--auth_host_name AUTH_HOST_NAME] [--noauth_local_webserver]
               [--auth_host_port [AUTH_HOST_PORT [AUTH_HOST_PORT ...]]]
               [--logging_level {DEBUG,INFO,WARNING,ERROR,CRITICAL}]
gcalcli: error: unrecognized arguments: agenda

```

**Comment by tresni** [comment]
How are you installing?  Which version?  What platform are you running on?

**Comment by some1563** [comment]
gcalcli v3.4.0 (Eric Davis, Brian Hartvigsen)

installed on arch with yaourt from https://aur.archlinux.org/packages/gcalcli-git/

**Comment by Paddre** [comment]
@some1563 : I had a similar problem (also under arch with the same version of gcalcli). Installing it via `pip2 install gcalcli` fixed it.

**Comment by tresni** [comment]
Per https://aur.archlinux.org/packages/gcalcli-git/ this seems to be an issue with the arch package and will be resolved by that maintainer.
