### ISSUE TITLE
add attendees when importing a ICS file

### ISSUE THREAD

**Issue by Azulinho** [insanum/gcalcli#27]
I received the following ICS invite

BEGIN:VCALENDAR
METHOD:REQUEST
PRODID:Microsoft Exchange Server 2010
VERSION:2.0
BEGIN:VTIMEZONE
TZID:Romance Standard Time
BEGIN:STANDARD
DTSTART:16010101T030000
TZOFFSETFROM:+0200
TZOFFSETTO:+0100
RRULE:FREQ=YEARLY;INTERVAL=1;BYDAY=-1SU;BYMONTH=10
END:STANDARD
BEGIN:DAYLIGHT
DTSTART:16010101T020000
TZOFFSETFROM:+0100
TZOFFSETTO:+0200
RRULE:FREQ=YEARLY;INTERVAL=1;BYDAY=-1SU;BYMONTH=3
END:DAYLIGHT
END:VTIMEZONE
BEGIN:VEVENT
ORGANIZER;CN="Hansen, Sune":MAILTO:Sune.Hansen@acme.com
ATTENDEE;ROLE=REQ-PARTICIPANT;PARTSTAT=NEEDS-ACTION;RSVP=TRUE;CN=tnielse3@c
 sc.com:MAILTO:tnielse3@acme.com
ATTENDEE;ROLE=REQ-PARTICIPANT;PARTSTAT=NEEDS-ACTION;RSVP=TRUE;CN=Kent Micha
 elsen (kmichaelsen@acme.com):MAILTO:kmichaelsen@acme.com
ATTENDEE;ROLE=REQ-PARTICIPANT;PARTSTAT=NEEDS-ACTION;RSVP=TRUE;CN="Costa, Jor
 ge":MAILTO:Jorge.Costa@acme.com
ATTENDEE;ROLE=REQ-PARTICIPANT;PARTSTAT=NEEDS-ACTION;RSVP=TRUE;CN=Martyn K H
 olden (mholden6@acme.com):MAILTO:mholden6@acme.com
DESCRIPTION;LANGUAGE=en-US:All\,\n\nThis is a Placeholder for next week’s
  TOI –\nWebex and Con Call details will follow.\n\n/Sune\n\n
SUMMARY;LANGUAGE=en-US:SnapCreator TOI
DTSTART;TZID=Romance Standard Time:20121024T113000
DTEND;TZID=Romance Standard Time:20121024T133000
UID:040000008200E00074C5B7101A82E00800000000E082784ADAADCD01000000000000000
 01000000078F78DCB98419F4889FE6A4B96A6DAF2
CLASS:PUBLIC
PRIORITY:5
DTSTAMP:20121019T071532Z
TRANSP:OPAQUE
STATUS:CONFIRMED
SEQUENCE:0
LOCATION;LANGUAGE=en-US:Webex and Con Call
X-MICROSOFT-CDO-APPT-SEQUENCE:0
X-MICROSOFT-CDO-OWNERAPPTID:2104731612
X-MICROSOFT-CDO-BUSYSTATUS:TENTATIVE
X-MICROSOFT-CDO-INTENDEDSTATUS:BUSY
X-MICROSOFT-CDO-ALLDAYEVENT:FALSE
X-MICROSOFT-CDO-IMPORTANCE:1
X-MICROSOFT-CDO-INSTTYPE:0
X-MICROSOFT-DISALLOW-COUNTER:FALSE
BEGIN:VALARM
ACTION:DISPLAY
DESCRIPTION:REMINDER
TRIGGER;RELATED=START:-PT15M
END:VALARM
END:VEVENT
END:VCALENDAR

which I imported into google calendar using

[535]$ cat /usr/share/applications/import-ICS-into-google-calendar.desktop
[Desktop Entry]
Name=Import ICS file into Google Calendar
GenericName=Import ICS file into Google Calendar
X-GNOME-FullName=Import ICS file into Google Calendar
Comment=Import ICS file into Google Calendar
Exec=gcalcli --cal "mycalendar" import  %U
Icon=chromium-browser
Terminal=false
TryExec=chromium-browser
Type=Application
MimeType=application/x-calendar;x-scheme-handler/ics;
Categories=Network;
X-AppInstall-Keywords=calendar

it shows up with the:
- WHERE bits: 
  Webex and Con Call
- TEXT bits:

All,

This is a Placeholder for next week’s TOI –
Webex and Con Call details will follow.

/Sune

but the atendee list is missing

**Comment by lasombra** [comment]
I am very sorry to re-open this but I'm seeing an issue where when I import a file all attendees are invited as well to the imported event on my calendar. Can this be optional during import please?

**Comment by tresni** [comment]
My understanding is that this should be controlled by the ["sendNotifications" url parameter](https://developers.google.com/google-apps/calendar/v3/reference/events/insert#parameters).  This parameter defaults to false and we don't override that (at least not as far as I can see.)  Not sure there is anything else we can do this...

**Comment by lasombra** [comment]
Maybe an explicit option to import to not include attendees?

I don't know what is causing this either but when I import a new .ics 
files, generated from Google Calendar, all the attendees receive a 
notification and, as they accept or refuse the meeting, I see their 
acceptance or refusal on my calendar as it was the primary source.

**Comment by lasombra** [comment]
I can test whatever's needed in case there's a need.

**Comment by samsunix** [comment]
lasombra - mind to share your ics file and method you use to import it to google calendar. I am stuck here.

Thank you very much in advance.

**Comment by jahagirdar** [comment]
Is there any update on this? I installed gcalcli today, imported my first calender invite via the following mutt macro
macro attach ,c "<pipe-entry>gcalcli --reminder=10 --detail_url=short --calendar='Dyumnin' import\n"

and it looks like it sent out invites to other participants...

**Comment by lasombra** [comment]
@samsunix Unfortunately it took me 1 year to see your update.

I used the following command: ` gcalcli import --calendar="my@calendar.com" calendar_test_issue.ics`

I still see the issue. Here's the screenshot, https://imgur.com/a/aRCWB6O. Notice that both guests are "awaiting"

**Comment by lasombra** [comment]
This issue still persists. Should I file a new issue to track this down?
