### ISSUE TITLE
poor man's sync tool?

### ISSUE THREAD

**Issue by sje30** [insanum/gcalcli#272]
What's the easiest way to use gcalcli as a simple syncing tool?

I'm mainly interested in a one-way sync, from local .ics file to google.  So one thought I had was to periodically do the following:

1. delete all entries from google calendar
2. import the .ics file

my .ics file has on the order of ~100 entries so would that be overkill?  I see there are other issues for this (#216 #47 ), so apologies if this is a duplicate.

**Comment by tresni** [comment]
I wouldn't recommend this right now as it would be really expensive from an API standpoint.  You'd likely hit your account's API limits.  There was some work a while back to make importing ICS's duplicate-aware, but nothing wrt to "syncing".  Just not a use case we've worked towards.
