### ISSUE TITLE
Pb with authentication

### ISSUE THREAD

**Issue by PelargoniumTomentosum** [insanum/gcalcli#275]
hello, 
I do not check google authification.
I generated a client and key api in google desk. 
I wrote them in the file .gcalclirc 
 I have on my browser : 
400. That’s an error.
Error: redirect_uri_mismatch
thank you for our help
regards

**Comment by tresni** [comment]
Sounds like you may have generated the wrong type of key/token.  http://stackoverflow.com/questions/11485271/google-oauth-2-authorization-error-redirect-uri-mismatch
