### ISSUE TITLE
Set default calendar

### ISSUE THREAD

**Issue by russellchill** [insanum/gcalcli#278]
is there a way to set a default calendar without having to to specify --calendar everytime?

ie)  gcalcli quick "11:00 tomorrow Lunch" --calendar "mycal"

can be:
     gcalcli quick "11:00 tomorrow Lunch"

**Comment by jimioke** [comment]
There's a `defaultCalendar` option, apparently, but I haven't been able to figure out how to set it or use it.

**Comment by tresni** [comment]
Best place to set it is in your .gcalclirc file:

```
--defaultCalendar=brian.andrew#red
```

Make sure each option is on it's own line.

**Comment by jimioke** [comment]
Thanks tresni. I was trying to set in from the command line but that wasn't working
