### ISSUE TITLE
Quick add recurring events

### ISSUE THREAD

**Issue by mickwar** [insanum/gcalcli#280]
Executing the following command

`gcalcli --calendar 'mycal' quick 'Test Thursday at 6am weekly'`

correctly adds the recurring event. However, the event is also added to the current day. For instance, suppose today is Tuesday and I run the command above, the weekly event is added to the Thursdays as well as today (but not any other Tuesday).

When typing in 'Test Thursday at 6am weekly' to the quick add on the Google Calendar website, the event is not added to today as it is when using gcalcli.

**Comment by tresni** [comment]
We don't do any processing on `quick` the text is sent to Google exactly as entered.  Any issues would need to be raised with Google on that.
