### ISSUE TITLE
Facebook Calendar is missing

### ISSUE THREAD

**Issue by ghost** [insanum/gcalcli#281]
Hello today realized that my Facebook Calendar which already linked to Google calendar is not seenable in `gcalcli calw` even if it exist in `gcalcli list`

**Comment by tresni** [comment]
If you can give steps to reproduce it might be helpful.  I have no idea how to link my facebook calendar to google calendar and didn't find instructions quickly googling.   You could try a `gcalcli --refresh calw` to see if that helps.  Also make sure your `.gcalclirc` isn't limiting the calendars with `--defaultCalendar` options.

**Comment by jcrowgey** [comment]
Closing because we don't have repro steps.  @ghost if this is still an issue please follow up here.
