### ISSUE TITLE
poorly aligned agenda in conky

### ISSUE THREAD

**Issue by capstan1** [insanum/gcalcli#283]
I'm using gcalcli for displaying my agenda in conky. Great fan here!

However alignment in conky is strange (contrary to gcalclis output in terminal.
I'm just using:
`gcalcli agenda --nocolor --military now`

Comparison of alignment in conky and in terminal can be seen in attachments.

Any solution to this?

![bildschirmfoto von 2017-02-08 18 03 48](https://cloud.githubusercontent.com/assets/17147867/22748239/a92c79ec-ee29-11e6-84a2-b5fd381e1bf0.jpeg)
![bildschirmfoto von 2017-02-08 18 08 39](https://cloud.githubusercontent.com/assets/17147867/22748240/a94abde4-ee29-11e6-946e-c96b7189c0a2.jpeg)

**Comment by tresni** [comment]
Use a fixed width font.  Alignment is done via spaces, so if your font has different sizes for different characters, it won't align correctly.

**Comment by capstan1** [comment]
Oh thanks! That did the trick! (Although it's not so good looking with a Mono font :P )
