### ISSUE TITLE
Newly shared calendar not synced to gcalcli

### ISSUE THREAD

**Issue by IniZio** [insanum/gcalcli#284]
I connected to my google account, but when I got a new shared calendar, it does not seem to be synced to the gcalcli client? Is there a command  for syncing it?

**Comment by gniding** [comment]
see https://github.com/insanum/gcalcli/issues/241

**Comment by IniZio** [comment]
Thanks it matches my issue, sorry should have read through the issues. Issue can be closed due to duplication.
