### ISSUE TITLE
Dollar sign $ Not handled well with --conky

### ISSUE THREAD

**Issue by cjsheets** [insanum/gcalcli#285]
I'll try and tackle this when I get time. Right not dollar signs aren't handled well when parsing output for conky.

Only noticed this because a spambot added an event that I'm having trouble removing which includes a '$' symbol.

**Comment by tresni** [comment]
Can you give steps to reproduce what you are doing please?

**Comment by cjsheets** [comment]
I investigated further this morning and think I was incorrectly attributing a lack of a (needed) `--nolineart` flag with trouble caused by a $ sign.

I stupidly found and deleted my test case (the spam message) and am no longer reproducing any issues.

Thanks for the quick reply. I'll be more careful next time.
