### ISSUE TITLE
Add a new calendar to Google - How can I get gcalcli to see it?

### ISSUE THREAD

**Issue by GrouchyGaijin** [insanum/gcalcli#286]
I have added a second calendar in Google.  When I type gcalcli list the new calendar is not seen.
What should I do so that gcalcli will pick up both of my calendars?

**Comment by webavant** [comment]
For me, this is normal behavior. New calendar does not display in `gcalcli list` until after doing `gcalcli --refresh <command>`.

**Comment by tresni** [comment]
`--refresh` is correct.  We cache the calendars you have access to.
