### ISSUE TITLE
Is there an option to show other fields when doing search?

### ISSUE THREAD

**Issue by adamryczkowski** [insanum/gcalcli#288]
I want to see the `description` and `when` fields as well as the title when dumping all my appointments using

```
gcalcli search "*"
```

Is there a built-in option to do it?

**Comment by tresni** [comment]
`--details description` will get you the description (if any exists.)  When should be output automatically with any search.

Any reason for doing `search "*"` instead of agenda?  Are you trying to get all of them ever?

**Comment by adamryczkowski** [comment]
Yes. I came here in a quest to find a tool that would backup/dump all my calendar data into something human-readable, so I can harvest phone numbers, addresses and stuff like this :-)
