### ISSUE TITLE
file_cache is unavailable when using oauth2client >= 4.0.0

### ISSUE THREAD

**Issue by Purgator** [insanum/gcalcli#290]
Hello there,

I just want to point out a warning that is prompted everytime I call a specific configuration folder.
If I start gcalcli with the default one, everything is ok.

Note that everything works fine.

Example :
**$ gcalcli --configFolder .gcalcli-perso agenda**
```
WARNING:googleapiclient.discovery_cache:file_cache is unavailable when using oauth2client >= 4.0.0
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/googleapiclient/discovery_cache/__init__.py", line 41, in autodetect
    from . import file_cache
  File "/usr/lib/python2.7/site-packages/googleapiclient/discovery_cache/file_cache.py", line 41, in <module>
    'file_cache is unavailable when using oauth2client >= 4.0.0')
ImportError: file_cache is unavailable when using oauth2client >= 4.0.0
```

If I type 
$ gcalcli agenda
no warning is prompted

I know that this issue is not a problem and I could hide it but I would like to keep potentials errors on the screen without this useless warning.

Regards.

**Comment by tresni** [comment]
More interesting is that that code and error is all contained in the googleapiclient.  So while it's code we rely on, we don't explicitly use `file_cache`

**Comment by dbarnett** [comment]
Obsolete, oauth2client dep has been removed.
