### ISSUE TITLE
[Cache] Keep data to display calendar while offline

### ISSUE THREAD

**Issue by Purgator** [insanum/gcalcli#305]
Hello,

Is there any way to calL gcalcli without internet connection ?
I would like to display my last known calendar if i'm offline, or update it if i'm online.

I tried the option --[no]cache but it has no effect. There is nothing particular in gcalcli --help.

Any clue ? Thx

**Comment by tresni** [comment]
`--[no]cache` deals with whether we used the cached list of calendars, not calendar event information.  There was an attempt at caching a while back, but it had some issues and was reverted.  While it should be possible, it doesn't exist today.

**Comment by elwais** [comment]
Hmm, I'm interested in the idea of using some sort of cache to allow for offline access and would like to learn more. I've tried to look through some of the git commits but wasn't able to find where caching was reverted. Would you be able to point me to the commit where caching was reverted? Additionally, if I were able to make some progress implementing caching, would you be open to contributions? (This is all a big fat **if** by the way; it's entirely possible I won't be able to solve the problem, but I thought I'd check just in case).
