### ISSUE TITLE
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:590)

### ISSUE THREAD

**Issue by Augustus175** [insanum/gcalcli#310]
my python version is 2.7
when I run gcalcli agenda it Reported the mistake .
please help me ,thanks !

**Comment by jcrowgey** [comment]
We're currently working on a bit of an overhaul in master.   Can you confirm that you still have the issue?

**Comment by jcrowgey** [comment]
Since we don't have a repro case and the information we do have suggests a transient network issue, I'm closing this.  Please reopen if this is reproducible.
