### ISSUE TITLE
Add the possibility to specify color per calendar in configuration file

### ISSUE THREAD

**Issue by edumerco** [insanum/gcalcli#314]
Hello. 
I've found in some issues that -although it's not documented- it's possible to define calendar colors in the command line. Would it be possible to add the possibility to specify the color per calendar in the .gcalclirc file? 
In this way the command line gets cleaner.  

Thanks a lot for gcalcli. It's wonderful. :)

Best...

**Comment by tresni** [comment]
Should be able to use the same syntax in your configuration file to specify calendar color.  I would recommend using `defaultCalendar` that way you can overwrite the settings on the command line using `--calendar` options.

**Comment by edumerco** [comment]
I'lll try that. Again, thanks a lot for sharing your work. 👍 d^_^b
