### ISSUE TITLE
deprecated print statement 

### ISSUE THREAD

**Issue by j0hannes** [insanum/gcalcli#317]
That's the error:
```
  File "/usr/local/bin/gcalcli", line 199
    print "ERROR: Missing module - %s" % e.args[0]
                                     ^
SyntaxError: Missing parentheses in call to 'print'

```

and that's the context:
```
% cat $(which gcalcli)|sed -n 187,200p
# Required 3rd party libraries
try:
    from dateutil.tz import tzlocal
    from dateutil.parser import parse
    import gflags
    import httplib2
    from apiclient.discovery import build
    from apiclient.errors import HttpError
    from oauth2client.file import Storage
    from oauth2client.client import OAuth2WebServerFlow
    from oauth2client.tools import run
except ImportError as e:
    print "ERROR: Missing module - %s" % e.args[0]
    sys.exit(1)
```

**Comment by tresni** [comment]
I think you are running an old version that was python2 only under python3.  You need version 4.0.0a2 or later for Python3 support.

**Comment by j0hannes** [comment]
according to pip it's `Version: 3.4.0`

**Comment by tresni** [comment]
That version does not support python3

-- Brian

**Comment by j0hannes** [comment]
But apparently it starts with
```
% cat $(which gcalcli)|head -n1
#!/usr/bin/python3
```

For Python2 some dependencies seem to be missing:
```
% python2.7 $(which gcalcli) 
ERROR: Missing module - No module named dateutil.tz
```

**Comment by tresni** [comment]
That change must be made by the package maintainer as line 1 for 3.4.0 definitely doesn't contain python 3 see https://github.com/insanum/gcalcli/blob/master/gcalcli#L1

**Comment by j0hannes** [comment]
According to pip, this is the URL where the package is maintained:
```
pip show gcalcli                                                                    
Name: gcalcli
Version: 3.4.0
Summary: Google Calendar Command Line Interface
Home-page: https://github.com/insanum/gcalcli
Author: Eric Davis, Brian Hartvigsen
Author-email: edavis@insanum.com, brian.andrew@brianandjenny.com
License: MIT
Location: /usr/local/lib/python3.5/dist-packages
Requires: python-dateutil, httplib2, python-gflags, oauth2client, google-api-python-client
```

**Comment by tresni** [comment]
Not sure why pip would let you install 3.4.0 on python 3.  Definitely stated in the setup.py that it only supports python2 :)  Maybe pip will let you shoot yourself in the foot?

Anyway, if you want to use python3, do:

`pip install gcalcli==4.0.0a3`

That'll get you the latest version that is python3 compatible.  (`pip install --upgrade gcalcli` might work too)

**Comment by j0hannes** [comment]
Thanks for the tip!

I just discovered that it's setuptools that rewrite the shebang and on my server, pip now means pip3 after some update. That is, using pip2 for installing gcalcli solved the issue.

But if development continues on python3, I better should already change it.
