### ISSUE TITLE
Deleting events containing single quote (apostrophe)

### ISSUE THREAD

**Issue by sje30** [insanum/gcalcli#319]
Hi, I'm trying to delete a calendar item called "dog's birthday" - but I am having no luck in finding the right syntax to quote the apostrophe.  Can anyone suggest what might work?

```
$~ $ gcalcli agenda
No handlers could be found for logger "oauth2client.util"

Thu Oct 19         Forecast for cb3 0wa (18° | 11°)
            14:30  dog's birthday

$ gcalcli delete "dog's birthday"
No handlers could be found for logger "oauth2client.util"
No Events Found...

$ gcalcli delete """dog's birthday"""
No handlers could be found for logger "oauth2client.util"

No Events Found...
```

**Comment by jcrowgey** [comment]
```
$ gcalcli add --allday
Title: dog's birthday
Location: everywhere
When: tomorrow
Duration (days): 1
Description: test
Enter a valid reminder or '.' to end: .
$ gcalcli agenda

Sun Aug 05           dog's birthday
             7:00am  test
            12:00pm  🎈unicode test š x̌ ʔ ə

Wed Aug 08   4:00pm  salas

$ gcalcli delete "dog's birthday"

2018-08-05           dog's birthday
Delete? [N]o [y]es [q]uit: y
Deleted!
```

I can't repo this.  I tested gcalcli 3.4 on python2.7 and I tested on python3 on current master.  Please reopen this issue if you're still having it with details about your platform and environment which may help us reproduce.

I suspect that those messages about "No handlers found for oauth2client.util" are actually more related to what's going on for you.

**Comment by sje30** [comment]
ok, thanks for checking!
