### ISSUE TITLE
Import ics file, last day missing

### ISSUE THREAD

**Issue by rzmc10** [insanum/gcalcli#328]
I try to import some .ics files to google calendar.
When I import an event that goes from 2017/12/22 to 2018/01/05, on the calendar I see it going from 2017/12/22 to 2018/01/04. The last day is ever missing

Is there something wrong with the ics file I'm importing?

An example of my .ics is this:

```
BEGIN:VCALENDAR
VERSION:2.0
CALSCALE:GREGORIAN
METHOD:REQUEST
BEGIN:VEVENT
DTSTART;VALUE=DATE:20171227T000000Z
DTEND;VALUE=DATE:20180105T000000Z
DTSTAMP:20171130T132000Z
ORGANIZER:mailto:xxx@gmail.com
CREATED:20171130T132000Z
DESCRIPTION: HOLIDAYS
CREATED:20171130T132000Z
SEQUENCE:0
STATUS:ACCEPTED
SUMMARY:HOLIDAYS
END:VEVENT
END:VCALENDAR
```
For import i use this command:
`~# gcalcli import myfile.ics --calendar 'test_calendar'`

Thanks for your help

**Comment by dbarnett** [comment]
I think that's working as intended. Your event ended at midnight 01/05 meaning it has 0% overlap with the day of 01/05, so it lasts all day through 01/04 but doesn't cover the following day.

AFAICT the ICS format doesn't have explicit support for explicitly specifying "all day" events and it's slightly ambiguous how to handle cases like this, but especially when you're specifying a midnight datetime like `20180105T000000Z` it seems correct to me to say that doesn't represent an "all day event including all of 01/05". I did see you can specify a date without a time instead, like `20180105`, but that seems to work the same in practice...

LMK if there's some aspect I'm missing and it still seems wrong for whatever reason.
