### ISSUE TITLE
Set Calendar Colors Manually

### ISSUE THREAD

**Issue by BadDecisionsAlex** [insanum/gcalcli#333]
Hey is there a way to set the color used for each of my calendars manually?
Currently colors are set by read/write authorization/ownership. I would like to add a line to my irc like
--setcolor 'School Calendar' 'RED'
--setcolor 'Work Calendar' 'BLUE'
etc

I looked at the source and think I could edit things to add that functionality but I wanted to check and make sure that this was not already simple to do. I noticed there is an array that seems to map Calendars to colors using the _CalendarColor command which seemed like the place to start.

**Comment by jcrowgey** [comment]
I've updated the color handling in master recently.  I don't know if you want to review the code changes to see if there's something you'd like to modify to achieve your goals.

FWIW, I think it works to do something like

```sh
$ gcalcli --calendar=me@google.com#blue  --calendar=mywork@gmail.com#green calw
```

And of course you can set up that kind of stuff in a config file as well.  I don't know if that solves what you're trying to do with your IRC client or not.
