### ISSUE TITLE
weird letters instead of graphical calendar

### ISSUE THREAD

**Issue by arnauldb** [insanum/gcalcli#334]
Hello,

thank you for gcalcli, I use it in my terminal. I wanted to use conky to show it on my desktop.
I can get the agenda on my desktop but can't have the graphical calendar. I have weird signs instead (please see screenshot).

link edited...
http://i.imgur.com/Z5q1Hp5.png

I correctly added:

> ${execpi 300 gcalcli --conky calw 3}

Thank you for any help.

**Comment by Penaz91** [comment]
It could relate to #97, hopefully this helps

**Comment by arnauldb** [comment]
Thank you @Penaz91 , It's better now...instead of having ugly lines of characters I have something better but I still have these characters instead of lines...see screenshot: http://i.imgur.com/Ub32rxd.png

I don't understand how

**Comment by Penaz91** [comment]
Might be a stupid question but worth a try, what font are you using to display your conky?

**Comment by arnauldb** [comment]
hey, I got it right using the "--nolineart" option. Thank you @Penaz91 for the link  [#97](https://github.com/insanum/gcalcli/issues/97) that helped me find the solution...

see screenshot of my working calendar now: http://i.imgur.com/0W5ZaGB.png

**Comment by Penaz91** [comment]
That's good. Happy you got it worked out.

**Comment by arnauldb** [comment]
> my gcalcli completely refuses to work

Hope you will find a way to make it work.

**Comment by jcrowgey** [comment]
Closing this as dup since #97 tracks the work to add a unicode box drawing characters output as lineart instead of the vt100 escape sequences.
