### ISSUE TITLE
Certificate Verify Fails

### ISSUE THREAD

**Issue by Penaz91** [insanum/gcalcli#336]
Since February 27th, I'm having a lot of issues with Certificate Verification. Sometimes I manage to get the calendar data, but most of the time I get this traceback:

>Traceback (most recent call last):
>  File "/usr/lib/python-exec/python2.7/gcalcli", line 2500, in <module>
>    BowChickaWowWow()
>  File "/usr/lib/python-exec/python2.7/gcalcli", line 2382, in BowChickaWowWow
>    options=FLAGS)
>  File "/usr/lib/python-exec/python2.7/gcalcli", line 587, in __init__
>    self._GetCached()
>  File "/usr/lib/python-exec/python2.7/gcalcli", line 714, in _GetCached
>    self._CalService().calendarList().list())
>  File "/usr/lib/python-exec/python2.7/gcalcli", line 670, in _CalService
>    http=self._GoogleAuth())
>  File "/home/penaz/.local/lib64/python2.7/site-packages/oauth2client/util.py", line 132, in positional_wrapper
>    return wrapped(*args, **kwargs)
>  File "/home/penaz/.local/lib64/python2.7/site-packages/apiclient/discovery.py", line 192, in build
>    resp, content = http.request(requested_url)
>  File "/home/penaz/.local/lib64/python2.7/site-packages/oauth2client/util.py", line 132, in positional_wrapper
>    return wrapped(*args, **kwargs)
>  File "/home/penaz/.local/lib64/python2.7/site-packages/oauth2client/client.py", line 490, in new_request
>    redirections, connection_type)
>  File "/home/penaz/.local/lib64/python2.7/site-packages/httplib2/__init__.py", line 1570, in request
>    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
>  File "/home/penaz/.local/lib64/python2.7/site-packages/httplib2/__init__.py", line 1317, in _request
>    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
>  File "/home/penaz/.local/lib64/python2.7/site-packages/httplib2/__init__.py", line 1252, in >_conn_request
>    conn.connect()
>  File "/home/penaz/.local/lib64/python2.7/site-packages/httplib2/__init__.py", line 1044, in connect
>    raise SSLHandshakeError(e)
>httplib2.SSLHandshakeError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:661)

I reinstalled my ca-certificates, python, httplib2, google-api-python-client with no result. I tried downgrading too, but it didn't produce any result.
My clock is synced via NTP so time is not the problem (I verified it just to be safe, and it's right), I'm running:
- Gentoo Linux
- gcalcli v4.0.0_alpha3-r1 (from Portage, but also version 3.4.0 doesn't work)
- python-2.7.14-r1
- httplib2 0.10.3-r1
- google-api-python-client 1.6.5 (Tried also the stable version 1.6.2 with no result)
- oauth2-client 4.1.2

**Comment by Penaz91** [comment]
Seems like I found the issue, portage reported httplib2 0.10.3-r1, while it was running version 0.8 for some reason. Using pip2 install --upgrade --user httplib2 solved the issue.

**Comment by lemonkey** [comment]
I'm seeing this too from time to time and I have httplib2 (0.10.3) installed.
