### ISSUE TITLE
Set up CI

### ISSUE THREAD

**Issue by jcrowgey** [insanum/gcalcli#343]
Travis ci is free for open source projects

We should set up ci to run our tests.

**Comment by jcrowgey** [comment]
@insanum I think the files are all in place on master, can you go ahead and turn on travis-ci for this repo?

Cheers!

**Comment by insanum** [comment]
I enabled Travis against gcalcli.
https://travis-ci.org/insanum/gcalcli

**Comment by jcrowgey** [comment]
Thanks!
