### ISSUE TITLE
add not working with argparse

### ISSUE THREAD

**Issue by jcrowgey** [insanum/gcalcli#350]
On current master, add gripes that "must specify a single calendar" even when --calendar=me@gmail.com is specified.

Also: would be nice to prompt for calendar if its missing rather than erroring out.

**Comment by tresni** [comment]
Check your configuration file.  IF you have a `--calendar` entry there (instead of a `--defaultCalendar` entry), that woudl cause the error you are seeing.  The config file is additive to command line configuration, one does not replace the other.

**Comment by jcrowgey** [comment]
In my case, I have no config file.  I can look further into the issue.  But I'm running in a venv with no config in '~'.

**Comment by jcrowgey** [comment]
I found the issue, I wasn't being consistent about '.'s in my gmail address.  We should probably improve the error message, but I will close this issue.
