### ISSUE TITLE
add fails with AttributeError: 'Namespace' object has no attribute 'allday'

### ISSUE THREAD

**Issue by dieterdeyke** [insanum/gcalcli#351]
Executing 

PYTHONIOENCODING=utf_8 ./gcalcli.py --calendar 'Dieter Deyke' add --title 'Test Entry' --where '' --when 2018-06-16T10:00:00 --duration 60 --descr '' --reminder 0

fails with

Traceback (most recent call last):
  File "./gcalcli.py", line 2485, in <module>
    main()
  File "./gcalcli.py", line 2433, in main
    eStart, eEnd = GetTimeFromStr(FLAGS.when, FLAGS.duration, FLAGS.allday)
AttributeError: 'Namespace' object has no attribute 'allday'

**Comment by jcrowgey** [comment]
You're right!  thank you!  Fixed in b9faf7c9203d1408dd5e3689b2b8b11a9f38fb95
