### ISSUE TITLE
ImportError: No module named color_printer

### ISSUE THREAD

**Issue by dieterdeyke** [insanum/gcalcli#352]
Installing gcalcli from git into /usr/local/gcalcli and executing ./gcalcli/gcalcli.py results in

Traceback (most recent call last):
  File "./gcalcli/gcalcli.py", line 120, in <module>
    from gcalcli.color_printer import ColorPrinter, valid_color_name
  File "/usr/local/gcalcli/gcalcli/gcalcli.py", line 120, in <module>
    from gcalcli.color_printer import ColorPrinter, valid_color_name
ImportError: No module named color_printer

**Comment by jcrowgey** [comment]
Do you also have this issue when you pip install?

**Comment by dieterdeyke** [comment]
Joshua Crowgey <notifications@github.com> writes:

> Do you also have this issue when you pip install?

I never used pip, I just run it from a git clone. Are there more steps
to be done if just using git? If so, can I manual do them?

Thanks,
--
Dieter Deyke
mailto:dieter.deyke@gmail.com
Get my Gnupg key:
gpg --keyserver keys.gnupg.net --recv-keys B116EA20

**Comment by jcrowgey** [comment]
It should be as easy as:

```
$ git clone https://github.com/insanum/gcalcli
$ cd gcalcli
$ pip install .
```

Of course if you don't want to install in your system's libraries, you're encouraged to use a virtualenvironment.  Especially if you're doing git clone of master in this repo, as it's currently undergoing a bit of refactoring.

If you get a change to properly install gcalcli master and are still having errors, I'd love to know!

**Comment by dieterdeyke** [comment]
Joshua Crowgey <notifications@github.com> writes:

> It should be as easy as:
>
> $ git clone https://github.com/insanum/gcalcli
> $ cd gcalcli
> $ pip install .
>
> Of course if you don't want to install in your system's libraries, you're encouraged to use a virtualenvironment.
> Especially if you're doing git clone of master in this repo, as it's currently undergoing a bit of refactoring.
>
> If you get a change to properly install gcalcli master and are still having errors, I'd love to know!

Thanks for your reply. I tries your steps but still failed:

deyke@deyke2> cd tmp                                                          ~
deyke@deyke2>  git clone https://github.com/insanum/gcalcli               ~/tmp
Cloning into 'gcalcli'...
remote: Counting objects: 1223, done.
remote: Compressing objects: 100% (97/97), done.
remote: Total 1223 (delta 85), reused 129 (delta 59), pack-reused 1063
Receiving objects: 100% (1223/1223), 2.29 MiB | 25.00 KiB/s, done.
Resolving deltas: 100% (687/687), done.
deyke@deyke2> cd ./gcalcli                                                ~/tmp
deyke@deyke2> ll -a                                               ~/tmp/gcalcli
total 60
drwxr-xr-x 6 deyke deyke 4096 Jun 23 11:35 .
drwxr-xr-x 3 deyke deyke 4096 Jun 23 11:34 ..
-rw-r--r-- 1 deyke deyke 6850 Jun 23 11:35 ChangeLog
-rw-r--r-- 1 deyke deyke  208 Jun 23 11:35 .coveragerc
drwxr-xr-x 3 deyke deyke 4096 Jun 23 11:35 docs
drwxr-xr-x 2 deyke deyke 4096 Jun 23 11:35 gcalcli
drwxr-xr-x 8 deyke deyke 4096 Jun 23 11:35 .git
-rw-r--r-- 1 deyke deyke  103 Jun 23 11:35 .gitignore
-rw-r--r-- 1 deyke deyke   51 Jun 23 11:35 MANIFEST.in
lrwxrwxrwx 1 deyke deyke   14 Jun 23 11:35 README.md -> docs/README.md
-rw-r--r-- 1 deyke deyke   28 Jun 23 11:35 setup.cfg
-rw-r--r-- 1 deyke deyke 1527 Jun 23 11:35 setup.py
drwxr-xr-x 3 deyke deyke 4096 Jun 23 11:35 tests
-rw-r--r-- 1 deyke deyke  292 Jun 23 11:35 tox.ini
-rw-r--r-- 1 deyke deyke  129 Jun 23 11:35 .travis.yml
deyke@deyke2> pip install .                                       ~/tmp/gcalcli
Processing /home/deyke/tmp/gcalcli
Collecting google-api-python-client>=1.4 (from gcalcli==4.1.0)
  Downloading https://files.pythonhosted.org/packages/bd/40/bc3b4e7c7c65f9548024dde5c7bad60e0e078b2d2a0ee8c426a5639c2cc9/google_api_python_client-1.7.3-py2.py3-none-any.whl (55kB)
    100% |████████████████████████████████| 61kB 234kB/s
Collecting httplib2 (from gcalcli==4.1.0)
  Downloading https://files.pythonhosted.org/packages/fd/ce/aa4a385e3e9fd351737fd2b07edaa56e7a730448465aceda6b35086a0d9b/httplib2-0.11.3.tar.gz (215kB)
    100% |████████████████████████████████| 225kB 187kB/s
Collecting oauth2client (from gcalcli==4.1.0)
  Downloading https://files.pythonhosted.org/packages/82/d8/3eab58811282ac7271a081ba5c0d4b875ce786ca68ce43e2a62ade32e9a8/oauth2client-4.1.2-py2.py3-none-any.whl (99kB)
    100% |████████████████████████████████| 102kB 192kB/s
Collecting python-dateutil (from gcalcli==4.1.0)
  Downloading https://files.pythonhosted.org/packages/cf/f5/af2b09c957ace60dcfac112b669c45c8c97e32f94aa8b56da4c6d1682825/python_dateutil-2.7.3-py2.py3-none-any.whl (211kB)
    100% |████████████████████████████████| 215kB 138kB/s
Collecting six (from gcalcli==4.1.0)
  Downloading https://files.pythonhosted.org/packages/67/4b/141a581104b1f6397bfa78ac9d43d8ad29a7ca43ea90a2d863fe3056e86a/six-1.11.0-py2.py3-none-any.whl
Collecting uritemplate<4dev,>=3.0.0 (from google-api-python-client>=1.4->gcalcli==4.1.0)
  Downloading https://files.pythonhosted.org/packages/f6/25/66a49231b44409d7f07cfcf2506a8b070ce3c99fc47cc256bea833f24791/uritemplate-3.0.0-py2-none-any.whl
Collecting google-auth-httplib2>=0.0.3 (from google-api-python-client>=1.4->gcalcli==4.1.0)
  Downloading https://files.pythonhosted.org/packages/33/49/c814d6d438b823441552198f096fcd0377fd6c88714dbed34f1d3c8c4389/google_auth_httplib2-0.0.3-py2.py3-none-any.whl
Collecting google-auth>=1.4.1 (from google-api-python-client>=1.4->gcalcli==4.1.0)
  Downloading https://files.pythonhosted.org/packages/53/06/6e6d5bfa4d23ee40efd772d6b681a7afecd859a9176e564b8c329382370f/google_auth-1.5.0-py2.py3-none-any.whl (65kB)
    100% |████████████████████████████████| 71kB 203kB/s
Collecting pyasn1>=0.1.7 (from oauth2client->gcalcli==4.1.0)
  Downloading https://files.pythonhosted.org/packages/a0/70/2c27740f08e477499ce19eefe05dbcae6f19fdc49e9e82ce4768be0643b9/pyasn1-0.4.3-py2.py3-none-any.whl (72kB)
    100% |████████████████████████████████| 81kB 161kB/s
Collecting pyasn1-modules>=0.0.5 (from oauth2client->gcalcli==4.1.0)
  Downloading https://files.pythonhosted.org/packages/e9/51/bcd96bf6231d4b2cc5e023c511bee86637ba375c44a6f9d1b4b7ad1ce4b9/pyasn1_modules-0.2.1-py2.py3-none-any.whl (60kB)
    100% |████████████████████████████████| 61kB 162kB/s
Collecting rsa>=3.1.4 (from oauth2client->gcalcli==4.1.0)
  Downloading https://files.pythonhosted.org/packages/e1/ae/baedc9cb175552e95f3395c43055a6a5e125ae4d48a1d7a924baca83e92e/rsa-3.4.2-py2.py3-none-any.whl (46kB)
    100% |████████████████████████████████| 51kB 198kB/s
Collecting cachetools>=2.0.0 (from google-auth>=1.4.1->google-api-python-client>=1.4->gcalcli==4.1.0)
  Downloading https://files.pythonhosted.org/packages/0a/58/cbee863250b31d80f47401d04f34038db6766f95dea1cc909ea099c7e571/cachetools-2.1.0-py2.py3-none-any.whl
Building wheels for collected packages: httplib2
  Running setup.py bdist_wheel for httplib2 ... error
  Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-mAsD1Q/httplib2/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmpUsD26Bpip-wheel- --python-tag cp27:
  usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: -c --help [cmd1 cmd2 ...]
     or: -c --help-commands
     or: -c cmd --help

  error: invalid command 'bdist_wheel'

  ----------------------------------------
  Failed building wheel for httplib2
  Running setup.py clean for httplib2
Failed to build httplib2
Installing collected packages: httplib2, uritemplate, cachetools, six, pyasn1, rsa, pyasn1-modules, google-auth, google-auth-httplib2, google-api-python-client, oauth2client, python-dateutil, gcalcli
  Running setup.py install for httplib2 ... done
  Running setup.py install for gcalcli ... done
Successfully installed cachetools-2.1.0 gcalcli-4.1.0 google-api-python-client-1.7.3 google-auth-1.5.0 google-auth-httplib2-0.0.3 httplib2-0.11.3 oauth2client-4.1.2 pyasn1-0.4.3 pyasn1-modules-0.2.1 python-dateutil-2.7.3 rsa-3.4.2 six-1.11.0 uritemplate-3.0.0
deyke@deyke2> ./gcalcli/gcalcli.py                                ~/tmp/gcalcli
Traceback (most recent call last):
  File "./gcalcli/gcalcli.py", line 108, in <module>
    from gcalcli import utils
  File "/home/deyke/tmp/gcalcli/gcalcli/gcalcli.py", line 108, in <module>
    from gcalcli import utils
ImportError: cannot import name utils
[1] deyke@deyke2>                                                 ~/tmp/gcalcli

--
Dieter Deyke
mailto:dieter.deyke@gmail.com
Get my Gnupg key:
gpg --keyserver keys.gnupg.net --recv-keys B116EA20

**Comment by jcrowgey** [comment]
So, I think that if you want to pip install into your system's python, you'll probably have to sudo (or the equivalent on your OS).  It's odd that the result would be 'invalid command' from setuptools, so I'm curious which version of python you're running.

You might just create a virtualenv and test pip install there.  

Alternatively, you might try 

```
python setup.py install
```

(as suggested in the README), I still think you'll need elevated privileges if you're installing to a system location.  I believe that you can use setuptools with --prefix to install to a specific directory, but you probably need to look up the specific flag, it may not be `--prefix`

In any case, once you install it, you'll find a man page and a command line tool `gcalcli`, just like in earlier versions.  Ie, you don't need to call gcalcli/gcalcli.py, you can just use the command line tool on your $PATH.

Let me know if you're able to install.

**Comment by dieterdeyke** [comment]
Joshua Crowgey <notifications@github.com> writes:

> So, I think that if you want to pip install into your system's python, you'll probably have to sudo (or the equivalent
> on your OS). It's odd that the result would be 'invalid command' from setuptools, so I'm curious which version of python
> you're running.
>
> You might just create a virtualenv and test pip install there.
>
> Alternatively, you might try
>
> python setup.py install
>
> (as suggested in the README), I still think you'll need elevated privileges if you're installing to a system location. I
> believe that you can use setuptools with --prefix to install to a specific directory, but you probably need to look up
> the specific flag, it may not be --prefix
>
> In any case, once you install it, you'll find a man page and a command line tool gcalcli, just like in earlier versions.
> Ie, you don't need to call gcalcli/gcalcli.py, you can just use the command line tool on your $PATH.
>
> Let me know if you're able to install.

My system is Debian testing, running python 2.7.15. Since debian is
using apt for all package management, I do not like the idea of using
pip or any other additional package management system, or installing
anything into system locations. But finally I got successful doing

python setup.py install --prefix ...

So thank you again for your help, and please close the issue.
-- 
Dieter Deyke
mailto:dieter.deyke@gmail.com
Get my Gnupg key:
gpg --keyserver keys.gnupg.net --recv-keys B116EA20

**Comment by jcrowgey** [comment]
Great!

And, fwiw, gcacli is in debian already so you can just apt-get install debian (and you'll get a more stable version than what's going on in master right now).

If you want to help test my changes in master, you can use a virtual environment.  On debian, you can apt-get installl python-venv and then you'll be able to create a virtual envionment with

```
python -m venv venv
```
