### ISSUE TITLE
Modernize oauth2client requirements

### ISSUE THREAD

**Issue by jcrowgey** [insanum/gcalcli#353]
I'm pretty sure that the current oauth2client and possibly other stuff related to communication with google which we're using is pretty outdated.  In some cases, the apis have changes and we have to either pin to deprecated libraries or support the new ones.  I think we should more to support the newer ones.

**Comment by shreeramsenthi** [comment]
To add onto this, oauth2client is [officially deprecated](https://github.com/google/oauth2client). The team recommends switching to google-auth and oauthlib.

**Comment by dbarnett** [comment]
Fixed by #683.
