### ISSUE TITLE
error in master: AttributeError: 'dict' object has no attribute 'logging_level'

### ISSUE THREAD

**Issue by nealmcb** [insanum/gcalcli#355]
When I run 

     gcalcli search test
I get

     AttributeError: 'dict' object has no attribute 'logging_level'

I just (re)installed gcalcli from the current master (2867605).
`gcalcli list` successfully lists several calendars for me.
If I checkout `v4.0.0a4` it works fine.
So there seems to be a regression in master.

**Comment by jcrowgey** [comment]
FWIW, full tracebacks are more helpful.  :)

I was able to repro this by removing my ~/.gcalcli_oauth file.

This is fixed in  c87e6f5

**Comment by nealmcb** [comment]
Sorry - I indeed should have given a better error report with traceback!
Thanks.
