### ISSUE TITLE
pip package version is too old

### ISSUE THREAD

**Issue by amitech** [insanum/gcalcli#359]
Hi,

pip package version is too old i.e. 3.4.0 (released in 2016). It will be good if can be updated on pip hosted package manager.
P.S: Ubuntu package manager is showing version 3.3.0. So it will be good to update it there too. 

![screenshot from 2018-07-10 20-41-02](https://user-images.githubusercontent.com/7789327/42519525-de432398-8481-11e8-8220-c343c91e2866.png)

**Comment by jcrowgey** [comment]
I'm relatively new at helping to maintain this project so I don't know a lot about the history.  I *believe* that v4 is still considered alpha, so it may be that 3.6 in pypi is actually the latest stable.   I don't know if there's been any tradition of pushing alpha builds to pypi or if pulling from this repo is the preferred way for testers pre-release.

Ubuntu packaging is, I think, downstream from debian, which is also on 3.4.0-1.  I'll leave this issue open in case someone else knows whether we should be pushing alpha builds to pypi under some namespace.

**Comment by jcrowgey** [comment]
No one has updated this.  I'm currently assuming, then, that we just release alpha builds here as tags.

**Comment by jcrowgey** [comment]
I've reopened this because I'd like to revisit it soon.

**Comment by tresni** [comment]
The alpha builds can be installed via pip, you just have to point to the specific version you want:

`pip install gcalcli==4.0.0a4`

**Comment by jcrowgey** [comment]
pypi is now updated to the latest release
