### ISSUE TITLE
--nostarted causes the start time to shift

### ISSUE THREAD

**Issue by jcrowgey** [insanum/gcalcli#362]
Found and in the report for #361, this was confirmed in 3.4 and in current master (4.0.4alpha).

Ran this at approx Thu Aug  2 20:28:15 PDT 2018
```
(venv) ~/src/gcalcli$ gcalcli agenda

Thu Aug 02           all day test

(venv) ~/src/gcalcli$ gcalcli agenda --nostarted

Tue Aug 07   2:00pm  Test meeting
```

**Comment by jcrowgey** [comment]
In `_ParseStartEnd`, which called by `AgendaQuery` (and I'm sure many other functions), we see:

```python
        if not startText:                                                                                
            start = self.now if self.options['ignore_started'] else None 
```

So, that seems like a bug to me, especially because I find a specific filter _IterateEvents

```python
        for event in eventList:                                                                          
            if self.options['ignore_started'] and (event['s'] < self.now):                               
                continue
```

The only other spots in the code which refer to `'ignore_started'` are in the `_tsv` function.  This may mean that other functionality is relying on the moving of the start date.

Since we're on alpha in master, I'm going to write a test or two for this and then check in a bug fix this weekend.  I'm going to take the strategy of just removing the start time shift unless someone else knows a reason I shouldn't.

**Comment by slgobinath** [comment]
Thank you very much for such an awesome tool and for your immediate response to the problem.

FYI: Ubuntu 18.04 official repository contains [gcalcli 4.0.0~a3-1](https://launchpad.net/ubuntu/bionic/+source/gcalcli) which is the version caused to the problem mentioned in https://github.com/linuxmint/cinnamon-spices-desklets/issues/330.

**Comment by jcrowgey** [comment]
@slgobinath I hope I didn't confuse anyone.  The issue reported in #361 is still a thing.  While investigating #361 I ran across this bug (#362), which is now fixed.  I think your comment might be helpful in the thread about #361, unless I'm missing something.
