### ISSUE TITLE
agenda keyerror: 'calendar'

### ISSUE THREAD

**Issue by ryufrvr** [insanum/gcalcli#369]
![111](https://user-images.githubusercontent.com/31278954/44538446-dd4d6980-a6f0-11e8-900f-b44f977bf569.png)

**Comment by jcrowgey** [comment]
Is this on 3a6399b928585b87736ca30b4edab7532fe64129?

If not can you git pull master?

**Comment by ryufrvr** [comment]
big thanks! install from source and all work!
