### ISSUE TITLE
How to get details of remainders?

### ISSUE THREAD

**Issue by akashks1998** [insanum/gcalcli#373]
I am trying `gcalcli agenda --detail_reminders` but I am only getting the remainders not their details. Also the date of the remainders is wrong.
![2018-08-31-203318_1920x1080_scrot](https://user-images.githubusercontent.com/25325900/44920479-a8c75680-ad5d-11e8-96b2-4d311d172f25.png)

**Comment by jcrowgey** [comment]
As with your other issue, I am not able to reproduce on the current master.  The syntax of the detail stuff in a bit in flux.  Here's my experience using current master on python3.5

```shell
(venv) jcrowgey@tsuga:~/src/gcalcli$ gcalcli  add
Title: test 
Location: anywhere
When: tuesday
Duration (minutes): 30
Description: a test event
Enter a valid reminder or '.' to end: 5m sms
Enter a valid reminder or '.' to end: 10m email
Enter a valid reminder or '.' to end: .
(venv) jcrowgey@tsuga:~/src/gcalcli$ gcalcli agenda --details=reminders

Mon Sep 03           Labor Day

Tue Sep 04  12:00am  test
                     Reminder: sms 5 minutes
                     Reminder: email 10 minutes
```

So I think I need a bit more detail in order to be of service to you.
