### ISSUE TITLE
raw_input() is input() in Python 3 

### ISSUE THREAD

**Issue by bgschaid** [insanum/gcalcli#378]
I installed v4.0.0a3 through the package manager of Ubuntu

When I try to use `add --prompt` I get the error message
```
 Traceback (most recent call last):
  File "/usr/bin/gcalcli", line 2500, in <module>
    BowChickaWowWow()
  File "/usr/bin/gcalcli", line 2425, in BowChickaWowWow
    FLAGS.title = raw_input()
NameError: name 'raw_input' is not defined
```

Reason seems to be that it is installed as a Python3-script and in Python3 what used to be `raw_input()` is now just `input()`

I guess checking for Python 3 and defining a wrapper function would fix this

**Comment by jcrowgey** [comment]
This is fixed in the current version.  We're now using six consistently for py2/py3 compatibility.
