### ISSUE TITLE
adding crontab doesn't work

### ISSUE THREAD

**Issue by kurokirasama** [insanum/gcalcli#380]
I have this added to my crontab:

```
*/10 * * * * /usr/bin/gcalcli remind 30 '/usr/bin/notify-send -i appointment-soon -a /usr/bin/gcalcli %s --military'
```
But i got this error:

```
/bin/bash: -c: línea 0: EOF inesperado mientras se buscaba un «'» coincidente
/bin/bash: -c: línea 1: error sintáctico: no se esperaba el final del archivo

```

Which in English it should be something like:

```
/bin/bash: -c: line 0: EOF unexpected while searching a matching «'»
/bin/bash: -c: line 1: syntactic error : not expected end of file
```

**Comment by jcrowgey** [comment]
Are you missing an EOF in your crontab file?  FWIW, this doesn't look like a gcalcli error.

Also, I'm pretty sure you don't want --militiary as an option to notify-send, so that ought to be outside your quoted command argument.
