### ISSUE TITLE
Unify param names

### ISSUE THREAD

**Issue by n1-cz** [insanum/gcalcli#382]
1st of all - amazing app - thank you

I have a suggestion about params. Some are camelCase, some are under_scored, some are dash-ed. I recommend to tuse standard lowercase-dashed naming.

-client_id -> --cliend-id,
--client_secret -> --client-secret
--configFolder -> --config-folder

Also "long params" should always start with 2 dashes (ulinke short ones where standard is only one dash).

I'm willing to help if you are interested.

**Comment by jcrowgey** [comment]
Yes please!

**Comment by hammerheadlemon** [comment]
Agree that this is the correct way forward for any new or revised code. De-Javafying (is that a word?) needs to commence! I'm happy to look at doing this, although it's a fairly large user API change so would want full agreement with @jcrowgey first!

**Comment by n1-cz** [comment]
Im Op and Im sooo busy. Damn. Nevertheless..

Do it!

**Comment by jcrowgey** [comment]
@hammerheadlemon In #411 you said:

> Yesterday I did some work on something similar in pursuit of #382, this time using a decorator. That problem is a lot simpler - we're just masking the old optionals (with the underscore) and not showing them in --help, and adding in new ones with the correct semantics - however this issue here is always going to be a lot more difficult. (By the way, I'd be happy to do more work #382, but obviously I'm going to wait until this is resolved in master first :-)

Can you check in that work somewhere when you have a chance.  Even if it's still WIP, I'd love to take a look at what you've got.  I'll probably make some effort at resolving #382 in the next couple of days.

**Comment by hammerheadlemon** [comment]
@jcrowgey PR #412 pushed for you to have a look at. Needs work, testing and refactoring, but basic idea there. Let me know what you think.
