### ISSUE TITLE
gcalci conky not working anymore for me

### ISSUE THREAD

**Issue by arnauldb** [insanum/gcalcli#386]
Hello,

I've been using gcalcli for a while and added my google calendar on my desktop. It worked fine and gcalcli is still working fine. However the calendar in conky stopped showing on my desktop.

I have this instead (screenshot): 
https://i.imgur.com/Vl4pn2V.png

Thank you for any help.

**Comment by jcrowgey** [comment]
Your symptom indicates that your login token is missing or expired.

What happens if you follow the instructions shown on that screenshot?

**Comment by arnauldb** [comment]
> What happens if you follow the instructions shown on that screenshot?
Well, I'd like to select the link showed instead of the calendar, but how to select it?

**Comment by jcrowgey** [comment]
I'm not sure that I follow your question.  In your .conkyrc, or wherever your conky config is, there's a gcalcli command.  You should be able to run that exact command and get the same message if for some reason you can't copy-paste from the output of conky.  Or, like, type carefully?

**Comment by arnauldb** [comment]
> You should be able to run that exact command and get the same message if for some reason you can't copy-paste from the output of conky

Thanks, I just did that, running `gcalcli --conky agenda` in my terminal but the link is a 404 page with: 

> 401. That’s an error.
> 
> Error: invalid_client
> 
> The OAuth client was not found.
> 
> Request Details
> scope=https://www.googleapis.com/auth/calendar https://www.googleapis.com/auth/urlshortener
> redirect_uri=urn:ietf:wg:oauth:2.0:oob
> response_type=code
> client_id='51183518870-l8iai37kt16rfslhrrl6jqi6ie7e8u3c.apps.googleusercontent.com'
> access_type=offline
> That’s all we know.
