### ISSUE TITLE
Missing parentheses in call to print. Python 3 error?

### ISSUE THREAD

**Issue by jessebett** [insanum/gcalcli#388]
I installed gcalcli as instructed through pip but am getting errors probably due to python 3 print differences:

```
gcalcli
  File "/Users/jesse/anaconda3/bin/gcalcli", line 199
    print "ERROR: Missing module - %s" % e.args[0]
                                     ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(int "ERROR: Missing module - %s" % e.args[0])?
```

**Comment by sebw** [comment]
Getting the same error after upgrading to Fedora 29.

**Comment by jcrowgey** [comment]
Hi guys,

Your distros need to upgrade their gcalcli if they want to run against python3.  Current master is compatible with py2 and py3 (see the use of six).

**Comment by sebw** [comment]
Fixed by changing the shebang back to python2.
