### ISSUE TITLE
OAuth2 semms no work on text only machine.

### ISSUE THREAD

**Issue by miky2k** [insanum/gcalcli#389]
II have a text only console , when i start gcalcli it start lynx to try to obtain google token,
but google authentication cannot be used on text only browser (ask to type number in image).

**Comment by jcrowgey** [comment]
I don't know how we can resolve this, unless Google provides some other method to get the auth token.

What would you like gcalcli to do in this scenario?

**Comment by miky2k** [comment]
I activate gcalcli on a machine with firefox and coped .gcalcli_oauth to root home.

I need to add calendar events from linux crontab script.

**Comment by lasers** [comment]
If you start with `gcalcli --noauth_local_webserver`, you can copy and paste a link to a different browser. Sign in there and it'll give you 50char~ token to copy and paste it back into the terminal.
```
$ gcalcli --noauth_local_webserver list

Go to the following link in your browser:

    https://accounts.google.com/o/oauth2/v2/auth?client_id=xxxxxxxxxxxx.apps.goo-
    gleusercontent.com&redirect_uri=...

Enter verification code: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
Authentication successful.
```
I tried `lynx`, but I think Google asked for captcha or something. Hard to tell and/or navigate.

**Comment by joydashy** [comment]
This was helpful! Should probably be added to: https://pypi.org/project/gcalcli/
