### ISSUE TITLE
Add installation from homebrew

### ISSUE THREAD

**Issue by wildeyes** [insanum/gcalcli#394]
Add a way to install this package directly from homebrew (for macOS)

**Comment by jcrowgey** [comment]
I don't have any use for this (or interest).  But I believe that (at least one of) the original authors may use the macOS.  In the meantime, can't you use pip on a mac?

**Comment by wildeyes** [comment]
It's an open feature request for who's willing to implement.

Mostly it's for me :)

**Comment by audioboxer217** [comment]
I'd be interested in this as well.  Pip does work for now, but I prefer to manage apps through homebrew as much as possible and keep my Python envs clean.

**Comment by jcrowgey** [comment]
I think that homebrew is some sort of package manager for mac OS.  I'm happy to have gcalcli in as many package managers as possible--that's fine.  But from what I can tell, this issue belongs downstream from here.  I can keep it open if mac OS users want to track status here, but I don't think there's actually any work to be done in this repo, is there?

**Comment by sebasrp** [comment]
FYI, working on the homebrew formula: https://github.com/Homebrew/homebrew-core/pull/62935

Once merged, I will update the installation doc to reflect the additional installation method.
