### ISSUE TITLE
--lineart options not valid

### ISSUE THREAD

**Issue by stevensonmt** [insanum/gcalcli#395]
When running `gcalcli agenda --lineart=fancy` (or `unicode` or `ascii`) if I see the error 
>The following options are either no longer valid globally or just plain invalid:
>  --lineart=fancy

In the terminal this is meaningless b/c it still displays legibly. In conky, however it makes it impossible for me to get a legible agenda.

`gcalcli --version -> gcalcli v4.0.0a4 (Eric Davis, Brian Hartvigsen)`
Manjaro Linux installed by AUR.

**Comment by jcrowgey** [comment]
Your experiencing the fact that the order of arguments and options matters.  `--lineart` is a global option, but you've written it as it it were an option for `agenda`.  To fix your specific issue, you just need to change your invocation:

```shell
$ . venv/bin/activate
(venv) $ gcalcli agenda --lineart=fancy
The following options are either no longer valid globally or just plain invalid:
  --lineart=fancy
^CSignal caught, bye!
(venv) j$ gcalcli --lineart=fancy agenda

Mon Dec 31           New Year's Eve

Tue Jan 01           New Year's Day
```

More broadly, we ought to provide a better error message, as detailed in #347.
