### ISSUE TITLE
next n days agenda

### ISSUE THREAD

**Issue by kaustabpal** [insanum/gcalcli#396]
I want to display the agenda for the next 10 days on my desktop using Conky. Can you please tell me what would be the command to do so. Thank you and keep up the good work. :)

**Comment by hammerheadlemon** [comment]
In bash, a command such as:

`gcalcli agenda today $(python -c "from datetime import date;from datetime import timedelta;print(date.today() + timedelta(10))")`

gets the output you require, so I'm guessing maybe this in your Conky config:

`${execpi 300 gcalcli agenda today $(python -c "from datetime import date;from datetime import timedelta;print(date.today() + timedelta(10))")`

**Comment by lasers** [comment]
Alternative / shorter end date: `date -d "+10 days" "+%F"`

**Comment by hammerheadlemon** [comment]
@lasers that's much nicer.

**Comment by jcrowgey** [comment]
@lasers Works as long as you have GNU date.  If you've got busybox date (or possibly other date implementations), you don't get the fancy +N days stuff.  ;)

**Comment by lasers** [comment]
```bash
date -d "@$((`date +%s` + 86400 * 10))" +%F  # Document this to help others. :-) 
```

**Comment by hammerheadlemon** [comment]
@lasers Where is that documented? I had no idea...

**Comment by lasers** [comment]
I knew about `-d` for some years. I googled to find `busybox date` version. 

I don't see anything in `man date` about `@` other than this example.
```
Convert seconds since the epoch (1970-01-01 UTC) to a date
      $ date --date='@2147483647'
```

**Comment by Geethree** [comment]
I've been aliasing
```sh
function agenda() {
  re='^[0-9]+$'
  if [[ "$1" =~ $re ]] ; then
    gcalcli agenda $(date -u +"%Y%m%d") $(date -u +"%Y%m%d" -d "+$1 day") --detail_length --detail_location
  else
    gcalcli agenda --detail_length --detail_location
  fi
}
```

**Comment by jcrowgey** [comment]
@geethree I think that's going to break when you upgrade.  The details now go as an arg to `--detail`:

```shell
$ gcalcli agenda --help
[snip]
optional arguments:
  -h, --help            show this help message and exit
  --details {all,calendar,location,length,reminders,description,longurl,shorturl,url,attendees,email,attachments}
                        Which parts to display, can be: all, calendar,
                        location, length, reminders, description, longurl,
                        shorturl, url, attendees, email, attachments
```

**Comment by lasers** [comment]
Can we close this now?

```
# conky.conf
...
${execpi 600 gcalcli --conky agenda $(date -d "+10 days" +%F)}
${execpi 600 gcalcli --conky agenda $(date -d "@$((`date +%s` + 86400 * 10))" +%F)}
]]
```
