### ISSUE TITLE
No input validation for gcalcli add

### ISSUE THREAD

**Issue by hammerheadlemon** [insanum/gcalcli#399]
When adding an event using a bare `gcalcli add` command, there is no validation to guard against erroneous input (ints where strings expected, blanks, etc) during the process requesting event details from the user (using `input()`). Python exceptions of various sorts are not being handled and bubble up to the user.

A simple line-by-line validation, which kicks out an erroneous entry with a friendly message to the user pointing out the type of data expected, and then waits for it again, would be a good idea here, rather than waiting for all the data to be input and then validated. The user can always Ctrl-C out if necessary.

I can't find a current issue covering this so raising it here - please correct me if I'm wrong.

**Comment by hammerheadlemon** [comment]
@jcrowgey - What are your views on gaining another dependency for this project? I've been considering [prompt_toolkit](https://pypi.org/project/prompt_toolkit/), which does offer some nice validation out of the box. It would also pave the way for a more sophisticated/user-friendly UI should the project to go down that route. Not essential, but thought I'd ask. Am working on a PR. Happy to make the current implementation more robust without the new dependency.

**Comment by jcrowgey** [comment]
As someone who has suffered from python dependency hell in the past, I'm wary about adding dependencies without looking into what they require (and so forth).  I'm not ruling this out, but I won't be able to carry out that investigation right away because of time constraints.

**Comment by hammerheadlemon** [comment]
Ok - will do something based on current `input()`-based implementation. Thanks.

**Comment by jcrowgey** [comment]
I believe this was resolved in PR #402
