### ISSUE TITLE
NameError: name 'raw_input' is not defined

### ISSUE THREAD

**Issue by gmparker2000** [insanum/gcalcli#400]
When I execute:
gcalcli --calendar "Work Calendar" delete "Work meeting"

I get this error:
NameError: name 'raw_input' is not defined

My python version is:
Python 3.7.1 (default, Oct 22 2018, 10:41:28) 
[GCC 8.2.1 20180831] on linux

**Comment by hammerheadlemon** [comment]
Which version of `gcalcli` are you using? (`gcalcli --version`)

**Comment by jcrowgey** [comment]
We maybe need to put this in some sort of FAQ.  More and more people are running old gcalcli, which wasn't fully python3 compatible, against py3k.  @gmparker2000: the solution is to upgrade your gcalcli to the lastest, which uses six to service py27 and above.

**Comment by gmparker2000** [comment]
I'm running 4.0.0a4-1.  Is that not the latest?

**Comment by jcrowgey** [comment]
The lastest tagged number is v4.0.0a5, however, the actual latest is just pulling master from this repo.

I'm not totally sure which version tag this change was under, but the fix happened in this commit be031716 which was merged on 12 June 2018

**Comment by gmparker2000** [comment]
Pulled the latest and everything works - thanks!
