### ISSUE TITLE
How to use method Events: list to get events with specified created time or update time with google-calendar-api?

### ISSUE THREAD

**Issue by dapsjj** [insanum/gcalcli#407]
I use method Events: list of google-calendar-api to get events on the specified calendar at this [link](https://developers.google.com/calendar/v3/reference/events/list).

I found these parameters：

> calendarId,iCalUID,maxAttendees,maxResults,orderBy,pageToken,privateExtendedProperty,q,sharedExtendedProperty,showDeleted,showHiddenInvitations,singleEvents,syncToken,timeMax,timeMin,timeZone,updatedMin

But when I use updatedMin='2019-01-16T16:00:00+09:00',I can only get data that was created or updated later than this time.

In fact,I want to get created time or updated time of events  between '2019-01-16T00:00:00+09:00' and '2019-01-16T23:59:59+09:00'.

What should I do?

**Comment by hammerheadlemon** [comment]
Use `updatedMin` with the bottom boundary and retrieve the data from that date until now, and then use another query to get from the upper bound until now, and use your program code to get the difference.

Best place for help I would say would be here: https://stackoverflow.com/questions/tagged/google-apis-explorer.

**Comment by dapsjj** [comment]
@hammerheadlemon 
Sir,I asked a question in this [link](https://stackoverflow.com/questions/54337619/how-to-use-method-events-list-to-get-events-with-specified-created-time-or-upda).

I think I can use `updatedMin`  to do what I want.
For example, when I use updatedMin='2019-01-16T16:00:00+09:00',I can only get data that was created or updated later than this time.

In the response,I remove the events data over `'2019-01-16T23:59:59+09:00'`.

Then I can  get created time or updated time of events between '2019-01-16T00:00:00+09:00' and '2019-01-16T23:59:59+09:00'.

Am I right?
