### ISSUE TITLE
gcalcli add gives error message 'must specify a single calendar'

### ISSUE THREAD

**Issue by vegarab** [insanum/gcalcli#408]
I have checked out the solutions to #220 and #223, but none worked.

Using the example from the readme:
```
gcalcli --calendar 'Aktiviteter'
              --title 'Analysis of Algorithms Final'
              --where UCI
              --when '12/14/2019 10:00'
              --duration 60
              --description 'It is going to be hard!'
              --reminder 30 add
```
yields the messsage. Although "Aktiviteter" is a calendar. 

This is my `gcalcli list` output:
``` 
 Access  Title
 ------  -----
 owner  Aktiviteter
 reader  Contacts
```

and my `~.gcalcirc` has the following entry:
```
--defaultCalendar=Aktiviteter
```

**Comment by jcrowgey** [comment]
We desperately need better help messages now that the argument parsing is sensitive to global options vs command specific options, so I assume that's what you're dealing with.  Can you tell us what version you're running?  Also, in your example, there is no subcommand given,  I assume you should have `add` in there somewhere (right after that `--calendar 'Aktiviteter'` is the right spot, iirc).

**Comment by hammerheadlemon** [comment]
@vegarab - and are you able to update the issue with message you received? I think you mistakenly omitted it from your message. Thanks.

@jcrowgey - a re-write of the docs/man page for 4.0? I think it's sorely needed. Happy to contribute to that.

**Comment by vegarab** [comment]
Yes, I mistakenly omitted "add" from the command - added it back in.
I'm running gcalcli 4.0

**Comment by jcrowgey** [comment]
@vegarab I believe that putting the `--calendar` switch before `add` and everything else afterward should solve your issue.  I hope to eventually provide better feedback (see the feedback from `git` and `rustc` for inspiration).

**Comment by vegarab** [comment]
@jcrowgey that fixed the issue... but it's not very intuitive that the command has to come after `--calendar` but before all other arguments. Sounds like the implementation here could be improved.

**Comment by jcrowgey** [comment]
You are correct.  The logical basis of the current behavior is that switches which apply to many subcommands are implemented as switches on `gcalcli` whereas the switches such as `--where`, `--when`, etc which are only appropriate for adding events are switches on `add`.  switches follow the command they are appropriate for.  I agree that we need better documentation or prompts.
