### ISSUE TITLE
release gcalcli

### ISSUE THREAD

**Issue by jcrowgey** [insanum/gcalcli#409]
After some discussion with the original authors, I've decided to do a release very soon as 4.0.0, even though we haven't finished all of the items for that milestone.  There are a number of reasons for this, the principle one is that debian is going into a freeze so it's a good time to get bug-fixes that we've patched in master out to the distros downstream.

If anyone want to help out over the next few days, I especially want to get the documentation issues cleared up:

- [x] #363
- [x] #371
- [x] #347 

It may also be a good time to try to address #382.

- [x] #382 

Beyond those items, which I think are really mainly housekeeping, we can push out 4.0.0 as python3 compatible which is a major achievement in itself.  Then, the other items which we hoped to do for 4.0.0 can be slated for bugfix releases under 4.0.x.

If anyone has cycles to work on this housekeeping stuff, please chime in here to coordinate.

Thanks in advance and happy hacking!

(Retroactively, we'll also address #360 as well.)

**Comment by hammerheadlemon** [comment]
Totally agree - Debian deadline is probably around early to mid Feb, so not long, and I think 4.0 should definitely target that.

Made some comments on #405 re using the projects feature - just a suggestion. I know it's all additional time... :+1: 

Happy to look at these issues and fix stuff where I can.

**Comment by jcrowgey** [comment]
I'm going to pick up #363 now.

**Comment by jcrowgey** [comment]
Hooray, 4.0.0 tagged and released to pypi (and then 4.0.1 almost immediately thereafter: i screwed up the long_description because I didn't have pypanadoc installed...so 4.0.1 only had package metadata changes).

Thank you to everyone who contributed to this release!  I hope everyone will try out the new code by pulling the tag from git (or from pypi).

**Comment by hammerheadlemon** [comment]
Congratulations! Apologies I've gone quite over the last week or so - been really busy in the "real" world, and likely to be the same for the next seven days or so, but looking forward to cracking on with bug fixes, etc beyond that.
