### ISSUE TITLE
Question: View event content?

### ISSUE THREAD

**Issue by Geethree** [insanum/gcalcli#415]
gcalcli is.. awesome! I'm probably missing something right in front of me, but how does one view the details for an event? Like location, description, invitees, etc...?

**Comment by hammerheadlemon** [comment]
Depends upon your version possibly, but in current master and probably latest release, add the `--details all` flag. Works for `agenda`, `search` and `edit` commands as far as I am aware. Use `--details location`, `--details description`, etc individually if want a partial view.

**Comment by Geethree** [comment]
Yes. Right in front of my face, I was missing the detail flags. Cheers.

**Comment by thapakazi** [comment]
treasures of life time... :heart_eyes:
