### ISSUE TITLE
how to set this up?

### ISSUE THREAD

**Issue by dirtbag** [insanum/gcalcli#426]

**Comment by dirtbag** [comment]
the instructions say:
OAuth2 is used for authenticating with your Google account. The resulting token is placed in the ~/.gcalcli_oauth file. When you first start gcalcli the authentication process will proceed. Simply follow the instructions.

but when I run it, I get 
[jason@badman ~]$ gcalcli
usage: gcalcli [-h] [--auth_host_name AUTH_HOST_NAME]
               [--noauth_local_webserver]
               [--auth_host_port [AUTH_HOST_PORT [AUTH_HOST_PORT ...]]]
               [--logging_level {DEBUG,INFO,WARNING,ERROR,CRITICAL}]
               [--version] [--client-id CLIENT_ID]
               [--client-secret CLIENT_SECRET] [--config-folder CONFIG_FOLDER]
               [--noincluderc] [--calendar CALENDAR]
               [--default-calendar DEFAULTCALENDAR] [--locale LOCALE]
               [--refresh] [--nocache] [--conky] [--nocolor]
               [--lineart {fancy,unicode,ascii}]
               {list,search,edit,delete,agenda,calw,calm,quick,add,import,remind}
               ...
gcalcli: error: the following arguments are required: command
[jason@badman ~]$ 

???
-db

**Comment by jcrowgey** [comment]
You should use one of the commands, see the man page for examples.

Available commands are listed in that output:

```
{list,search,edit,delete,agenda,calw,calm,quick,add,import,remind}
```
