### ISSUE TITLE
Just some help required. 

### ISSUE THREAD

**Issue by Stever88** [insanum/gcalcli#431]

**Comment by Stever88** [comment]
I am new to this but love it. I'm using it with Conky to display my agenda on the desktop. I would like it to also display todays day and date, but I don't have a clue. Thanks for any help.

**Comment by jcrowgey** [comment]
For today's date, you might use the `date` command.  In any case, it seems that your question is more about how to use conky than about how to use gcalcli.  Good luck!

**Comment by Stever88** [comment]
Ahh... I see. Seems as if I was looking at it the wrong way. conky just being the tool to display my calendar on the desktop through gcalcli. I assumed I could access the day and date through the calendar i.e. gcalcli. Sorry.
