### ISSUE TITLE
24 hour time (--military not working in .gcalclirc)

### ISSUE THREAD

**Issue by Habmala** [insanum/gcalcli#434]
Hi, I'm looking to use 24 hour time. I saw another issue looking for the same thing where it was suggested to use --military but I can't seem to get it to work. As mentioned in that issue changing to my local locale just removes the am/pm but doesn't change the way the time is shown.

```
habmala@Damian - 19:09 ~ $ gcalcli --version
gcalcli v4.0.4 (Eric Davis, Brian Hartvigsen, Joshua Crowgey)
habmala@Damian - 19:09 ~ $ gcalcli --military agenda
usage: gcalcli [-h] [--client-id CLIENT_ID] [--client-secret CLIENT_SECRET]
               [--config-folder CONFIG_FOLDER] [--noincluderc]
               [--calendar CALENDAR] [--default-calendar DEFAULTCALENDAR]
               [--locale LOCALE] [--refresh] [--nocache] [--conky] [--nocolor]
               [--lineart {fancy,unicode,ascii}]
gcalcli: error: unrecognized arguments: --military
```

**Comment by Habmala** [comment]
Hmm, my bad, this seems to only be partially true. Apparently --military can not be an option for gcalcli directly, but needs to be an option for the subcommand (agenda in this example) so gcalcli agenda --military does work.

But I still cant find how to put this in my .gcalclirc file. When trying to I get the same error as above.

```
habmala@Damian - 19:38 ~ $ cat .gcalclirc 
--military
--config-folder=~/.config/gcalcli/
```
And changing the order of those two options makes no difference.

**Comment by jcrowgey** [comment]
#381
