### ISSUE TITLE
--details is broken for --tsv

### ISSUE THREAD

**Issue by mumpitzstuff** [insanum/gcalcli#435]
--details all: does not work (not all details are visible e.g. longurl and other details)

if --details all is active all other --details parameters are ignored like --details longurl

**Comment by lasers** [comment]
@jcrowgey See if you like this fix https://github.com/lasers/gcalcli/tree/longurl

**Comment by jcrowgey** [comment]
We still list longurl in the help for details.  I don't typically have that in my events.  Do we actually fail to show the longurl when the event contains that field?

**Comment by lasers** [comment]
>I think the long/short was originally intended to be used in `add` to use the url shortening service (or not).

I think it's for outputting in `gcalcli agenda` and the likes. From what I see, you have an option of using long/short url. If you specified short, then it have to shorten the urls repeatedly with new hashes. With long url, it will repeatedly display the same urls. Longurl could be preferable in most scenarios and to use shorturl when you want to share.

>I don't currently have any events with urls on my calendar... Fill in here if you have information.

Does this work for you?
* `gcalcli agenda --detail shorturl`
* `gcalcli agenda --detail longurl`

**Comment by jcrowgey** [comment]
Got it yes, that makes sense.  I think I didn't realize that the Link attribute was generated automatically.  So, do we agree that the --detail parser probably isn't appropriate for `add`?

**Comment by lasers** [comment]
>So, do we agree that the --detail parser probably isn't appropriate for add?

I think so because `Which parts to display, can be:... ` does not make sense to be there.
