### ISSUE TITLE
Ampersand in calendar at the beginning of line upsets display

### ISSUE THREAD

**Issue by billmaidment** [insanum/gcalcli#442]
I am using current master branch and an ampersand (&) at the beginning of a line in the calendar upsets the display.
![Screenshot at 2019-04-12 15-10-05](https://user-images.githubusercontent.com/17757393/56013647-2bbd8000-5d35-11e9-8dd8-9c3aa965b09b.png)

**Comment by billmaidment** [comment]
I forgot to mention that I'm using conky as follows:
gcalcli --conky calw now 4 |
        sed -e 's/^[(0\x71^[(B/─/g' \
            -e 's/^[(0\x78^[(B/│/g' \
            -e 's/^[(0\x6A^[(B/┘/g' \
            -e 's/^[(0\x6B^[(B/┐/g' \
            -e 's/^[(0\x6C^[(B/┌/g' \
            -e 's/^[(0\x6D^[(B/└/g' \
            -e 's/^[(0\x6E^[(B/┼/g' \
            -e 's/^[(0\x74^[(B/├/g' \
            -e 's/^[(0\x75^[(B/┤/g' \
            -e 's/^[(0\x76^[(B/┴/g' \
            -e 's/^[(0\x77^[(B/┬/g'

**Comment by jcrowgey** [comment]
Possibly related to #372.

Thanks for the report!

Also, you may already know that `--lineart=ascii` now works with `--conky` in case you are okay with old-school style +-| calendar bars and don't want to use sed.  :)

**Comment by billmaidment** [comment]
Thanks for the quick response.
I downloaded the new master, but python setup.py install gives me the following error:
zipimport.ZipImportError: bad local file header in /usr/lib/python2.7/site-packages/gcalcli-4.0.4-py2.7.egg

I have python3 installed:
  File "setup.py", line 52, in <module>
    "Programming Language :: Python :: 3",

Do I have to install differently?

 
 
-----Original message-----

**Comment by billmaidment** [comment]
My bad.
I forgot to login as root.
The new version has fixed up the alignment OK.
 
 
-----Original message-----

**Comment by jcrowgey** [comment]
Thank you for the report.  There was definitely a logic error in the calendar drawing code that you helped fix!
