### ISSUE TITLE
Reminder timing seems off

### ISSUE THREAD

**Issue by sagotsky** [insanum/gcalcli#448]
Hi.  I just found the remind command and I'm super happy to have it.  It's firing reminders at unexpected times though. 

I've been doing `gcalcli remind 0 "echo %s"`.  It seems like I'm getting the reminder 5 minutes earlier than expected.  It's also lasting past the expected time (which is past the end of the event in the case of my test alerts).  

It totally makes sense that there would be some sort of fudge factor around the alert time.  I could also see the reminder being keyed off the event's alert time, not start time.  

I can't tell if this is working as intended or if it's buggy.  If this is all intended, could the reminder time math be published in the readme somewhere?  I can work around the weirdness if I have confidence that the reminder will come up if `event.start_time - event.alert_min_before < now < event.end_time` (or something to that effect).

**Comment by jcrowgey** [comment]
https://github.com/insanum/gcalcli/blob/a75b73bb63056cf69d6912f6b6587e7fa4d664c6/gcalcli/gcal.py#L1332

I'd love a PR to update the readme as you suggested :)

**Comment by sagotsky** [comment]
Here ya go!  https://github.com/insanum/gcalcli/pull/450

**Comment by jcrowgey** [comment]
Merged, thank you.
