### ISSUE TITLE
Add latest release to apt-get repo

### ISSUE THREAD

**Issue by lfv89** [insanum/gcalcli#449]
Would it be possible to add the latest release to the apt-get repo?

I'm having trouble with the `--nostarted` option in `v4.0.0a3`, as follows:

> The following options are either no longer valid globally or just plain invalid: --nostarted

**Comment by jcrowgey** [comment]
This is a task for the maintainers of your distribution's repositories.   FWIW, debian has 4.0.4 (not the alpha) in buster and sid.  I have written to the maintainer to make sure they're aware of the 4.1.0 release.

https://packages.debian.org/buster/gcalcli
https://packages.debian.org/sid/gcalcli
