### ISSUE TITLE
ways to format the output data

### ISSUE THREAD

**Issue by aristosv** [insanum/gcalcli#454]
Currently, when I type `gcalcli agenda` I get this output

```
Fri Jun 07   7:00am  appointment1
             9:15am  appointment2
             10:15am appointment3
             2:30pm  appointment4
             3:30pm  appointment5
             3:30pm  appointment6
             4:15pm  appointment7
             5:00pm  appointment8
             5:30pm  appointment9
```
is there an option to show the output like this?

```
Fri Jun 07   7:00am  appointment1
Fri Jun 07   9:15am  appointment2
Fri Jun 07   10:15am appointment3
Fri Jun 07   2:30pm  appointment4
Fri Jun 07   3:30pm  appointment5
Fri Jun 07   3:30pm  appointment6
Fri Jun 07   4:15pm  appointment7
Fri Jun 07   5:00pm  appointment8
Fri Jun 07   5:30pm  appointment9
```

This will basically help me when formatting the output of the bash script.

My target is to get the date, time and phone number (which is always in the title of the event) and using an API I will sent an SMS reminder 24 hours and 1 hour before the appointment.

**Comment by jcrowgey** [comment]
I think that `--tsv` will get you to where you want to go.

**Comment by aristosv** [comment]
that's great, thanks!
