### ISSUE TITLE
list events

### ISSUE THREAD

**Issue by remembertoremind** [insanum/gcalcli#461]
Hi! Thanks for this great application!

I wanted to see a range of dates, and I wrote this question before I found out how to do it :) I think the part about `agenda` in the man-page could be fleshed out a bit. I'm not sure how to ask for a range of dates. Eg can I ask for more than the current month?

**Comment by jcrowgey** [comment]
It sounds like you figured out that you can add a `start` and `end` parameter to the `agenda` call.  Perhaps you used `gcalcli agenda --help` for this.

Feel free to submit a pull request with improvements to the documentation. Any such help is warmly appreciated!
