### ISSUE TITLE
Formating Text

### ISSUE THREAD

**Issue by MeisterLupo** [insanum/gcalcli#462]
i want to change the position of the text. Currently I do not see how to do this. The events of the calendar are not placed at the same position. This locks not very nice: 
![gicalci](https://user-images.githubusercontent.com/52126879/59975775-1928b800-95bc-11e9-9a71-faa791ffe256.jpg)
My operating system is Linux Mint 19.1.
I use conky to show my calender on the desktop by using this comand:
"${execpi 1800 gcalcli --conky agenda `date -d"$day" +%Y-%m-%d` `date -d"$day + 1 day" +%Y-%m-%d` --military}"
I have created the file .gcalclirc in my home directory with one entry "--nocolor".
Is there a possibility to define the position of the text blocks?

It would also be nice to display not only the the start of one event but also the end.

My files:
[conkyrc-Calendar.txt](https://github.com/insanum/gcalcli/files/3317827/conkyrc-Calendar.txt)
[gcalclirc.txt](https://github.com/insanum/gcalcli/files/3317832/gcalclirc.txt)

**Comment by jcrowgey** [comment]
I can't seem to reproduce your issue, except in that when I tried your invocation in my .conky file, I see errors from the `date` command.  That coincides to some degree with your sscreenshot, in that you seem to be intending to ask for only today's agenda ($day, $day+1) but your screenshot clearly shows something closer to a week (the default).

I suggest that you try working out your gcalcli invocation without --conky first, to make sure you don't have errors, then figure out if you need to change anything for conky integration.

Finally, I'll note that if your really do want to just get a single day's agenda for "today", you can take advantage of the smart date parsing we provide.  The following works for me:

```sh
$ gcalcli agenda today tomorrow
```

Good luck!
