### ISSUE TITLE
Python error

### ISSUE THREAD

**Issue by testbughub** [insanum/gcalcli#467]
Hi.

I just upgraded to Ubuntu 19.04, and I got some errors that I of course forgot to write down.
Now however, I get this error when using "gcalcli calm --mon --military" :

Traceback (most recent call last):
  File "/usr/bin/gcalcli", line 11, in <module>
    load_entry_point('gcalcli==4.0.4', 'console_scripts', 'gcalcli')()
  File "/usr/lib/python3/dist-packages/gcalcli/cli.py", line 147, in main
    cal_names=cal_names, printer=printer, **vars(parsed_args)
  File "/usr/lib/python3/dist-packages/gcalcli/gcal.py", line 67, in __init__
    self._get_cached()
  File "/usr/lib/python3/dist-packages/gcalcli/gcal.py", line 196, in _get_cached
    self.all_cals = self.cache['all_cals']
KeyError: 'all_cals'

Any help would be appreciated!

**Comment by testbughub** [comment]
Anyone? Just some general directions where to look would help.

**Comment by hammerheadlemon** [comment]
I've not looked at gcalcli for a while but it looks to be an issue with your cache, which may not have survived your OS upgrade. Have a look and see if you have a `~/.gcalcli_cache` directory. Or try your command with the `--nocache` option. Report back.

**Comment by testbughub** [comment]
Success! Deleting the .gcalcli_cashe worked wonderfully!
Thank you so much!
