### ISSUE TITLE
Support updated/moved/cancelled events from ics/vcal files when importing

### ISSUE THREAD

**Issue by insanum** [insanum/gcalcli#47]
gcalcli needs to support importing events from ics/vcal files (i.e. from Exchange) that have previously been entered and are now updated, moved, or cancelled.

I haven't looked closely at the ICS spec but I think there is a UID field in there which is used for tracking individual meetings which can be tagged onto a Google Calendar event.

**Comment by insanum** [comment]
Going to use this issue for tracking the ` track_import_event_ids ` branch. See commit 928a9dfdcfdc7eb73c379ba15f9185ff03ef7888 which attempts to add this enhancement.

**Comment by guiniol** [comment]
I have been using the `track_import_events_ids` branch for a few days and it seems to work properly. I haven't tested removing events because I'm unsure as to how to do that with an .ics file

**Comment by insanum** [comment]
That's good. This changes in that branch work great for single events. For removing events, the .ics file will have a `STATUS:CANCELLED` field. This triggers gcalcli to remove the event from the calendar.

Note that you'll really start seeing problems when trying to move/delete single event inside a recurrence.

**Comment by guiniol** [comment]
I'm not sure if it would qualify as a bug (especially since it seems to be due to the google side), but if I add an event, cancel it, and then try to re-add it, I get:

googleapiclient.errors.HttpError: <HttpError 409 when requesting https://www.googleapis.com/calendar/v3/calendars/gguiniol%40gmail.com/events?alt=json returned "The requested identifier already exists.">

**Comment by insanum** [comment]
Yes I've seen that as well. For some reason the event UID remains on the Google servers and you can't re-use it. I never followed up as to why and whether or not the API allows you to override it. Maybe there is a more permanent way to perform the previous cancellation/deletion. Don't know.

**Comment by dbarnett** [comment]
I believe #583 should fix this? LMK if you see otherwise.
