### ISSUE TITLE
Can't run, unknown command line flag noauth_local_webserver

### ISSUE THREAD

**Issue by AndyReifman** [insanum/gcalcli#470]
Trying to use gcalci for the first time. I installed it by running 
`apt-get install gcalcli`

When I ran it the first time with `gcalcli list` I get
```gcalcli list
Your browser has been opened to visit:

<URL>

If your browser is on a different machine then exit and re-run this
application with the command-line parameter

  --noauth_local_webserver
```

Then when I try to run `gcalcli --noauth_local_webserver list` it tells me `Unknown command line flag 'noauth_local_webserver'`, and then prints out the usage message.

**Comment by jcrowgey** [comment]
Can you report the version number ```gcalcli --version```.  I can't repro this.  I tried on v4.0.4 and v4.1.1 (on debian buster).

**Comment by AndyReifman** [comment]
Looks like I'm way back on `v3.3.2`, which seems odd since I just installed today.
