### ISSUE TITLE
Alignment issues with Conky (using --lineart=ascii and --lineart=unicode)

### ISSUE THREAD

**Issue by logix2** [insanum/gcalcli#477]
Using gcalcli (it's the same using version 4.0.4 and latest gcalcli version installed using PIP) with ``--conky`` (with Conky 1.10.8), and ``--lineart=ascii`` in the month view (``calm``), the ascii line above the month name (at the top of the widget) is misaligned. Screenshot: [https://i.imgur.com/SOpo2dy.png](https://i.imgur.com/SOpo2dy.png).

With ``lineart=unicode`` it gets worse, having not only the line above the month name misaligned, but part of the last bottom line is also missing. Screenshot: [https://i.imgur.com/fPuSA0H.png](https://i.imgur.com/fPuSA0H.png)

P.s.: thanks for this great tool!

**Comment by jcrowgey** [comment]
Thanks for the report!

I can't seem to reproduce this generally.  It may be that there's something specific about your calendar which triggers the poor alignment.  I understand you may not want to share your calendar for privacy reasons, but maybe you can figure out some repro steps (ie, how to create a set of events which triggers the bug).

Also, just to be clear, you've reprod this with 4.1.1 as well?

**Comment by logix2** [comment]
Actually it also happens with an empty calendar, with both ascii and unicode, the only difference between an empty calendar and my initial calendar being that the bottom line is not misaligned when using ``--lineart-=unicode``, but the top line is still broken in both. 

Screenshot gallery with both ascii and unicode lineart, with an empty calendar: [https://imgur.com/a/JZ4U7Ml](https://imgur.com/a/JZ4U7Ml)

And yes, it happens with 4.1.1 too (install with PIP3).

**Comment by logix2** [comment]
This is my Conky (using Conky 1.10.8, which is in both Ubuntu 18.04 and 19.04) configuration in case it matters:

```
conky.config = {
    background = true,
    update_interval = 1.5,
    cpu_avg_samples = 2,
    net_avg_samples = 2,
    out_to_console = false,
    override_utf8_locale = true,
    double_buffer = true,
    no_buffers = true,
    text_buffer_size = 32768,
    imlib_cache_size = 0,
    own_window = true,
    own_window_type = 'desktop',
    own_window_argb_visual = true,
    own_window_argb_value = 120,
    own_window_hints = 'undecorated,below,sticky,skip_taskbar,skip_pager',
    border_inner_margin = 10,
    border_outer_margin = 0,
    xinerama_head = 1,
    alignment = 'top_right',
    gap_x = 90,
    gap_y = 90,
    draw_shades = true,
    draw_outline = false,
    draw_borders = false,
    draw_graph_borders = false,
    use_xft = true,
    font = 'Ubuntu Mono:size=12',
    xftalpha = 0.8,
    uppercase = false,
    default_color = '#FFFFFF',
    own_window_colour = '#000000',
    minimum_width = 0, minimum_height = 0,
};

conky.text = [[
    ${execpi 300 gcalcli --conky --lineart=unicode calm --monday}
]];
```

I used the same configuration back when I was using gcalcli 4.0.0a3 (which had ``--nolineart`` instead of ``--lineart=...``), and it worked with no issues.

**Comment by xdispatchx** [comment]
change this
```
conky.text = [[
    ${execpi 300 gcalcli --conky --lineart=unicode calm --monday}
]];
```

to this
```
conky.text = [[
${execpi 300 gcalcli --conky --lineart=unicode calm --monday}
]];
```

**Comment by logix2** [comment]
Indeed, the alignment fixes it.
