### ISSUE TITLE
"ERROR: Missing module - No module named dateutil.tz"

### ISSUE THREAD

**Issue by vitaly-zdanevich** [insanum/gcalcli#479]
After `sudo apt install gcalcli`.

Version `4.0.0~a3-1`.

Xubuntu 18.04.3 i686.

**Comment by jcrowgey** [comment]
https://github.com/insanum/gcalcli/blob/1746522de0fa41dfe8764deaeef18e4cc7c7e88a/setup.py#L37

Seems like your package manager has made some mistake.
