### ISSUE TITLE
AttributeError: 'GoogleCalendarInterface' object has no attribute '_cal_service'

### ISSUE THREAD

**Issue by slosar** [insanum/gcalcli#489]
When importing a vcs file, gcalcli fails with the above error. Latest master from git:
```
anze@kosovel: ~ [15294] ▶ gcalcli --calendar="Anze Slosar" import -v ~/vcal-3.vcs 
+----------------+
| Calendar Event |
+----------------+
Event........Retreat Preparation

...
 [redacted]
...

[S]kip [i]mport [q]uit: i
Traceback (most recent call last):
  File "/home/anze/anaconda3/bin/gcalcli", line 11, in <module>
    load_entry_point('gcalcli==4.2.0', 'console_scripts', 'gcalcli')()
  File "/home/anze/anaconda3/lib/python3.6/site-packages/gcalcli-4.2.0-py3.6.egg/gcalcli/cli.py", line 230, in main
  File "/home/anze/anaconda3/lib/python3.6/site-packages/gcalcli-4.2.0-py3.6.egg/gcalcli/gcal.py", line 1583, in ImportICS
AttributeError: 'GoogleCalendarInterface' object has no attribute '_cal_service'
anze@kosovel: ~ [15294] ▶ 


```
Any ideas?

**Comment by jcrowgey** [comment]
Well, I don't know if I know what cargo culting means in this context, but I'm glad you found a solution.  If you want to send a PR with that patch, that would be convenient.

Otherwise I can patch it shortly.  In either case, thanks for the report and the fix.

**Comment by tschwinge** [comment]
> I don't know if I know what cargo culting means in this context

<https://en.wikipedia.org/wiki/Cargo_cult_programming> -- do the same thing as done elsewhere (`s%_cal_service%get_cal_service`) even if not understanding what it means.  (But here, it really is obvious.)

> I'm glad you found a solution. If you want to send a PR with that patch, that would be convenient.
> 
> Otherwise I can patch it shortly. In either case, thanks for the report and the fix.

I filed PR #516.
