### ISSUE TITLE
ImportError: cannot import name get_terminal_size

### ISSUE THREAD

**Issue by ricorico94** [insanum/gcalcli#493]
Hi,
I've been using Gcalcli for years now with my Domoticz.. an dvery happy about it.
However, I now face an error during setup process.
Every time I've been installing on a Raspberry Pi (Stretch Lite version), I followed this process:
o	sudo apt-get install python-gflags python-dateutil python-httplib2 
o	sudo apt-get install python-pip
o	sudo git clone https://github.com/insanum/gcalcli.git 
o	 cd gcalcli 
o	 sudo python setup.py install
o	gcalcli --noauth_local_webserver agenda
This summer, I also had to run:
sudo pip install pyasn1 --upgrade
and also
pip install cachetools 
but then it was working. From logs I could take, it was installing gcalcli 4.1.1

but this time, when installing (still usig latest realease of raspberry pi Stretch Lite), I get an error message :
`pi@raspberrypi:~/gcalcli $ gcalcli --noauth_local_webserver agenda
Traceback (most recent call last):
  File "/usr/local/bin/gcalcli", line 11, in <module>
    load_entry_point('gcalcli==4.2.0', 'console_scripts', 'gcalcli')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 561, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2631, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2291, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2297, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "build/bdist.linux-armv7l/egg/gcalcli/cli.py", line 30, in <module>
  File "build/bdist.linux-armv7l/egg/gcalcli/argparsers.py", line 8, in <module>
ImportError: cannot import name get_terminal_size
`
At that stage, I really don't know what to do (my knowledge of linux is also limited.. sorry). 
What should I do ?

Thanks in advance for your help,
ricorico94
> 
Edit: I found on the web a suggestion for error looking similar, but which does not seem to work in my case. It was about running:
pip install --upgrade setuptools pip
pip uninstall backports.shutil_get_terminal_size
pip install --upgrade backports.shutil_get_terminal_size
In my case, I still face the same error.

**Comment by jcrowgey** [comment]
You want to switch to python3.  See #481.  If you can pull from master, in theory this patch 
f6f181d fixed issues with importing get_terminal_size.

A couple of further notes:

1) We don't depend on gflags anymore, so you shouldn't need that dependency.
2) In general, you should probably switch to pip, if you can.  It should take care of dependencies for you so that you just need `pip3 install gcalcli`.

Hope this helps.

**Comment by ricorico94** [comment]
Hi,
Thank you for support. 
Do you mean that I should aviod my install process (including the setup.py command) and use simply "pip3 install gcalcli" ? or will it require also to execute the commands described in other message you refer to (this one:

> git clone https://github.com/insanum/gcalcli
cd gcalcli/
git checkout bugfix/481
gcalcli # old one with the error
pip uninstall gcalcli # remove it
python setup.py install # install new
gcalcli # looks good

> )

**Comment by jbrockc** [comment]
@ricorico94 I struggled a bit with this error yesterday. I had installed Debian 10 over Xubuntu 18.04. However, I had kept the same home directory/partition. I fixed the issue by deleting the files `.gcalcli_cache ` and `.gcalcli_oauth` in my home directory. Then I just ran `gcalcli list` and re-authenticated with Google. I hope this can help.

**Comment by jcrowgey** [comment]
@ricorico94 f6f181d3 was merged to master, so you shouldn't have to clone the bugfix branch.  In general, installing with pip(3) is preferred these days.  Since f6f181d3 has not yet been released to pypi, you're going to want to clone this repo and then `pip3 install .`.  That should be all.
