### ISSUE TITLE
Sign in with Google temporarily disabled for this app

### ISSUE THREAD

**Issue by johnnypea** [insanum/gcalcli#497]
Anyone experiencing this issue when trying to initialise the Google calendar? Is there some problem with the app @insanum ? Thanks.

> This app has not been verified yet by Google in order to use Google Sign In.

**Comment by insanum** [comment]
Yes, I got a notification from Google about this a couple days ago. I submitted the gcalcli API scope usage for verification by Google. The form said it could take a couple weeks.

If you knows someone who works for Google... ask them to help expedite/guide this along. :-)

**Comment by jester02k** [comment]
Hello I'm getting this error too after a reinstall of my system can someone explain whats going on is it my system or google's. I have never had a problem with Gcalcli  an miss it.

**Comment by zripka** [comment]
Same here, I'm trying to install it for the first time and I'm getting the same message.

**Comment by qualitywins** [comment]
Same here.

**Comment by rpietro** [comment]
same here

**Comment by MarSoft** [comment]
If you created client id and client secret from dev account associated to your google account then on "App not verified" screen you can bypass it by clicking "Additional" and then "Go to (project name) page".

**Comment by rpietro** [comment]
@MarSoft I don't get that option on Chromium or Firefox.

**Comment by eethann** [comment]
Can users create their own app as a work-around?

**Comment by eethann** [comment]
Confirming that using the `--client-id` and `--client-secret` arguments to authenticate works. [This article](https://codeyarns.com/2013/11/19/how-to-use-gcalcli-with-your-own-client-id-and-secret/) is a bit outdated but is the general idea: create an OAuth web login app in the Google developer console, then enable the calendar API for it. Works!

This is probably the best approach, actually, if you are concerned about security (making sure you're not granting a 3rd party app access to your cal).

**Comment by maphew** [comment]
the process at https://github.com/insanum/gcalcli#login-information is more up to date than the blog post link on eethan's comment. There is still a "This app isn't verified" warning screen, but expand [Advanced] link at bottom and then use [Go to gcalcli (unsafe)] link under that.

**Comment by anthrolisp** [comment]
I'm also getting the following error:

> This app has not been verified yet by Google in order to use Google Sign In.

I'm unable to get the --client-id and --client-secret arguments to work, and the "[Advanced] link at the bottom is not visible for me.

Any ideas? Many thanks in advance!

**Comment by maphew** [comment]
I tried to setup another computer. Google isn't showing the [Advanced] and [Go to gcalcli (unsafe)] links anymore for me either.

**Comment by aristosv** [comment]
Are there any workarounds to make this work?

**Comment by awkwardengineer** [comment]
any update on when Google might approve? I'm still hitting the same "Sign in with Google temporarily disabled for this app This app has not been verified yet by Google in order to use Google Sign In."

**Comment by jester02k** [comment]
I have been waiting for over a month is this going to be fixed or what or has it been abandoned? Any info would be appreciated.

**Comment by jcrowgey** [comment]
So far, it seems like google hasn't invalidated any existing oauth tokens, so I've still been able to use gcalcli as normal.   I did move my token out of the way and try to go through the sign in process using firefox.  I also didn't see the "Advanced" option that some users reported.  It would be nice to get to the bottom of that: exactly who sees "Advanced" and why.

**Comment by aristosv** [comment]
Yes. Once you set up a new id and secret, then the Advanced option appears and you can create the 2 authentication files.

**Comment by ripperle** [comment]
@aristosv Today I tried to install gcalcli and had the same problem. How do you set up a new ID and secret?

**Comment by pjotrp** [comment]
The following worked for me: login to your google account and enable Google Calendar API with OAuth 2.0 Client IDs . Copy the client ID credentials. Next remove any old settings

      rm ~/.gcalc*

Next login with credentials

     ~/.local/bin/gcalcli --xxxx.apps.googleusercontent.com --client-secret=XXXX calw

Now, critically, you get a login in the browser which says the app is temporarily disabled. Click on the 'Advanced' link (which only shows up when you use credentials) and go to gcalcli and allow all. It will end with 'The authentication flow has completed.'.  This should show your calendar, now you can run without credentials

      ~/.local/bin/gcalcli calw

**Comment by sadid** [comment]
I can confirm that this solution worked.

**Comment by slosar** [comment]
Sorry for being a noob, but how do I " enable Google Calendar API with OAuth 2.0 Client IDs "? I've been looking around my google settings and google calendar settings and can't find this option.

**Comment by abers** [comment]
Same issue as with @slosar, absolutely no idea how to securely setup OAuth 2.0 Client IDs. When trying I'm stuck at stage where forced to setup a OAuth consent screen but unable to restrict it to Internal only. Any step-by-step instructions available?

**Comment by jester02k** [comment]
This has worked for me but make sure you are using Chrome or Chromium  not Firefox. That is where I see the other button (I can't remember it's name) and it steps through allowing it at the end you get a security code. But I can say that I have to run this every once and a while to reauthorize gcalcli it just fails.

**Comment by pjotrp** [comment]
I use firefox only. It worked as described.

**Comment by tuckerconnelly** [comment]
There's a button on this page that automates a lot of the process for getting the client id + secret, just need to click it: https://developers.google.com/calendar/quickstart/go

Also not sure if this matters, but @pjotrp it looks like your comment above is missing `client-id=`, should be:

```
 ~/.local/bin/gcalcli --client-id=xxxx.apps.googleusercontent.com --client-secret=XXXX calw
```

**Comment by Hitkul** [comment]
Just tried the method suggested by @pjotrp (created client-id by @tuckerconnelly suggestion) but I did not see any 'Advanced' link. Tested with both Brave and Chrome browser. Any idea what can I try next?

**Comment by squiter** [comment]
Just like @Hitkul I followed the instructions and can't see the 'Advanced' link in Chrome neither Firefox :(

**Comment by dannyshaw** [comment]
the configuration parameters are `--client_id` and `--client_secret` (note then underscores).

and NOT `--client-id` and `--client-secret` as incorrectly specified in the docs and all the examples above.

It must have changed at some point.

**Comment by Hitkul** [comment]
@dannyshaw It worked. Thank you

**Comment by squiter** [comment]
> and NOT --client-id and --client-secret as incorrectly specified in the docs and all the examples above.

This did the trick, thaniks

**Comment by desgua** [comment]
Thank you so much [abers](https://github.com/insanum/gcalcli/issues/497#issuecomment-592948891) this step by step was what I needed :-)

**Comment by tobiasrenkin** [comment]
Tried to follow @abers steps, but it says I need to go through verification. It seems google makes people jump through more and more hoops to access their own data...

**Comment by aristosv** [comment]
Would this help?

https://github.com/aristosv/google_auth/blob/master/README.md

and then you can run

gcalcli --client_id=clientid_here --client_secret=clientsecret_here agenda

**Comment by ak202** [comment]
first time trying gcalcli, and I got the "temporarily disabled" notice without any "advanced" options. I did @aristosv suggestion and then the advanced button showed up, and I was then able to authenticate.

**Comment by lee2sman** [comment]
I followed @aristosv readme above. Unfortunately not working for me. Got error message that included ```UserWarning: Cannot access /home/lee/.gcalcli_oauth: No such file or directory
  warnings.warn(_MISSING_FILE_MESSAGE.format(filename))``` Tried on Chrome on Ubuntu

**Comment by sunnyguan** [comment]
If you have the fancy new dropdown box, I tried using TV and it was able to work as well. The name of the TV client did not matter.

**Comment by bwagner** [comment]
Behind a proxy here. Environment Variables `http_proxy `and `https_proxy `configured. Running
`python -m pip install --upgrade pip`
works (to demonstrate proxy settings are picked up by python).
Trying
`gcalcli --client-id=xxx.apps.googleusercontent.com --client-secret=yyy calw`
with and without (`--noauth_local_webserver`), I get to authenticate, but in the shell I get this error:
```
  File "c:\users\czxbwg\appdata\local\programs\python\python38\lib\site-packages\httplib2\socks.py", line 465, in __negotiatehttp
    raise HTTPError((statuscode, statusline[2]))
httplib2.socks.HTTPError: (407, b'Proxy Authentication Required')

```

This is:
gcalcli v4.3.0
on
MINGW64_NT-10.0-17763 C42L37WS1065 3.0.7-338.x86_64 2019-11-21 23:07 UTC x86_64 Msys
on
Microsoft Windows 10 Enterprise
Version 1809 (OS Build 17763. 1397)

**Comment by xdhmoore** [comment]
Still getting this screen on 2020-10-9. I was able to set up the clientid/secret successfully in Google Cloud's console as described. But it would be nice if it just worked. Since this issue has been open so long though, maybe at this point all the setup stuff should be added to the README. I have a passing familiarity with Google Cloud's console, but for people that don't, it may be prohibitively confusing.

**Comment by xdhmoore** [comment]
aaaaand, the process is already mostly on the README, [here](https://github.com/insanum/gcalcli#login-information) for anyone else trying to figure this out. When Google denies access click the Advanced option, as othes have mentioned.

**Comment by KevinBuchs** [comment]
Still happening today. There is no advanced option

**Comment by aristosv** [comment]
Yesterday I did this for a client and it worked just fine. There was an "Advanced" button.

https://github.com/aristosv/google_auth/blob/master/README.md

**Comment by mglantz** [comment]
> Confirming that using the `--client-id` and `--client-secret` arguments to authenticate works. [This article](https://codeyarns.com/2013/11/19/how-to-use-gcalcli-with-your-own-client-id-and-secret/) is a bit outdated but is the general idea: create an OAuth web login app in the Google developer console, then enable the calendar API for it. Works!
> 
> This is probably the best approach, actually, if you are concerned about security (making sure you're not granting a 3rd party app access to your cal).

Confirming that this is still the case as of this writing.
Create Google Calendar API access, add oauth2 application, and then define arguments:
```
gcalcli --client-id the-id-you-created --client-secret the-secret-created
```

**Comment by dbarnett** [comment]
Seems like this won't be an issue anymore (as long as you're supplying your own `--client-id` and not using the old built-in one), but please reach out with a fresh issue if anyone's still seeing problems.
