### ISSUE TITLE
Adding detailed event instruction compatibility

### ISSUE THREAD

**Issue by luwso** [insanum/gcalcli#501]
I can see that help in the newest version (v4.2.0) is different than for ex in v4.0.0a3 but I have a question whether the command should be compatible with new version.

As I can see in version 4.0.0a3 there's an help instruction for add as:

> add a detailed event to a calendar
                           - a single --calendar must specified
                           - the "--details url" option will show the event link
                           - example:
                              gcalcli --calendar 'Eric Davis'
                                      --title 'Analysis of Algorithms Final'
                                      --where UCI
                                      --when '12/14/2012 10:00'
                                      --who 'foo@bar.com'
                                      --who 'baz@bar.com'
                                      --duration 60
                                      --description 'It is going to be hard!'
                                      --reminder 30
                                      add

It doesn't work for 4.0.0a3 as in newer versions of gcalcli. Command works for v3.4.0. To make it work for newer version we have to delete `add` and the end of command and add `add` before `--title`.

The question is: is it desirable? If not I can work on that.

**Comment by jcrowgey** [comment]
We switched to argparse in v4.  So we now have a root command which has some options, then subcommands have their own options.  And the order matters.  A lot of modern CLIs, like git, work this way.  It would be nice to be more robust with help messages when people get it wrong though.  I think that's where I'd like to see improvements.
