### ISSUE TITLE
Sign in with Google temporarily disabled for this app

### ISSUE THREAD

**Issue by pjangam** [insanum/gcalcli#507]
This app has not yet been verified by Google in order to use Google Sign in.

**Comment by jackmawer** [comment]
+1 for this issue

**Comment by jackmawer** [comment]
Workaround is to create a custom app as detailed in the README. Hopefully, Google might verify the app eventually, but this project seems abandoned as-is so this problem will probably not go away otherwise.

**Comment by erikLundstedt** [comment]
this is a duplicate https://github.com/insanum/gcalcli/issues/497
@insanum
