### ISSUE TITLE
Initial Setup Error

### ISSUE THREAD

**Issue by ckurij** [insanum/gcalcli#525]
During initial setup I run this command

`gcalcli --noauth_local_webserver agenda

Go to the following link in your browser:

    **URL HERE**

Enter verification code: 
`

and the url takes me to 

![DeepinScreenshot_select-area_20200330181320](https://user-images.githubusercontent.com/31017935/77970674-66a42500-72b2-11ea-80ba-d3ec7c172299.png)

**Comment by jcrowgey** [comment]
#497

**Comment by jcrowgey** [comment]
#497
