### ISSUE TITLE
googleapiclient.errors.HttpError: <HttpError 404 when requesting https://www.googleapis.com/calendar/v3/calendars/[...]&alt=json returned "Not Found">

### ISSUE THREAD

**Issue by tschwinge** [insanum/gcalcli#530]
As of a few days, I'm getting this traceback using gcalcli master branch (tag: v4.2.1):

    $ gcalcli agenda
    Traceback (most recent call last):
      File "[...]/gcalcli/cli.py", line 247, in <module>
        main()
      File "[...]/gcalcli/cli.py", line 155, in main
        gcal.AgendaQuery(start=parsed_args.start, end=parsed_args.end)
      File "[...]/gcalcli/gcal.py", line 1197, in AgendaQuery
        return self._display_queried_events(start, end)
      File "[...]/gcalcli/gcal.py", line 1157, in _display_queried_events
        event_list = self._search_for_events(start, end, search)
      File "[...]/gcalcli/gcal.py", line 1104, in _search_for_events
        events = self._retry_with_backoff(
      File "[...]/gcalcli/gcal.py", line 112, in _retry_with_backoff
        return method.execute()
      File "/usr/lib/python3/dist-packages/googleapiclient/_helpers.py", line 130, in positional_wrapper
        return wrapped(*args, **kwargs)
      File "/usr/lib/python3/dist-packages/googleapiclient/http.py", line 856, in execute
        raise HttpError(resp, content, uri=self.uri)
    googleapiclient.errors.HttpError: <HttpError 404 when requesting https://www.googleapis.com/calendar/v3/calendars/[...]&alt=json returned "Not Found">

If I manually retrieve that URL, I get:

    {
      "error": {
        "code": 403,
        "message": "The request is missing a valid API key.",
        "errors": [
          {
            "message": "The request is missing a valid API key.",
            "domain": "global",
            "reason": "forbidden"
          }
        ],
        "status": "PERMISSION_DENIED"
      }
    }

**Comment by tschwinge** [comment]
Well, and a few tries later, I now get:

    {
     "error": {
      "errors": [
       {
        "domain": "usageLimits",
        "reason": "dailyLimitExceededUnreg",
        "message": "Daily Limit for Unauthenticated Use Exceeded. Continued use requires signup.",
        "extendedHelp": "https://code.google.com/apis/console"
       }
      ],
      "code": 403,
      "message": "Daily Limit for Unauthenticated Use Exceeded. Continued use requires signup."
     }
    }

I'll try the steps outlined in #497.

**Comment by tschwinge** [comment]
> I'll try the steps outlined in #497.

That worked.

**Comment by ifiscoder** [comment]
hi have same problem.how you solved it ?
<HttpError 403 when requesting https://serviceusage.googleapis.com/v1/projects/loyal-theater-314713/services/iam.googleapis.com:enable?alt=json returned "Project 'loyal-theater-314713' not found or permission denied.". Details: "[{'@type': 'type.googleapis.com/google.rpc.PreconditionFailure', 'violations': [{'type': 'googleapis.com', 'subject': '?error_code=210002&type=Project&resource_id=loyal-theater-314713'}]}, {'@type': 'type.googleapis.com/google.rpc.ErrorInfo', 'reason': 'RESOURCES_NOT_FOUND', 'domain': 'serviceusage.googleapis.com', 'metadata': {'type': 'Project', 'resource_id': 'loyal-theater-314713'}}]">
<HttpError 403 when requesting https://serviceusage.googleapis.com/v1/projects/loyal-theater-314713/services/drive.googleapis.com:enable?alt=json returned "Project 'loyal-theater-314713' not found or permission denied.". Details: "[{'@type': 'type.googleapis.com/google.rpc.PreconditionFailure', 'violations': [{'type': 'googleapis.com', 'subject': '?error_code=210002&type=Project&resource_id=loyal-theater-314713'}]}, {'@type': 'type.googleapis.com/google.rpc.ErrorInfo', 'reason': 'RESOURCES_NOT_FOUND', 'domain': 'serviceusage.googleapis.com', 'metadata': {'type': 'Project', 'resource_id': 'loyal-theater-314713'}}]">
Creating accounts in saf-ppn1s-l0iktiz1bl7hadxwovrt
Creating accounts in transfer-315010
Creating accounts in loyal-theater-314713
Traceback (most recent call last):
  File "gen_sa_accounts.py", line 323, in <module>
    download_keys=args.download_keys
  File "gen_sa_accounts.py", line 233, in serviceaccountfactory
    _create_remaining_accounts(iam,i)
  File "gen_sa_accounts.py", line 33, in _create_remaining_accounts
    sa_count = len(_list_sas(iam,project))
  File "gen_sa_accounts.py", line 93, in _list_sas
    resp = iam.projects().serviceAccounts().list(name='projects/' + project,pageSize=100).execute()
  File "/usr/local/lib/python3.7/dist-packages/googleapiclient/_helpers.py", line 134, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/googleapiclient/http.py", line 915, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 404 when requesting https://iam.googleapis.com/v1/projects/loyal-theater-314713/serviceAccounts?pageSize=100&alt=json returned "Requested entity was not found.". Details: "Requested entity was not found.">

**Comment by ifiscoder** [comment]
{
  "error": {
    "code": 403,
    "message": "The request is missing a valid API key.",
    "status": "PERMISSION_DENIED"
  }
}

**Comment by tschwinge** [comment]
(... if only for my own later reference...)  ;-)

I've ran into this again, and followed the steps of <https://github.com/insanum/gcalcli#login-information> to restore access.

**Comment by tschwinge** [comment]
Today I figured out that in my last steps, <https://github.com/insanum/gcalcli/issues/530#issuecomment-1277241149>, *Reset Client Secret* is not actually necessary, but one may instead *Continue [...]* with the *existing* credentials as displayed on the page where you'd *Reset Client Secret*.
