### ISSUE TITLE
clientid + secret - authorization still required?

### ISSUE THREAD

**Issue by aristosv** [insanum/gcalcli#531]
Once I have the clientId and client secret, shouldn't gcalcli work without falling back to --noauth_local_webserver?

For example, I run this command

gcalcli --client-id=clientID_here --client-secret=clientSecretHere agenda

and I still get a prompt saying

```
/usr/lib/python3/dist-packages/oauth2client/_helpers.py:255: UserWarning: Cannot access /root/.gcalcli_oauth: No such file or directory
  warnings.warn(_MISSING_FILE_MESSAGE.format(filename))

Failed to start a local webserver listening on either port 8080
or port 8090. Please check your firewall settings and locally
running programs that may be blocking or using those ports.

Falling back to --noauth_local_webserver and continuing with
authorization.


Go to the following link in your browser:

    https://accounts.google.com/o/oauth2/v2/auth?client_id=...more...
```

I was under the impression that once you have the client id and secret, you don't have to go through the authorization process.

I'm I understanding this wrong?

**Comment by jcrowgey** [comment]
My understanding was that given an id and secret, you can use those value to get an oauth token.  I think that's true whether you're using the globally shared app "secret" and id or whether you have your own.
