### ISSUE TITLE
Sign in with Google temporarily disabled for this app

### ISSUE THREAD

**Issue by strogiyotec** [insanum/gcalcli#540]
Good day, I just installed this app (gcalcli v4.3.0 (Eric Davis, Brian Hartvigsen, Joshua Crowgey))
I run simple command `gcalcli list` then I was redirected to google oauth page after authorizing i was redirected to page with the following content
```
Sign in with Google temporarily disabled for this app

This app has not yet been verified by Google in order to use Google Sign in.
```
Probably Google wants this app to follow new security rules

**Comment by eseca** [comment]
Same here.
```
$ gcalcli --version
gcalcli v4.3.0 (Eric Davis, Brian Hartvigsen, Joshua Crowgey)
```

**Comment by deimosfr** [comment]
Same here also for v4.3.0

**Comment by jcrowgey** [comment]
Duplicate #497

**Comment by strogiyotec** [comment]
@deimosfr @eseca 

    Go to OAuth consent screen from sidebar
    Create as External user type
    On next screen give it a name and hit save
    Go to Credentials from sidebar
    Click Create Credentials from top, then OAuth Client ID in the dropdown
    Choose Other, enter any name you want, and hit create
    You now have your client ID and secret
    In your terminal run "gcalcli --client-id "djfldsjl" --client-secret "djfaksdf" agenda
    It'll open login screen in browser, login, when get error page click advanced, select gcalcli and allow all.
