### ISSUE TITLE
Date format for "When" parameter is unclear

### ISSUE THREAD

**Issue by strogiyotec** [insanum/gcalcli#542]
Good day. Let's say I want to add a new event into my calendar . I use `gcalcli add` command and it asks me for a date using `When: ` hint. However it's unclear for me which date format it expects.I wrote `10/05/20 12:30pm` and thought that it will choose 10th of May but gcalcli parsed it as 5th of October. In order to understand the format I had to look through the source code and find that it uses dateutil.parser.parse method. I think it would be better to have some sort of hint about date format something like this 
```
When(ex. yyyy-MM-dd hh:MM(am/pm)):
```
What do you think ? If it's ok I could contribute and implement it .

**Comment by dbarnett** [comment]
Hello from 2024!

I agree it's unclear what format it's assuming. I think it should include an inline hint like you suggested, and be configurable to accept dayfirst date formats. I'll track both improvements on this issue.

And also like I mentioned [in #655](https://github.com/insanum/gcalcli/issues/655#issuecomment-2311669439), it's unfortunate it doesn't just work automatically based on $LC_TIME:

> The dates it parses from input ideally would depend on your system locale (especially LC_TIME on Mac and Linux), but I'm not finding any date parsing libraries that know how to respect system locale like that. dateutil that we use [apparently doesn't](https://stackoverflow.com/a/29548727) and others I found like [dateparser](https://dateparser.readthedocs.io/) support some locale-awareness but not well enough to handle this properly.

But inferring automatically doesn't seem trivial, so we can come back to that question after adding hints and manual config.
