### ISSUE TITLE
Enhancement: import agenda from CSV

### ISSUE THREAD

**Issue by michaelmhoffman** [insanum/gcalcli#550]
I often need to do bulk editing of my calendar which is not super convenient with the Google Calendar web interface. A spreadsheet interface would be much better.

What would you think about a way to do roundtrip updates through `gcalcli agenda --tsv` and a paired command `agendaupdate` for writing any changes back? We would need:

- [x] Some refactoring of `gcalcli.gcal.GoogleCalendarInterface._tsv()`. I would like to replace the current long list of if statements with a modular design based around new class `gcalcli.details.Handler`. Each `Handler` represents the set of event properties that are captured by each item of `gcalcli.argparsers.DETAILS`. These objects would have `get()` handlers for TSV. They would be stored in a `collections.OrderedDict` called `gcalcli.details.HANDLERS`.
- [x] Set `gcalcli.argparsers.DETAILS` to a superset of `gcalcli.details.HANDLERS.keys()` to avoid duplication.
- [x] Add a header row to TSV. This would probably break old code so would require a major release. The alternative would be to add an option like `--header`.
- [x] Implement a `Handler` for `id` to make it trivial to find the right Event later for the round trip.
- [x] Implement `Handler.patch()` for a limited set of details. Throw error if there is a column not in the implemented set.
- [x] Implement `Handler.patch()` for the rest of the details.

Future extensions or subsequent refactoring could include:
- Refactoring other uses of patch to call `details.Handler` subclasses
- Add `Detail.format()` handlers that could be used for `gcalcli.gcal.GoogleCalendarInterface._PrintEvent()`.
- A feature to add new events through this interface instead of only updating events with existing IDs (#550)
- Adding ability to support multiple calendars in agendaupdate
- Adding ability to move events between calendars by changing the calendar field (see commit message for d7589edbdcdf60872179a8be47d7e6b0452ed287)
- A feature to do the round-trip through a Google Sheets instead of a local TSV

**Comment by michaelmhoffman** [comment]
@jcrowgey Could you let me know what you think of this design?

**Comment by jcrowgey** [comment]
Overall this looks good to me.  Your recent work on this project has
been very helpful and appreciated.  I'm sorry for the long delays.  In
general, I'm not going to be able to work on gcalcli much for the
foreseeable future.

**Comment by michaelmhoffman** [comment]
To get the TSV output of `gcalcli agenda` to work automatically in Microsoft Excel with non-ASCII characters, it is necessary to set `PYTHONIOENCODING=utf_16`. Things that don't work `utf_16_le` (no BOM) or `utf_8_sig` (BOM but for whatever reason Excel ignores the tabs by default). This does not seem like a sensible default but if you intend to use these files with Excel you should know about it.

**Comment by michaelmhoffman** [comment]
The easiest way to use a UTF-16 `file.tsv` is to use input redirection with the `PYTHONIOENCODING` environment variable set. There's no user-accessible way to change the encoding of what's read with a file argument.

`PYTHONIOENCODING=utf_16 gcalcli agendaupdate < file.tsv`

**Comment by michaelmhoffman** [comment]
The output of `PYTHONIOENCODING=utf_16 gcalcli agenda` isn't easy to use some other Unix tools like grep with. Instead you can use `iconv --to-code=utf-16` as part of a pipeline. For example:
```bash
gcalcli agenda | grep Title | iconv --to-code=utf-16 > file.csv
```

**Comment by michaelmhoffman** [comment]
The main parts of this are done. I haven't closed the issue because each of the "Future extensions or subsequent refactoring" should either be (1) implemented, (2) made into issues for future discussion or implementation, or (3) decided as WONTFIX.

**Comment by dbarnett** [comment]
K, I've forked off some new issues for the loose ends:
- #773
- #772
- #774
- #775

I'll close out this base issue and we can follow up on subtasks in those or fresh bugs.

**Comment by michaelmhoffman** [comment]
Thank you @dbarnett for cleaning this up.
