### ISSUE TITLE
GCalCli won't install on Ubuntu 20

### ISSUE THREAD

**Issue by mbrylewi** [insanum/gcalcli#579]
Here is what I got installing from package:

![obraz](https://user-images.githubusercontent.com/1277868/104109230-c1e45880-52c3-11eb-95ac-956c1047f0b9.png)

Here is what I got installing manually:

~/gcalcli$ python setup.py install
  File "setup.py", line 15
    print('Warning: No long description generated.', file=sys.stderr)
                                                         ^
SyntaxError: invalid syntax

Any idea how to fix this?

**Comment by shaicoleman** [comment]
You are running it through Python2, Python3 is required.

If you're still getting probably after using Python3, try installing it through pipx
https://pipxproject.github.io/pipx/
