### ISSUE TITLE
Gcalcli install Error

### ISSUE THREAD

**Issue by charpy2312** [insanum/gcalcli#586]
Hi,
I have an error when install GCALCLI :

pi@raspidom:~/gcalcli $ python setup.py install
  File "setup.py", line 15
    print('Warning: No long description generated.', file=sys.stderr)
                                                         ^
SyntaxError: invalid syntax

Have you an idea to correct this error ?

thank you in advance for your help.

**Comment by dbarnett** [comment]
Not sure what this was about but should be no longer an issue with the latest instruction. Let me know if you see otherwise. Thanks!

**Comment by dbarnett** [comment]
Ah, it was a python 2 issue, same as #579. Definitely fixed now that python 2 has been end-of-lifed for years.
