### ISSUE TITLE
Is there any way to make start the week from Monday?

### ISSUE THREAD

**Issue by aReaSa** [insanum/gcalcli#594]
Hello,
I love glcacli, and using a a lot. However, I was wondering that my google calendar by default starts the week from monday. Can i do the same for gcalcli? I don't want it to start Sunday.

Thank you

**Comment by meltzerpete** [comment]
there is `--monday` option for commands `calm` and `calw`. I agree  it would be great to be able to set this default in the `.gcalclirc` though.

**Comment by kiteloopdesign** [comment]
Hi, first of all great app, thanks for doing it !
I have same petition here. This is the standard in all Europe and UK, it should not be too much hassle getting it inside the .gcalclirc options, right?
It should also be listed inside help for gcalcli. Currently doing `man gcalcli` shows nothing at this respect
For us non-USA users this is a must, cant look at a week which starts on Sunday
Thanks

**Comment by diegov** [comment]
I haven't found a way to put this in .gcalclirc, I don't think subcommand options are supported in the config file, so for now I'm running a slightly modified fork that makes Monday the default, and accepts `--sunday` as an option:

https://github.com/diegov/gcalcli/tree/default_week_on_monday

I install most Python tools with pipx, so I just installed it with `pipx install --force git+https://github.com/diegov/gcalcli.git@ec5a296144d6d8060be99d591c52c5376682cfe6` and uninstalled the debian package. 

For now this solves my problem, hopefully in the future with support for subcommand settings in the config file this won't be necessary any more.

**Comment by geekobiloba** [comment]
It's 2023, and `--monday` flag still cannot be used from `~/.gcalclirc`

**Comment by dbarnett** [comment]
> It's 2023, and `--monday` flag still cannot be used from `~/.gcalclirc`

Now it's 2024 and it can :stuck_out_tongue: (not _technically_ from ~/.gcalclirc, but something better).

Once 4.5 release is published (or if you run the latest repo version from source), you can now edit your config.toml with `gcalcli config edit` and configure it to start the week from Monday like:
```toml
#:schema https://raw.githubusercontent.com/insanum/gcalcli/HEAD/data/config-schema.json
[output]
week-start = "monday"
```
