### ISSUE TITLE
Question: Can I remove certain calendars?

### ISSUE THREAD

**Issue by jason-mehmel** [insanum/gcalcli#597]
There's one calendar that my account is linked to that I don't want to see when I use gcalcli.

I don't want to delete the calendar entirely, just remove it from the ones gcalcli lists when I run it.

Can I do that from the gcalcli command line?

Do I need to do it at the authorization level between Google Calendar and gcalcli?

**Comment by jason-mehmel** [comment]
I think I may have found what I'm looking for in the` --calendar` command, but I'm still not sure about usage.

Right now I can see all of the calendars that gcalci has access to, and I really only want to remove one.

Do I need to use `--calendar` and list **every calendar** I want to display, just omitting the one I'm not interested in?

Or is there a usage where I can hide or remove the calendar I don't want to see?

**Comment by jason-mehmel** [comment]
With the help of a redditor, I was able to find a command format that worked in terms of controlling which calendars the agenda shows: 
`
gcalcli --default-calendar 'EXAMPLE CALENDAR' --default-calendar 'EXAMPLE CALENDAR 2' --default-calendar 'EXAMPLE CALENDAR 3' agenda`

What I did notice is that it stripped out the default colours of the agenda for some reason?

I am still having trouble trying to get that into the conky file to display inside that conky window. I've also tried adding them as details in the .gcalclirc file, to no avail. Again, I might be having a command format problem here.

Still working on this, but I did find one other solution: the **--nostarted** agenda option.

Part of what was happening was that I've got calendars logging my phone calls and articles I read in Pocket, which makes the agenda messy. But since most of these things are logged as they happen, the --nostarted feature only shows me things still ahead, so I'm not seeing the clutter.

(I'd still love to figure out a way to control the default calendars, particularly in my conky usage, in the situation where seeing my whole agenda for the day can still be valuable.)



gcalcli --default-calendar 'Work' --default-calendar 'ZZZ supplemental' --default-calendar 'ZZZ Supplemental work' --default-calendar 'd20initiativeyyc@gmail.com' --default-calendar 'jmehmel@gmail.com' --default-calendar 'Weather' --default-calendar 'Week Numbers' --default-calendar 'Sage Theatre Production Calendar' --default-calendar 'Parish of St. Joseph of Arimathea' --default-calendar 'Sage Board Calendar' --default-calendar 'Holidays in Canada' --default-calendar 'jason@sagetheatre.com' --default-calendar 'Birthdays' --default-calendar 'Sage Theatre Staff Calendar' --default-calendar 'Phases of the Moon' --default-calendar 'IGNITE! Calendar' --default-calendar 'AIAM' agenda

**Comment by clemenscodes** [comment]
I figured out that you have to use the dictionary syntax from python eg.:
```gcalcli --calendar={'EXAMPLE CALENDAR', 'EXAMPLE CALENDAR 2'} agenda```

**Comment by dbarnett** [comment]
Now you can! (From the latest repo version, or once I publish a 4.5 release)

See config examples at https://github.com/insanum/gcalcli?tab=readme-ov-file#configuration. This setting would look like:
```toml
[calendars]
ignore-calendars = ["Boring stuff", "Holidays"]
```
