### ISSUE TITLE
This app tried to access sensitive info in your Google Account.

### ISSUE THREAD

**Issue by MuhammadSawalhy** [insanum/gcalcli#598]
I installed `gcalcli` using `sudo apt-get install gcalcli`. Then I run this command:

```bash
> gcalcli  list
```

A link opened in my default browser to OAuth into my account, by here is what I got:

![image](https://user-images.githubusercontent.com/42011920/117550483-f59c7880-b040-11eb-90d2-84aa50441603.png)

**Comment by DavidTre07** [comment]
Duplicate of https://github.com/insanum/gcalcli/issues/580

**Comment by llvllch** [comment]
I got this message when I opened the link in Firefox, switched to Chrome, it worked fine. As a general rule, for all things Google, try Chrome.

**Comment by ki11roy** [comment]
Worked like a charm in Firefox with the instructions from @aristosv

**Comment by dardo82** [comment]
Worked flawlessly in Google Chrome with the instructions from @aristosv! ;-)

**Comment by michaelmhoffman** [comment]
I think the instructions now in `README.md` have substantively the same instructions. If there is anything that needs to be changed please open an issue.
