### ISSUE TITLE
consider add ability to list today's agenda (or between dates)

### ISSUE THREAD

**Issue by Dentrax** [insanum/gcalcli#610]
The following command lists this week's agenda:
```bash
$ gcalcli agenda
```

It would be great if we are able to list between dates or today's and tomorrow's. Like the following:
```bash
$ gcalcli agenda --when today
$ gcalcli agenda --when tomorrow
$ gcalcli agenda --when yesterday
$ gcalcli agenda --from DATE --to DATE
$ gcalcli agenda # lists this week by default
```

What do you think?

**Comment by zekenie** [comment]
I was just looking for this as well. It turns out you can, you just have to specify dates. For example, this works

```
$ gcalcli agenda --details={email,location,conference}  --nostarted --nodeclined 2022-07-16 2022-07-20
```
