### ISSUE TITLE
gcalcli not showing events from all of my Public calendars

### ISSUE THREAD

**Issue by Xliff** [insanum/gcalcli#614]
I can see events from other shared calendars, however I have several calendars and I'm not seeing any events from any of these. Am  I missing something?

Please advise. Thanks.

**Comment by dbarnett** [comment]
Possibly #622? Could you try `gcalcli --refresh list` to see if that fixes it?

**Comment by dbarnett** [comment]
Didn't hear back yet, going to assume that was the same issue here but if not, feel free to reopen here or LMK on that other issue.
