### ISSUE TITLE
you may lose access to apps that are using less secure sign-in technology (OOB flow)

### ISSUE THREAD

**Issue by aristosv** [insanum/gcalcli#626]
I'm assuming gcalcli wont be affected by this change, since it's using OAuth authentication?

![Greenshot 2022-03-05 06 08 36](https://user-images.githubusercontent.com/528302/156867073-d53db32b-a510-4c2c-964b-3885e97497d6.png)

**Comment by rrthomas** [comment]
I've just been notified that gcalcli will indeed stop working because it uses OOB OAUTH2.

**Comment by jhilker1** [comment]
I hope so too, because I love this tool and use it daily.

**Comment by gopromaster** [comment]
The issue is that the deprecated library `oauth2client` is used for authentication. The suggested replacement is `google-auth`, see [here](https://google-auth.readthedocs.io/en/latest/oauth2client-deprecation.html)... Has anyone attempted to adapt `gcalcli` for this?

**Comment by michaelmhoffman** [comment]
@gopromaster Thanks for the tip on google-auth! If anyone can verify that switching will fix this, that information would be greatly appreciated. As would a pull request.

**Comment by ManuRS** [comment]
I was trying to open the link in Chrome as always. I finally tried with Firefox and still working. My bad for assuming that google services will work better with the google browser. Maybe was just an annoying cache bug on Chrome or something like that.

In any case, I would mark this issue as "important" or something like that. Because is true the library oauth2client is getting old and Google could discard OOB OAuth at any moment.

**Comment by jhilker1** [comment]
I can fork the project and see what I can do - I've got a new machine coming in today, but once I get that set up I can work on it.

**Comment by jhilker1** [comment]
> I can fork the project and see what I can do - I've got a new machine coming in today, but once I get that set up I can work on it.

Unfortunately, been dealing with some really heavy stuff in my personal life, so I'm not sure I'll be able to work on it right now. I'm sorry all - I'll be archiving my fork, and when things improve I'll see what I can do.

**Comment by dbarnett** [comment]
Hey folks, has anyone seen this flavor of issue recently?

AFAICT the current auth instructions won't hit this because they have you set up your own Google "project" and client ID, and that will presumably be set up in "Testing" mode instead of "Production".
