### ISSUE TITLE
Google limits access to 7 days. 

### ISSUE THREAD

**Issue by jsellin78** [insanum/gcalcli#634]
So every week i have to do the process over agen to get access to my calender.
Google limits token for 7 days, then you have to do it all over agen witch is frustrating.

I've googled about this issue, and no one seems to know anything about it.

why cant i have permanent access to my calender with gcalcli without having to reauthenticate every week?

**Comment by ajkessel** [comment]
Per https://github.com/insanum/gcalcli/issues/611 , if we can figure out how to get gcalcli to pass a redirect_uri parameter to the Python Google OAuth2 module, it should be possible to publish the app without Google review and have longer-lasting tokens. I also filed an Ubuntu bug report at https://bugs.launchpad.net/ubuntu/+source/python-oauth2client/+bug/1983216 since it appears upstream is no longer maintaining the relevant library https://github.com/googleapis/oauth2client/issues/317

**Comment by Nephiel** [comment]
For what it's worth, [here is a fork](https://github.com/Nephiel/gcalcli) where the deprecated `oauth2client` library has been replaced with `google-auth`. I just threw [this](https://stackoverflow.com/a/52101480) at the problem.

I'm refraining from making it a PR for now, as it is untested, `redirect_uri` is hardcoded to `localhost` (which I don't like, and I'm not even sure if it is needed). This still doesn't fully solve the 7-day expiration issue, but hopefully paves the way to try the `redirect_uri` approach.

**Comment by jsellin78** [comment]
Went with this instead
to run

python3 timer.py 2023 09 15 19 25

#! /usr/bin/env python3

import time
import os
import sys
from datetime import date
import subprocess
import datetime
import threading
import requests

chat_id=       #Enter Telegramchat_id
TOKEN=       #Token

def start_timer():
    year = int(sys.argv[1])
    month = int(sys.argv[2])
    day = int(sys.argv[3])
    hour = int(sys.argv[4])
    minute = int(sys.argv[5])
    description = str(sys.argv[6]) #Currency
    des2 = str(sys.argv[7]) #16x or 19x or 23x
    date1 = str(sys.argv[8]) #date when occured
    startTime = datetime.datetime(year, month, day, hour, minute)
    print (" ~~> Telegram Alert is set for:{}".format(startTime))
    while datetime.datetime.now() < startTime:
        time.sleep(1)
    print('Time\'s up')
    url = f"
https://api.telegram.org/bot{TOKEN}/sendMessage?chat_id={chat_id}&text={description}
"
    print(requests.get(url).json())

myTimerThread=threading.Thread(
   target=start_timer,
   name='myTimerThread')
myTimerThread.daemon = True
myTimerThread.start()
myTimerThread.join()

**Comment by hramrach** [comment]
> For what it's worth, [here is a fork](https://github.com/Nephiel/gcalcli) where the deprecated `oauth2client` library has been replaced with `google-auth`. I just threw [this](https://stackoverflow.com/a/52101480) at the problem.

It does not seem to work:

```
Traceback (most recent call last):
  File "/usr/bin/gcalcli", line 11, in <module>
    load_entry_point('gcalcli==4.3.0', 'console_scripts', 'gcalcli')()
  File "/usr/lib/python3.6/site-packages/gcalcli/cli.py", line 152, in main
    gcal.AgendaQuery(start=parsed_args.start, end=parsed_args.end)
  File "/usr/lib/python3.6/site-packages/gcalcli/gcal.py", line 1212, in AgendaQuery
    return self._display_queried_events(start, end)
  File "/usr/lib/python3.6/site-packages/gcalcli/gcal.py", line 1156, in _display_queried_events
    event_list = self._search_for_events(start, end, search)
  File "/usr/lib/python3.6/site-packages/gcalcli/gcal.py", line 1105, in _search_for_events
    self.get_events()
  File "/usr/lib/python3.6/site-packages/gcalcli/gcal.py", line 179, in get_events
    return self.get_cal_service().events()
  File "/usr/lib/python3.6/site-packages/gcalcli/gcal.py", line 174, in get_cal_service
    credentials=self._google_auth())
  File "/usr/lib/python3.6/site-packages/gcalcli/gcal.py", line 143, in _google_auth
    credentials = pickle.load(gcalcli_oauth)
_pickle.UnpicklingError: invalid load key, '{'.
```

**Comment by hramrach** [comment]
Also it seems to be using the no longer supported oob authentication type

**Comment by hramrach** [comment]
Apparently the local server that is commented out needs to be used instead of the console flow

**Comment by hramrach** [comment]
Thanks for the patch. It is not complete as is but with a little cleanup it does work well enough - see #677

**Comment by dgrieser** [comment]
Here is a PR which makes it work with the current code base.

**Comment by dbarnett** [comment]
PR is merged now. Hopefully that fixes it for you!
