### ISSUE TITLE
gcalcli agenda: error: argument start: invalid get_time_from_str value: 

### ISSUE THREAD

**Issue by TomHenderson4** [insanum/gcalcli#639]
Calendar "Weather" is a a valid calendar:
> $ gcalcli list 
>  Access  Title
>  ------  -----
>   owner  Tom Henderson (Home)
>   owner  Tom Henderson (Work)
>  reader  Weather
> 

But when I try to list an agenda for only that calendar, i get the following error:

> $gcalcli agenda --calendar "Weather"
> usage: gcalcli agenda [-h]
>                       [--details {calendar,location,length,reminders,description,url,conference,attendees,email,attachments,end,all}]
>                       [--color-owner COLOR_OWNER] [--color-writer COLOR_WRITER] [--color-reader COLOR_READER]
>                       [--color-freebusy COLOR_FREEBUSY] [--color-date COLOR_DATE]
>                       [--color-now-marker COLOR_NOW_MARKER] [--color-border COLOR_BORDER]
>                       [--color-title COLOR_TITLE] [--tsv] [--nostarted] [--nodeclined] [--width CAL_WIDTH]
>                       [--military] [--no-military] [--override-color]
>                       [start] [end]
> gcalcli agenda: error: argument start: invalid get_time_from_str value: 'Weather'
> 

"gcalcli agenda" works as expected for all calendars, but I am unable to limit it to specific calendars without getting that error.

**Comment by abdeoliveira** [comment]
Please try `gcalcli --calendar Weather agenda` instead.

**Comment by michaelmhoffman** [comment]
A more helpful error messages would be nice, but probably not going to happen.

**Comment by TomHenderson4** [comment]
> Please try `gcalcli --calendar Weather agenda` instead.

That worked!
