### ISSUE TITLE
Switch to more standard config file location

### ISSUE THREAD

**Issue by jmetz** [insanum/gcalcli#640]
Instead of home directory dot file for the rc file, would suggest conforming to [XDG  standard](https://specifications.freedesktop.org/basedir-spec/latest/ar01s03.html), ie using `$XDG_CONFIG_HOME` (`~/.config`) and a folder within that, ie:

`$XDG_CONFIG_HOME/gcalcli/config` 

which will usually resolve to `$HOME/.config/gcalcli/config`

**Comment by joshbode** [comment]
The `.gcalcli_cache` and `.gcalcli_oauth` could probably go to `${XDG_CACHE_HOME}/gcalcli/{cache,oauth}`, also.

Note: `${XDG_CACHE_HOME}` usually defaults to `${HOME}/.cache`

**Comment by michaelmhoffman** [comment]
Looks like a good idea. The [xdg-base-dirs](https://pypi.org/project/xdg-base-dirs/) package supplies these paths in a way that meets the standard.
