### ISSUE TITLE
ModuleNotFoundError: No module named 'setuptools

### ISSUE THREAD

**Issue by ghost** [insanum/gcalcli#642]
i get the following error when trying to install the project on arch-Linux:
Traceback (most recent call last):
  File "/home/ituge/gcalcli/setup.py", line 2, in <module>
    from setuptools import setup
ModuleNotFoundError: No module named 'setuptools'

**Comment by dbarnett** [comment]
Probably fixed now. If not, please follow up again with any specifics you have.
