### ISSUE TITLE
Batch deletion

### ISSUE THREAD

**Issue by plegrand1** [insanum/gcalcli#647]
Would it be possible to add an option to delete all past events between two dates?
Unless there is already this possibility or another application.
I have searched without success.
In any case, thank you for your application 
Pascal

**Comment by michaelmhoffman** [comment]
The trunk version of gcalcli (not released) has the `agendaupdate` command. You can use the `agenda` command to get all the events between those dates, change the `action` column from `patch` to `delete` and use `agendaupdate` to 

Something like
```sh
start="tomorrow"
end="dec 1"
calendar="Events"
gcalcli --calendar "$calendar" agenda --details id --details action --tsv "$start" "$end" > calendar.tsv
```

Edit (or script to do this) and then:

```sh
gcalcli --calendar "$calendar" agendaupdate < calendar.tsv
```
```
