### ISSUE TITLE
Same account on multiple devices cause app block 

### ISSUE THREAD

**Issue by Vsb23** [insanum/gcalcli#650]
I have my PC, in which gcalcli works perfectly. I wanted to setup gcalcli on my laptop too, but I've done the procedure and when I call gcalcli for credentials recognition (the last step of the guide), it doesn't show any google window with account permission. 

Also, if after this you put in input any gcalcli command, such as agenda, it show a window in which you can chosse your G account, but immediately says that you app is blocked, due to security problems. 

```
If your browser is on a different machine then exit and re-run this
application with the command-line parameter

  --noauth_local_webserver



```

**Comment by dbarnett** [comment]
Can you still repro this? Are you available to supply a few more details for troubleshooting?
