### ISSUE TITLE
Google blocked this "app"

### ISSUE THREAD

**Issue by balwierz** [insanum/gcalcli#651]
When trying to log in (in browser) I get the following error:

**This app is blocked
This app tried to access sensitive info in your Google Account. To keep your account safe, Google blocked this access.**

**Comment by bombermuecke** [comment]
> When trying to log in (in browser) I get the following error:
> 
> **This app is blocked This app tried to access sensitive info in your Google Account. To keep your account safe, Google blocked this access.**

Same here.

**Comment by elzii** [comment]
+1

**Comment by bombermuecke** [comment]
When will there finally be a fix for this issue? I have to create new token every week because google keeps blocking the app then ...
