### ISSUE TITLE
Using --default_reminders still prompts for reminders

### ISSUE THREAD

**Issue by pawliger** [insanum/gcalcli#653]
I would like to use gcalcli with no interaction. When I try to create an event like this:

`gcalcli add --calendar TestCalendar --title "Test Title" --when "07-Jul-2023 13:00" --duration "60" --where "Test Location" --description "Test Description" --default-reminders`

I still get prompted

`Enter a valid reminder or "." to end: .`

Am I misunderstanding the use of `--default-reminders`? How can I create an event using default reminders and not get prompted?

This is with gcalcli v4.3.0 installed via `brew` on macOS 13.4.1 (22F2083)

**Comment by dbarnett** [comment]
I agree this is confusing... --default-reminders is kind of a weird option, the way it's intertwined with the behavior of other --reminders, but I'm half convinced it shouldn't prompt in that case, the same way if you specified a --reminders arg you could argue that it should still prompt for additional reminders, but it doesn't.

Using --noprompt would work, but I'm also considering to update it to the behavior you were expecting, to not prompt in that case. Either way, I'm planning to update it with some more self-explanatory hints along the way about what it's doing and why.
