### ISSUE TITLE
Date Format

### ISSUE THREAD

**Issue by jakatta** [insanum/gcalcli#655]
Hi,

Loving the app but is there anyway to change the date format from MMDDYYYY to DDMMYYYY?

Any help or pointers would be appreciated.

**Comment by elig0n** [comment]
@jakatta you can modify the source at [utils.py line 94](https://github.com/insanum/gcalcli/blob/master/gcalcli/utils.py#L94) and pass `dayfirst=True` to dateutil_parse. 
Then the first dateutil parser will interpret the first integer of a 3-integer ambiguous string as meaning the day. But this will also mean that for a string like "2023/05/08" 05 will be interpreted as the day.

**Comment by dbarnett** [comment]
I think you mean it's interpreting dates you *input* into the app using the unwanted MMDDYYYY format? Or do you mean certain commands are *displaying* dates in the MMDDYYYY format?

The dates it prints *out* seem to be correctly localized for me (although `--tsv` seems to be hard-coded to YYYYMMDD). The dates it parses from input ideally would depend on your system locale (especially LC_TIME on Mac and Linux), but I'm not finding any date parsing libraries that know how to respect system locale like that. dateutil that we use [apparently doesn't](https://stackoverflow.com/a/29548727) and others I found like [dateparser](https://dateparser.readthedocs.io/) support some locale-awareness but not well enough to handle this properly.

Anyway, yes there could be a config option to control it explicitly if there's really not a good way to detect it from system locale.

**Comment by dbarnett** [comment]
> I think you mean it's interpreting dates you input into the app using the unwanted MMDDYYYY format?

Yep, #542 seems to be talking about a case of the same. I'm going to mark this as a dupe and follow up there. And please clarify any other asks there or in a fresh issue.
