### ISSUE TITLE
when importing a iCS file gcalcli says 'Python vobject module not installed!' even though it is installed

### ISSUE THREAD

**Issue by emilBeBri** [insanum/gcalcli#658]
I can successfully add events using 'add' or 'quick', but when using:

```


gcal1=$(mktemp)


gcalcli import "$gcal1" --calendar my-mail@gmail.com 

```
where `gcal1` is a temporary file that I create using a GTP-3.5 cli app so I can use better natural language. 

however I get: 

```
Python vobject module not installed!
```

Ok so I'm on manjaro linux, and they just changed it so that you have to use 

```

sudo pacman -S python-vobject

```

To install system-wide packages, otherwise you'll get:

```

python3 -m pip install vobject

error: externally-managed-environment

× This environment is externally managed
╰─> To install Python packages system-wide, try 'pacman -S
    python-xyz', where xyz is the package you are trying to
    install.

    If you wish to install a non-Arch-packaged Python package,
    create a virtual environment using 'python -m venv path/to/venv'.
    Then use path/to/venv/bin/python and path/to/venv/bin/pip.

    If you wish to install a non-Arch packaged Python application,
    it may be easiest to use 'pipx install xyz', which will manage a
    virtual environment for you. Make sure you have python-pipx
    installed via pacman.

note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
hint: See PEP 668 for the detailed specification.

```

So i installed with pacman and now I can import vobject from within python. 

However, gcalcli still gives me the error. It does not matter if it is a csv file or a ics file.

gcalcli installed with yay (e.g. AUR package), manjaro fully updated.

```

gcalcli v4.3.0 (Eric Davis, Brian Hartvigsen, Joshua Crowgey)


```

**Comment by emilBeBri** [comment]
Ok my workround is to use xargs to send the output as an argument to 'quick' instead. But it's only a workaround, not a solution - posting here for others to see:

```

cat $gcal1 |  xargs -I {} gcalcli quick "{}" --calendar my.mail@something.com

```

**Comment by dbarnett** [comment]
I don't see any obvious reason it wouldn't work from the info you provided. You might comment in AUR to ask the package maintainer if there's any gotcha with the optional dep. I glanced at the current PKGBUILD and didn't see anything strange about the setup...

It sounds like there'd be some disconnect between the python env used by the gcalcli executable you're running and the env python-vobject is installing into. Could you double check the gcalcli executable is indeed coming from the installed package and see if there's any obvious reason it wouldn't be hooked up to the system python env / sys.path?

**Comment by dbarnett** [comment]
BTW I think it could also be improved with more self-contained hints about how to add vobject support if it's missing, and maybe some logs to help troubleshoot these cases where it's expected to be there but somehow isn't.

**Comment by emilBeBri** [comment]
It was  because I was using Manjaro linux at the time (my first step into arch linux waters) - I  started having  other issues with python packages too, so I  switched to endeavour linux , also arch based, which should be - and is, in my experience - less prone to issues with outdated packages. so I think you can be pretty confident that was the issue and nothing on your end :)

**Comment by dbarnett** [comment]
Glad you got that resolved!

Just in case, I mentioned on AUR to verify the vobject part works as part of commenting there was a new release: https://aur.archlinux.org/packages/gcalcli. Anyway I'm probably going to make the vobject part an unconditional dep soon.
