### ISSUE TITLE
Hourly authentication "The authentication flow has completed." 

### ISSUE THREAD

**Issue by majman** [insanum/gcalcli#663]
(This has been driving me bananas - apologies in advance if this is not at all related to gcalcli. )

I've been using gcalcli in a custom [übersicht](https://github.com/felixhageloh/uebersicht) widget for years that displays my daily calendar events on my desktop. In the last few weeks, it's started to re-authorize _every hour_. 

Each time, it spawns a new browser window with the title "Authentication Status" and the message "The authentication flow has completed." - It's incredibly disruptive to my already infinitesimal attention span. 

The url for this status usually looks something like: 
`http://localhost:8080/?code=4%2F0XXXXXXXX&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcalendar`

I can see that my `.gcalcli_oauth` file (in my ~/ directory)  is updated hourly as well. 

I've searched for others having similar issues, but it seems most are hitting a 7 day re-auth issue (which sounds like a much more appealing problem!). Again, this could be something else not related to gcalcli, but any help/guidance would be tremendous!

**Comment by dbarnett** [comment]
Can you make sure you're using the latest auth instructions from the README (with `--client-id` and such) and see if it's still an issue after I merged #683?
