### ISSUE TITLE
App 'gcalcli' is blocked - The out-of-band (OOB) flow has been blocked

### ISSUE THREAD

**Issue by bittorf** [insanum/gcalcli#674]
It worked some days, but not anymore - maybe it's just me:

```
user@box:~$ gcalcli --version
gcalcli v4.3.0 (Eric Davis, Brian Hartvigsen, Joshua Crowgey)

user@box:~$ gcalcli list
 Access  Title
 ------  -----
  owner  ...@googlemail.com
<works>

bastian@NAS:~$ gcalcli --noauth_local_webserver agenda

Go to the following link in your browser:

    https://accounts.google.com/o/oauth2/v2/auth?client_id=XXXXX.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcalendar&access_type=offline&response_type=code
```

when accessing this link I get:

```
Error 400: invalid_request
The out-of-band (OOB) flow has been blocked in order to keep users secure. Follow the Out-of-Band (OOB) flow migration guide linked in the developer docs below to migrate your app to an alternative method.
Details: redirect_uri=urn:ietf:wg:oauth:2.0:oob 
```

It says:
"This app is blocked
This app has tried to access confidential data in your Google account. We have blocked access to protect your account."

![grafik](https://github.com/insanum/gcalcli/assets/198379/bc90f728-6bfc-4bb2-8022-44d36756b724)

**Comment by ErikKnowles** [comment]
It's not just you. I've been reauthorizing the app for a long time now, but today I'm seeing the same symptoms as you.

**Comment by MatHoffman** [comment]
same here, not just you :)

**Comment by bombermuecke** [comment]
![gcalclierr](https://github.com/insanum/gcalcli/assets/92254886/3fc1e99b-c161-433f-b819-f6a197ccc338)
I get this with "--noauth_local_webserver". Worked until last week.

**Comment by rcbellN51** [comment]
Had this problem for the past two days as well but seems to have resolved itself with a large (~700 pkg) update on FreeBSD 13.2. I don't think gcalcli itself was updates so may be an issue with some other dependency.

**Comment by ErikKnowles** [comment]
> Had this problem for the past two days as well but seems to have resolved itself with a large (~700 pkg) update on FreeBSD 13.2. I don't think gcalcli itself was updated so may be an issue with some other dependency.
> 
> Or, maybe it's coincidence, and it was resolved on Google's end.

My gcalcli's on a system that hasn't been updated in years (hey, it's a firewalled internal-use only computer so don't judge!), so a breaking system update's definitely not the problem.

**Comment by rcbellN51** [comment]
Likely broken (and fixed?) on Google's end then.

For the record I use "gcalcli --client-id=<clientID> --client-secret=<clientSecret>" to authenticate once a week since forever. Part of my troubleshooting efforts yesterday was to rename .gcalcli_cache and .gcalcli_oauth to .gcalcli_cache.bak and .gcalcli_oauth.bak in my home directory.

After the update today i just tried using "gcalcli --noauth_local_webserver agenda" with the same error from the past 2 days resulting. Then I remembered I'd renamed those files, renamed them back to .gcalcli_cache and .gcalcli_oauth and did my normal reauth step of "gcalcli --client-id=<clientID> --client-secret=<clientSecret>", and it worked (for the next week or so anyway).

**Comment by bombermuecke** [comment]
idk the reason, but it's working again.

**Comment by bittorf** [comment]
I can confirm, that it works again (for me too)  
On my side i had to perform these steps:  

````
#!/bin/sh
ID="XXX.apps.googleusercontent.com"
KEY="XXXXXX"

cd ~
mv .gcalcli_cache .gcalcli_cache.backup
mv .gcalcli_oauth .gcalcli_oauth.backup
gcalcli "--client-id=$ID" "--client-secret=$KEY" --noauth_local_webserver agenda
````

Thanks a lot to all of you, happy gcalcli'ing!
