### ISSUE TITLE
DeprecationWarning

### ISSUE THREAD

**Issue by newmanth** [insanum/gcalcli#675]
I'm getting this error message with any command:

==================

~$ gcalcli --version
/usr/bin/gcalcli:6: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  from pkg_resources import load_entry_point
usage: gcalcli [-h]...{full list of options}
gcalcli: error: argument command: invalid choice: '' (choose from 'list', 'search', 'edit', 'delete', 'agenda', 'updates', 'conflicts', 'calw', 'calm', 'quick', 'add', 'import', 'remind')

============================

Running Ubunty 23.10 with gcalcli version 4.3.0-1

It seems like the deprecationwarning is being treated as the command.  Is there someway to turn off the notification?

**Comment by dbarnett** [comment]
Just checked on 24.04 and I can't reproduce. Looks like in /usr/bin/gcalcli that import is nested in some try/except blocks, so it's possible it only ever repro'd on a particular version of python where certain system imports were/weren't satisfied... but I don't see anything that would get confused and treat warnings as part of the command or anything like that.

Can you still repro?

**Comment by newmanth** [comment]
I updated to Ubuntu 24.04 and to Python 3.12.3 and no longer see the notification.
