### ISSUE TITLE
HELP: What do I specify? (Documention missing bug)

### ISSUE THREAD

**Issue by RobertPHeller** [insanum/gcalcli#681]
I don't understand what I need to specify for --calendar.

marchhare% gcalcli list
 Access  Title
 ------  -----
  owner  Robert Heller / Deepwoods Software
 reader  Holidays in United States
 reader  Birthdays
marchhare% gcalcli import cal
Must specify a single calendar
marchhare% gcalcli import --calendar "Robert Heller / Deepwoods Software" cal
usage: gcalcli import [-h] [--reminder REMINDERS] [--default-reminders]
                      [--verbose] [--dump]
                      [file]
gcalcli import: error: argument file: can't open 'Robert Heller / Deepwoods Software': [Errno 2] No such file or directory: 'Robert Heller / Deepwoods Software'

Note: I have not used Google Calendar at all before.  I am trying to migrate from ical-tcl to Google Calendar, but basically have no real clue as to what is going on.  The documentation for gcalcli is somewhat lacking.

**Comment by dbarnett** [comment]
I think this is fixed now via #590.
