### ISSUE TITLE
HELP!!! GCalCli stopped working! I can only list calendars, and cannot do anything else

### ISSUE THREAD

**Issue by RobertPHeller** [insanum/gcalcli#682]
All of a sudden, gcalcli is popping up my browser and when I select my account I get this message:

This app is blocked

This app tried to access sensitive info in your Google Account. To keep your account safe, Google blocked this access.

Is this fixable, and if so how?

**Comment by jamespo** [comment]
You can try my patched version @ https://github.com/jamespo/gcalcli at your own risk.

I think I'm the only one that uses it, but I authenticated with it recently and use it daily.

**Comment by olejorgenb** [comment]
> I ended up deleting .gcalcli_oauth and re-authenticating it.

Does not work for me. I think google is being really anti-hacker. For some years ago they also make it virtually impossible for normal people to integrate with the gmail apis, basically killing the SMS+ backup app :angry:

**Comment by olejorgenb** [comment]
@insanum Any chance of getting the jamespo changes merged? From a _brief_ look it seems to not be some super cumbersome method requiring constantly creating new private app tokens.

**Comment by RobertPHeller** [comment]
I created a script go through all of the steps to re-authenticate, including 
killing "stuck" background processes.

At Tue, 21 May 2024 02:51:51 -0700 insanum/gcalcli ***@***.***> wrote:

> 
> > I ended up deleting .gcalcli_oauth and re-authenticating it.
> 
> Does not work for me. I think google is being really anti-hacker. For some years ago they also make it virtually impossible for normal people to integrate with the gmail apis, basically killing the SMS+ backup app :angry: 
> 

-- 
Robert Heller             -- Cell: 413-658-7953 GV: 978-633-5364
Deepwoods Software        -- Custom Software Services
http://www.deepsoft.com/  -- Linux Administration Services
***@***.***       -- Webhosting Services

**Comment by insanum** [comment]
> @insanum Any chance of getting the jamespo changes merged? From a _brief_ look it seems to not be some super cumbersome method requiring constantly creating new private app tokens. (You have to create a private token/app, but it doesn't seem to expire)

I'm all for it but I don't feel comfortable integrating patches as I haven't been active with this codebase in quite a long time. This project has multiple maintainers which might be better to handle. 

Also... if anyone would like to get maintainer access to gcalcli just let me know. This projects deserves some love.

**Comment by kurokirasama** [comment]
hey, any updates on this?

**Comment by RobertPHeller** [comment]
Yes, sort of.  What happens is the authentification "times out", because 
Google has not bothered to make the gcalcli application an "official" 
application (or whatever Google calls it).  It is still "experimental".

I have written a script that resets the authentification and restarts my 
programs using gcalcli.  It is a pain in the ass, but there is nothing for it. 
Maybe at some point I will figure out what the time frame is and schedule a 
pre-emptive recycling of the authentification (eg, something to just do every 
Sunday morning or something). 

It sucks that Google does not just provide a generic REST api that anyone can
just use in their code, eg something like Amazon's APIs (yes, you have to
signup to AWS and get an IAM secret code, but once done, it is good forever,
and free so long as one's usage is within the "free" teir usage limits).

Sometimes these excessive security measures are just plain dumb.

At Mon, 03 Jun 2024 16:16:06 -0700 insanum/gcalcli ***@***.***> wrote:

> 
> hey, any updates on this?
> 

-- 
Robert Heller             -- Cell: 413-658-7953 GV: 978-633-5364
Deepwoods Software        -- Custom Software Services
http://www.deepsoft.com/  -- Linux Administration Services
***@***.***       -- Webhosting Services

**Comment by kurokirasama** [comment]
I tried re-authenticating, even changed the client_id and secret, but i still get the "blocked" message...

**Comment by RobertPHeller** [comment]
Here is the script I use (sanitized):

---------Begin re-auth-gcalcli.sh ---------------
#!/bin/bash
killall TkGCal
rm ~/.gcalcli*
killall gcalcli
gcalcli --client-id XXXXXXXXXXXX.apps.googleusercontent.com --client-secret XXXXXXXXX-XXXXXXX-XXXXX list
rsync -a ~/.gcalcli_oauth ticktock:
ssh ticktock killall NetworkRPiClock
ssh ticktock /usr/local/bin/NetworkRPiClock -b -d 5
nohup /usr/local/bin/TkGCal -geometry +0+50 -iconic &
---------End re-auth-gcalcli.sh ---------------

The two programs I use (TkGCal and NetworkRPiClock) are on github:

https://github.com/RobertPHeller/TkGCal -- This is a GUI calendar program in 
    Tcl/Tk 
https://github.com/RobertPHeller/NetworkRPiClock -- This is a C++ program that 
    runs on a RPi 3 with a OLed bonnet (https://www.adafruit.com/product/3531) 
    that functions as my bedroom clock.

At Mon, 03 Jun 2024 18:32:59 -0700 insanum/gcalcli ***@***.***> wrote:

> 
> I tried re-authenticating, even changed the client_id and secret, but i still get the "blocked" message...
> 

-- 
Robert Heller             -- Cell: 413-658-7953 GV: 978-633-5364
Deepwoods Software        -- Custom Software Services
http://www.deepsoft.com/  -- Linux Administration Services
***@***.***       -- Webhosting Services

**Comment by kurokirasama** [comment]
> gcalcli --client-id XXXXXXXXXXXX.apps.googleusercontent.com --client-secret XXXXXXXXX-XXXXXXX-XXXXX list

Thanks for the script. However I did try re-authenticating, but I still got the "Access blocked" message

**Comment by RobertPHeller** [comment]
At Tue, 04 Jun 2024 08:07:02 -0700 insanum/gcalcli ***@***.***> wrote:

> 
> > gcalcli --client-id XXXXXXXXXXXX.apps.googleusercontent.com --client-secret XXXXXXXXX-XXXXXXX-XXXXX list
> 
> Thanks for the script. However I did try re-authenticating, but I still got the "Access blocked" message
> 

The key is to delete the ~/.gcalcli_oauth file.  If you don't delete it, it 
won't (re-)authenticate.  You also need to be sure all gcalcli processes are 
stopped.  And probably any other related processes.  My script starts by 
killing any outstanding processes and removing the ~/.gcalcli_oauth file:

rm ~/.gcalcli*
killall gcalcli

*Then* it does the authenticating.  This fires up a webrowser and you then 
need to jump through the hoops: select your Google account, the go on to 
accept the risks, etc.

-- 
Robert Heller             -- Cell: 413-658-7953 GV: 978-633-5364
Deepwoods Software        -- Custom Software Services
http://www.deepsoft.com/  -- Linux Administration Services
***@***.***       -- Webhosting Services

**Comment by dbarnett** [comment]
Looks resolved, more or less? Please reopen if not.

I also noted on #691 that the experience is especially bad having to manually rm/kill stuff in cases like this.
