### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by dbarnett** [insanum/gcalcli#688]
Doesn't look like PRs have been getting accepted or getting any follow-up in months or years. Is this project still active? Seeking a new maintainer?

Could you add a note about project status in the README?

**Comment by dbarnett** [comment]
Fishing through the GitHub network view I found @chasecovello had a fork with quite a few commits newer than this repo.

**Comment by PMDant** [comment]
Been curious about this as well, can we get this blessed by google so we don't have to manually re-up the certificate every 7 days? Google API requirements for public publishing should stay centralized with the project and publishing privately is not cost effective for open source software. I am not great with code but could help with the publishing documentation.

**Comment by dbarnett** [comment]
Let's discuss the auth in #603. Yeah I saw it's a hot issue with a lot of dupes in the tracker.

**Comment by PMDant** [comment]
Right, it looks like PR #683 is supposed to be a work around that is waiting for commit.

**Comment by insanum** [comment]
There are a couple maintainers of the gcalcli repo but none of us use gcalcli anymore. The project isn't dead in spirit but has definitely lost about all momentum.

I'm more than happy to add more maintainers to keep the project going. Let me know if you'd like to dive in and help out.

**Comment by dbarnett** [comment]
Thanks for following up!

I'm only just getting acquainted with the code but I'd be happy to help maintain it. Where do we start?

**Comment by insanum** [comment]
@dbarnett I sent you a collaborator invite. If you accept... start wherever you want and hack away. 😀

**Comment by dbarnett** [comment]
Hooray, so the project is definitively not dead. =)

I'm going to get to work cleaning up the issue tracker and looking through some uncontroversial PRs. @insanum I'd also like to make any maintainer norms explicit in a CONTRIBUTING.md. Please watch for a PR from me and I'll want to get your input there.

**Comment by dbarnett** [comment]
Alright, status update:
  - I've merged all open PRs that were simple to merge and bumped most others
  - Would like to put out a 4.4 release soon, created https://github.com/insanum/gcalcli/milestone/9 for that
  - Following up with known maintainers to see who's still interested to be involved (see #689)

A request: @chasecovello @jamespo and others, could you help me track down any major outstanding changes in your forks that would be important to get upstreamed here?

**Comment by dbarnett** [comment]
Wrapped up most of those things and I'm getting ready to prep a 4.4 release!

FWIW I'm still mostly merging my own PRs without code review because I'm not hearing back from any other maintainers when I bump for reviews.
