### ISSUE TITLE
Internal maintenance: Enable branch protection on master

### ISSUE THREAD

**Issue by dbarnett** [insanum/gcalcli#699]
Could we change GitHub project settings to avoid pushing changes straight to master without a PR? https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-protected-branches/managing-a-branch-protection-rule#creating-a-branch-protection-rule

@insanum will need your help for that since I don't have permission to configure project Settings. Just minimal branch protection settings ideally, where the systems nudge you to create a PR instead of pushing directly to master, but repo maintainers can still opt to override the protection if needed.

**Comment by dbarnett** [comment]
BTW @mdengler @jcrowgey any concerns if I rename the master branch to main?

**Comment by mdengler** [comment]
go for it

**Comment by insanum** [comment]
> go for it

agreed

**Comment by jcrowgey** [comment]
No concerns

**Comment by dbarnett** [comment]
@insanum still need your help on this, I don't have permission to access the repo's settings menu here.

**Comment by insanum** [comment]
Done. Renamed master to main and added branch protection requiring PRs for all commits. Force bypass is enabled for those of us who have write access to the repo.
