### ISSUE TITLE
RecursionError: maximum recursion depth exceeded on latest git build

### ISSUE THREAD

**Issue by ajkessel** [insanum/gcalcli#735]
```
    sys.exit(main())
             ^^^^^^
  File "/home/adam/.venv/lib/python3.12/site-packages/gcalcli/cli.py", line 145, in main
    gcal = GoogleCalendarInterface(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/adam/.venv/lib/python3.12/site-packages/gcalcli/gcal.py", line 73, in __init__
    self._get_cached()
  File "/home/adam/.venv/lib/python3.12/site-packages/gcalcli/gcal.py", line 228, in _get_cached
    self.get_cal_service().calendarList().list(
    ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/adam/.venv/lib/python3.12/site-packages/gcalcli/gcal.py", line 187, in get_cal_service
    credentials=self._google_auth())
                ^^^^^^^^^^^^^^^^^^^
  File "/home/adam/.venv/lib/python3.12/site-packages/gcalcli/gcal.py", line 176, in _google_auth
    self.credentials = auth.authenticate(client_id, client_secret)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/adam/.venv/lib/python3.12/site-packages/gcalcli/auth.py", line 20, in authenticate
    credentials = flow.run_local_server(open_browser=False)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/adam/.venv/lib/python3.12/site-packages/google_auth_oauthlib/flow.py", line 458, in run_local_server
    self.fetch_token(
  File "/home/adam/.venv/lib/python3.12/site-packages/google_auth_oauthlib/flow.py", line 285, in fetch_token
    return self.oauth2session.fetch_token(self.client_config["token_uri"], **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/adam/.venv/lib/python3.12/site-packages/requests_oauthlib/oauth2_session.py", line 381, in fetch_token
    r = self.request(
        ^^^^^^^^^^^^^
  File "/home/adam/.venv/lib/python3.12/site-packages/requests_oauthlib/oauth2_session.py", line 566, in request
    return super(OAuth2Session, self).request(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/adam/.venv/lib/python3.12/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/adam/.venv/lib/python3.12/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/adam/.venv/lib/python3.12/site-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/home/adam/.venv/lib/python3.12/site-packages/urllib3/connectionpool.py", line 789, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "/home/adam/.venv/lib/python3.12/site-packages/urllib3/connectionpool.py", line 466, in _make_request
    self._validate_conn(conn)
  File "/home/adam/.venv/lib/python3.12/site-packages/urllib3/connectionpool.py", line 1095, in _validate_conn
    conn.connect()
  File "/home/adam/.venv/lib/python3.12/site-packages/urllib3/connection.py", line 652, in connect
    sock_and_verified = _ssl_wrap_socket_and_match_hostname(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/adam/.venv/lib/python3.12/site-packages/urllib3/connection.py", line 767, in _ssl_wrap_socket_and_match_hostname
    context.verify_mode = resolve_cert_reqs(cert_reqs)
    ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/ssl.py", line 680, in verify_mode
    super(SSLContext, SSLContext).verify_mode.__set__(self, value)
  File "/usr/lib/python3.12/ssl.py", line 680, in verify_mode
    super(SSLContext, SSLContext).verify_mode.__set__(self, value)
  File "/usr/lib/python3.12/ssl.py", line 680, in verify_mode
    super(SSLContext, SSLContext).verify_mode.__set__(self, value)
  [Previous line repeated 978 more times]
RecursionError: maximum recursion depth exceeded
```

**Comment by dbarnett** [comment]
Fun! No idea what's going on there, but I can take a look as part of prepping for 4.5 release.

**Comment by ajkessel** [comment]
Anything I can do to try to narrow the issue? Oddly, on the same machine, gcalcli from pip+git is working with Windows Python but not Python in WSL. Windows is on Python 3.12.3 and WSL/Ubuntu on 3.12.4, although I doubt that minor version bump is the cause of this recursion error.

**Comment by dbarnett** [comment]
Nah, I expect I'll be able to narrow it down easily enough once I get a minute to stare at the code. My hunch from what I see there is that when something is funny with your auth (which changed a lot in the 4.4 release), it's getting stuck somehow trying to renew it. 

If you haven't tried deleting the temporary auth files and redoing authentication fresh, you might see whether that works around the issue to get you unstuck.

**Comment by ajkessel** [comment]
I did try reauthorizing when this first happened and it didn't fix it -- but then I just now tried again and it did. No idea what was different!

**Comment by dbarnett** [comment]
Oh interesting, had a look through this and the recursion is all inside python3.12/ssl.py, just triggered from gcalcli by `flow.run_local_server(open_browser=False)`. Seems very unlikely that it'd be a bug within gcalcli that would make sense to fix within our code. My hunch is there was just a bad version of one of the dependencies out there somewhere and that they might've already yanked it so you wouldn't be able to repro on a fresh install.

Still, I'll leave the issue open a little longer in case anyone else runs into it or someone wants to try to narrow down a minimal repro to report against whatever upstream project. https://stackoverflow.com/questions/49820173/recursionerror-maximum-recursion-depth-exceeded-from-ssl-py-supersslcontex suggests this error tends to come from some prevalent monkey-patching hacks, although I'm not sure if any dependency of ours is actually using gevent or any of the other suspects mentioned there.

**Comment by ajkessel** [comment]
Now I'm wondering if it's actually a Google issue. I just attempted to replicate the problem on five different boxes (including Windows, WSL, Linux, and Mac) and it worked fine on all of them. I don't think I've changed any of my packages since the last check -- is it possible that some exception condition on making the API request is being misinterpreted by either gcalcli or one of its dependencies?

**Comment by dbarnett** [comment]
So... now I am seeing the same, and I can't get past it when running from a virtualenv install of gcalcli, but I can using a system-installed version (full workaround instructions below).

I found a relevant urllib3 issue that looks like the right upstream issue (backlinked above), but it's been closed for years with supposedly "no new reports of this issue in some time". Still pretty sure there's no possible fix on our end.

## Workaround

When this does happen it seems to only affect versions installed locally through pip etc, so try authenticating **using a system-installed version**, and then any other version should be able to reuse the same token.

If anyone's still stuck after trying that, please let us know.

**Comment by dbarnett** [comment]
For reference, here's the repro that seemed to work consistently for me:

1. Clone https://github.com/insanum/gcalcli @ v4.4.0
2. cd into that working dir
3. `python3.12 -m venv .env` + `source .env/bin/activate`
4. `pipx install .`
5. Set up auth per https://github.com/insanum/gcalcli/blob/HEAD/docs/api-auth.md to get `client-id`/`client-secret`
6. Delete or move aside any existing ~/.gcalcli_oauth file
7. `gcalcli --client-id=XXXXXX --client-secret=YYYYYY list`

**Comment by dbarnett** [comment]
Forked off #785 for the error message improvement that's already implemented for 4.5 release.

I'll leave this bug open to track the general issue blocked on upstream.

**Comment by dbarnett** [comment]
@ZaxonXP hit this after upgrading to 4.5.0 (I think in a system-level install?).

I'd like to find a general-purpose workaround and isolate an actual root cause. urllib3/urllib3#3482 doesn't seem like it's getting attention. But I'm the short term, if you can get authenticated on **any** version of gcalcli >=4.4, you should be able to continue using the token on any other version that's at least as recent. So in a pinch I'd try downgrading/upgrading or using alternate installation methods to get it unstuck as a workaround.

**Comment by dbarnett** [comment]
Ohhhhh, this is happening because of `truststore.inject_into_ssl()` (#726). On my system if I move it back to the top of the file I can make the repro disappear, and then move it back to make it reappear.

Merging PR #796 to hopefully make all the nonsense stop...

**Comment by glerner** [comment]
I have Linux Mint 21.2 Cinnamon

> For reference, here's the repro that seemed to work consistently for me:
> 
> 1. Clone https://github.com/insanum/gcalcli @ v4.4.0
> 2. cd into that working dir
> 3. `python3.12 -m venv .env` + `source .env/bin/activate`
> 4. `pip install .`
> 5. Set up auth per https://github.com/insanum/gcalcli/blob/HEAD/docs/api-auth.md to get `client-id`/`client-secret`
> 6. Delete or move aside any existing ~/.gcalcli_oauth file
> 7. `gcalcli --client-id=XXXXXX --client-secret=YYYYYY list`
> 
> but note the docs/api-auth.md part makes it not a very "minimal" minimal repro.

```
python3.12 -m venv .env + source .env/bin/activate
    Command 'python3.12' not found, did you mean:
    command 'python3.11' from deb python3.11 (3.11.0~rc1-1~22.04)
    command 'python3.10' from deb python3.10 (3.10.12-1~22.04.6)

```
```
    python3 --version
    Python 3.10.12

```
```
python3 -m venv .env + source .env/bin/activate
    Error: Unable to create directory '/home/george/sites/gcalcli/.env/bin/activate'

```

```
python3 -m venv .env
source .env/bin/activate

```
Breaking it into two commands, without the python specified version, works

**Comment by dbarnett** [comment]
> Breaking it into two commands, without the python specified version, works

Yes, that was the intention, that's why if you look the two commands were code-formatted but not the "+" between them. I made it one command with a semicolon in there to avoid confusion...

Were you trying to repro for a particular purpose? I believe the bug is fixed and the root cause identified as an issue with how the `truststore` hooks were called.
