### ISSUE TITLE
Building from source version from setuptools-scm error

### ISSUE THREAD

**Issue by PMDant** [insanum/gcalcli#799]
Running DietPi v9.7.1 on RPi 2 B with gcalcli 4.3.0 installed from APT.

When building 4.5.0 from source, over the deb package from Raspbian, gcalcli still runs but returns `/usr/local/lib/python3.11/dist-packages/gcalcli-0.0.0-py3.11.egg/gcalcli/__init__.py:5: UserWarning: Failed to load __version__ from setuptools-scm`. 

Some commands during installation (They were run as root on my pi so cant install through pip)...
`# python3 setup.py --version`
`/usr/lib/python3/dist-packages/setuptools/config/pyprojecttoml.py:108: _BetaConfiguration: Support for [tool.setuptools] in pyproject.toml is still *beta*.
  warnings.warn(msg, _BetaConfiguration)
0.0.0`

`# python3 setup.py install --dry-run`  (this was a mistake on code order, meant to have the --dry-run actually do a dry run but installed instead)

**Comment by PMDant** [comment]
#793 Looks to be the same issue, will try a fresh pull instead of the source tar from releases and report back.

**Comment by PMDant** [comment]
Still receiving the same error after fresh git pull.
`# gcalcli --version`
`/usr/local/lib/python3.11/dist-packages/gcalcli-0.0.0-py3.11.egg/gcalcli/__init__.py:5: UserWarning: Failed to load __version__ from setuptools-scm
gcalcli __unknown__`

**Comment by dbarnett** [comment]
Yeah, looks like the same basic issue. Can you point me to any details on the build scripts and sources you're using?

The preferred option is building from an archive that has the .git dir and git tooling available. If that's not easy then you can force it to tag the known version number with `SETUPTOOLS_SCM_PRETEND_VERSION_FOR_GCALCLI=4.5.0`. That's what we'll do for the AUR package, and nothing has been changed in the repo to work around that issue, only in build scripts.

**Comment by dbarnett** [comment]
BTW I'm happy to make accommodations to try to offer snapshots with _version.py already written if there's some convention for that level of "prebuilt" source archive, but at that point you might as well use the archive from pypi as the source of truth, right?

**Comment by PMDant** [comment]
Process for last iteration was...
`# git clone http://gcalcli` - source 
`# python3 setup.py install` - install
assuming I was trying to be a vanilla as possible but not a versed in python installs as I probably should be, I am a script-er at best. 
My only catch to using the pypi source is that I am running root and pip gets mad.  I was originally installed through the Raspbian deb packages and was looking to build a deb if possible but had not gotten that far, my brain is still pretty stuck in mainframe land.
I did just attempt to add the `SETUPTOOLS_SCM_PRETEND_VERSION_FOR_GCALCLI=4.5.0` but it didn't like that so will try to plink with the source I have and maybe get that little override put in there generically.

**Comment by dbarnett** [comment]
Add `SETUPTOOLS_SCM_PRETEND_VERSION_FOR_GCALCLI=4.5.0` on the `python setup.py` command and that should work fine. (BTW `pip install .` is preferred over setup.py where available.)

If it's from a git clone and you have git installed I'm not really sure why it wouldn't pick up the version automatically, but either way it should be an easy fix.

**Comment by PMDant** [comment]
Yeah not sure I was doing that right either because it kept bombing but I got it fixed, just added a `_version.py` to the `gcalcli/` directory with `__version__ = '4.5.0'` and reran it so its no longer complaining. Not sure git was setup to create that file when packaging or if its worth it but if it helps anyone else, this fixes it when installing with `python setup.py install`.  I would suspect pip still the better option but running pip with root is frowned upon so work around I go lol thanks for your input/help and giving this project new life! @dbarnett

**Comment by dbarnett** [comment]
Great, glad you got it sorted out! 

A few clarifications for anyone else following along: 
 - The version file is created via pip/setuptools as part of build/install, not directly by git or other steps 
 - You can try creating the _version.py file manually, sounds like that's what you ended up doing, but still python **build** commands will probably choke on it because they're expecting to *output* the version file, not take it as *input*
 - Running `pip install` as root should be exactly as recommended as running `python setup.py install` as root and works exactly the same, assuming you have pip available at all to run as root
