### ISSUE TITLE
using the --detail all and --detail_all commands

### ISSUE THREAD

**Issue by Logansfury** [insanum/gcalcli#812]
Hello,

I have a bash script that executes a gcalcli --nocolor agenda command. I am trying to add --detail all or --detail_all that I found in the user manual. Every time I try to add it however, it breaks the ability to display events.

I am using the bash script to format everything for display in Conky:  https://i.imgur.com/XIdifFi.png

Can anyone please help?

**Comment by michaelmhoffman** [comment]
Please specify the exact `gcalcli` command used and exact output on command line, not what is transformed in your script.

**Comment by Logansfury** [comment]
Hello Michael,

Thank you for getting back to me. I am using the following bash script to
get 14 days of google calendar events:

#!/bin/bash

# Fetch events and format the output
current_events=$(gcalcli --nocolor --details end agenda "$(date
+'%Y-%m-%d')" "$(date -d '+14 days' +'%Y-%m-%d')")
previous_events_file="/tmp/previous_events.txt"

# Check if the previous events file exists
if [ -f "$previous_events_file" ]; then
    # Compare current events with previous events
    if ! diff <(echo "$current_events") "$previous_events_file" >
/dev/null; then
        # If there are new events, play the sound
        mpg123 /home/logansfury/.conky/gcal/cal_event.mp3
    fi
fi

# Update the previous events file with current events
echo "$current_events" > "$previous_events_file"

echo "\${color1}\${voffset 4}Today\${voffset -12}" # Adjusted voffset
# Get today's events
today_events=$(gcalcli --nocolor agenda "$(date +'%Y-%m-%d')" "$(date -d
'+1 day' +'%Y-%m-%d')")
if [[ -z "$today_events" || "$today_events" == *"No Events Found"* ]]; then
    echo " "  # Print weekday abbreviation only
else
    echo "$today_events" | while IFS= read -r line; do
        echo "\${color1}\${goto 54}\${voffset -15}${line:0:11}"  # Set
spacing for events
        echo "\${color0}${line:11}"
    done
fi

echo "\${color1}\${voffset 14}Tomorrow\${voffset -12}" # Adjusted voffset
# Get tomorrow's events
tomorrow_events=$(gcalcli --nocolor agenda "$(date -d 'tomorrow'
+'%Y-%m-%d')" "$(date -d 'tomorrow +1 day' +'%Y-%m-%d')")
if [[ -z "$tomorrow_events" || "$tomorrow_events" == *"No Events Found"*
]]; then
    echo " "  # Print weekday abbreviation only
else
    echo "$tomorrow_events" | while IFS= read -r line; do
        echo "\${color1}\${goto 84}\${voffset -15}${line:0:11}"  # Set
spacing for events
        echo "\${color0}${line:11}"
    done
fi

# Fetch events and format the output for the next days
for i in {2..11}; do
    day_date=$(date -d "+$i days" +'%Y-%m-%d')
    day_events=$(gcalcli --nocolor agenda "$day_date" "$(date -d "+$((i +
1)) days" +'%Y-%m-%d')")

if [[ -z "$day_events" || "$day_events" == *"No Events Found"* ]]; then
    echo "\${color1}\${voffset 10}$(date -d "$day_date" +'%a')\${voffset
-12}"  # Print weekday abbreviation only
else
    echo "$day_events" | while IFS= read -r line; do
        # Print the first 11 characters and append the year
        echo "\${color1}\${voffset -10}${line:0:11}"
        # Print the remaining part of the line
        echo "\${color0}${line:11}\${voffset -4}"
    done
fi
echo " "  # Add a blank line for separation
done

The issue is in the line: current_events=$(gcalcli --nocolor --details end
agenda "$(date +'%Y-%m-%d')" "$(date -d '+14 days' +'%Y-%m-%d')")

I cant seem to find the correct syntax in this line to display the end time
of events.

Thank you again for taking the time to look this over :)

Sincerely,

Logan

**Comment by michaelmhoffman** [comment]
I am not able to go through your whole script. In the future please provide a single command that exposes your problem. In doing so you may find that the reason for the problem becomes more obvious to you.

You need to specify detail options *after* the subcommand. So here it would be `gcalcli agenda --details end`.

**Comment by dbarnett** [comment]
If that's the issue and `--details` was just silently ignored, maybe we could have it error or print a warning instead of ignoring.

**Comment by Logansfury** [comment]
Hello,

I have used the --details end option edited into the multi-day agenda
command every way I can think of, and I just can't get a display of event
end times.

**Comment by michaelmhoffman** [comment]
@Logansfury Please supply the output of `gcalcli agenda --details end` here. You can change any sensitive information in event descriptions to `[redacted]`.

**Comment by michaelmhoffman** [comment]
> If that's the issue and `--details` was just silently ignored, maybe we could have it error or print a warning instead of ignoring.

@dbarnett For me, it gives an error, so I suspect the problem is using it in a command substitution context where the error is hidden. That isn't a problem we can address though.

**Comment by Logansfury** [comment]
I am sorry I just now noticed the request to show the terminal output of
the gcalcli agenda --details end.

In terminal it seems to be working fine:

***@***.***:~$ gcalcli agenda --details end

Sat Nov 16           change patch
                     The Leonid meteor shower will reach its peak.

Mon Nov 18  10:00am - 12:00pm  timed event

Wed Nov 20           Ink Master S16E07
***@***.***:~$

The timed event I created for mon nov 18 shows start and end times.

However when using this in a bash script with a stated time range, it
doesnt work:

***@***.***:~$ gcalcli agenda --nocolor --details end"$(date
+'%Y-%m-%d')" "$(date -d '+9 days' +'%Y-%m-%d')"
usage: gcalcli agenda [-h]
                      [--details
{calendar,location,length,reminders,description,url,conference,attendees,email,attachments,end,all}]
                      [--color-owner COLOR_OWNER]
                      [--color-writer COLOR_WRITER]
                      [--color-reader COLOR_READER]
                      [--color-freebusy COLOR_FREEBUSY]
                      [--color-date COLOR_DATE]
                      [--color-now-marker COLOR_NOW_MARKER]
                      [--color-border COLOR_BORDER]
                      [--color-title COLOR_TITLE] [--tsv] [--nostarted]
                      [--nodeclined] [--width CAL_WIDTH] [--military]
                      [--no-military] [--override-color]
                      [start] [end]
gcalcli agenda: error: argument --details: invalid choice: 'end2024-11-16'
(choose from 'calendar', 'location', 'length', 'reminders', 'description',
'url', 'conference', 'attendees', 'email', 'attachments', 'end', 'all')
***@***.***:~$ gcalcli agenda --details end"$(date
+'%Y-%m-%d')" "$(date -d '+9 days' +'%Y-%m-%d')"
usage: gcalcli agenda [-h]
                      [--details
{calendar,location,length,reminders,description,url,conference,attendees,email,attachments,end,all}]
                      [--color-owner COLOR_OWNER]
                      [--color-writer COLOR_WRITER]
                      [--color-reader COLOR_READER]
                      [--color-freebusy COLOR_FREEBUSY]
                      [--color-date COLOR_DATE]
                      [--color-now-marker COLOR_NOW_MARKER]
                      [--color-border COLOR_BORDER]
                      [--color-title COLOR_TITLE] [--tsv] [--nostarted]
                      [--nodeclined] [--width CAL_WIDTH] [--military]
                      [--no-military] [--override-color]
                      [start] [end]
gcalcli agenda: error: argument --details: invalid choice: 'end2024-11-16'
(choose from 'calendar', 'location', 'length', 'reminders', 'description',
'url', 'conference', 'attendees', 'email', 'attachments', 'end', 'all')
***@***.***:~$

Is there something wrong with my syntax?
