### ISSUE TITLE
lineart broken in conky

### ISSUE THREAD

**Issue by b46** [insanum/gcalcli#97]
Hi!

I try to setup gcalcli and conky to show a weekly calendar. Here is the line in my .conkyrc file:
${execp ~/gcalcli-master/gcalcli --locale fr_CH.UTF-8 --military --conky calw}

The screenshot shows a portion of the result.
![screenshot-20130805-687398823](https://f.cloud.github.com/assets/5165188/909340/28d74d0a-fdbc-11e2-9db2-2cd5b9baa9d1.png)

I have to use the "--nolineart" flag for it to work, but it's kind of ugly...

Is there a way to make it work?

Thanks for you work!

**Comment by jcrowgey** [comment]
![lineart_in_conky](https://user-images.githubusercontent.com/4524026/44382052-24a4e180-a4c8-11e8-9f16-e4570c7dd2af.png)
